<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>What is probability?</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR1</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li>
  <a href="intro_r_rstudio_year1.html">DAPR1 starts here</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to data and R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_data_types.html">1/1: Collecting data</a>
    </li>
    <li>
      <a href="02_categorical.html">1/2: Categorical data</a>
    </li>
    <li>
      <a href="03_numerical.html">1/3: Numerical data</a>
    </li>
    <li>
      <a href="04_relationships.html">1/4: Relationships</a>
    </li>
    <li>
      <a href="05_functions.html">1/5: Types of relations</a>
    </li>
    <li class="dropdown-header">1/6: Break week!</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Probability &amp; sampling
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_probability_basics.html">1/7: Probability basics</a>
    </li>
    <li>
      <a href="08_probability_rules.html">1/8: Probability rules!</a>
    </li>
    <li>
      <a href="09_discrete_distributions.html">1/9: Discrete random variables</a>
    </li>
    <li>
      <a href="10_continuous_distributions.html">1/10: Continuous random variables</a>
    </li>
    <li>
      <a href="11_sampling_distributions.html">1/11: Sampling distributions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Hypothesis testing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="12_bootstrap_cis.html">2/1: Bootstrap &amp; CIs</a>
    </li>
    <li>
      <a href="13_hypothesis_testing.html">2/2: Hypothesis testing: p-values</a>
    </li>
    <li>
      <a href="14_critical_values.html">2/3: Hypothesis testing: critical values</a>
    </li>
    <li>
      <a href="15_connecting_ci_ht.html">2/4: Hypothesis testing &amp; CIs</a>
    </li>
    <li>
      <a href="16_ht_errors.html">2/5: Making decisions</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Basic tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="17_one_sample_mean.html">2/7: Test for one mean</a>
    </li>
    <li>
      <a href="18_two_sample_means.html">2/8: Test for two means</a>
    </li>
    <li>
      <a href="19_paired_t_test.html">2/9: Test for paired samples</a>
    </li>
    <li>
      <a href="20_chi_square.html">2/10: Chi-square</a>
    </li>
    <li>
      <a href="21_covcor.html">2/11: Covariance and correlation</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">What is probability?</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand the importance of uncertainty in data analysis.</li>
<li>Understand principle of probability as long run frequency.</li>
<li>Understand the concept of assigning probability to events.</li>
</ol>
</div>
<div id="introduction" class="section level2 unnumbered">
<h2>Introduction</h2>
<p>Think about flipping a coin once. Can you predict the outcome?</p>
<p>Think about flipping a coin many times, one million say. Are you able to
predict roughly how many heads or tails will show up?</p>
<p>It’s hard to guess the outcome of just one coin flip because the outcome
could be one of two possible outcomes. Hence, we say that flipping a
coin is a <em>random experiment</em> or <em>random process.</em></p>
<p>If you flip it over and over, however, you can predict the proportion of
heads you’re likely to see <em>in the long run.</em> In the long run simply
means if you were to repeat the same experiment over and over many times
under the same conditions.</p>
<p>This discussion leads us to define the specific type of randomness that
we will be studying in this course.</p>
<div class="frame">
<p><strong>What is randomness?</strong></p>
<p>We will say that a repeatable process is random if its outcome is</p>
<ul>
<li>unpredictable in the short run, and</li>
<li>predictable in the long run.</li>
</ul>
</div>
<p>It is this long-term predictability of randomness that we will use
throughout the rest of the course. To do that, we will need to talk
about the probabilities of different outcomes and learn some rules for
dealing with them.</p>
</div>
<div id="video-activity" class="section level2">
<h2>Video activity</h2>
<p>Please watch the following video, explaining you to the concept of
“randomness”.</p>
<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/H2lJLXS3AYM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</center>
</div>
<div id="random-experiments-and-probability" class="section level2">
<h2>Random experiments and probability</h2>
<div id="example-1-flipping-a-coin" class="section level3">
<h3>Example 1: Flipping a coin</h3>
<p>The process of flipping a coin is an example of a random experiment as
its outcome is uncertain. We do not know beforehand whether the coin
will land heads (H) or tails (T).</p>
<p>The collection of all possible outcomes is known as the <em>outcome space</em>
or <em>sample space.</em> We typically denote the sample space by <span class="math inline">\(S\)</span>. In the
coin example, this is:
<span class="math display">\[
S = \{ H, T \}
\]</span></p>
<p>One particular repetition (i.e. instance) of such experiment is known as
a <em>trial</em>.</p>
</div>
<div id="example-2-throwing-a-die" class="section level3">
<h3>Example 2: Throwing a die</h3>
<p>Another example of a random experiment is throwing a six-faced die as,
for each trial, we can not exactly predict which face will appear.</p>
<p>The list of possible outcomes for the die experiment is <span class="math inline">\(1, 2, ..., 6\)</span>.
Hence, the sample space can be written:
<span class="math display">\[
S = \{1, 2, 3, 4, 5, 6 \}
\]</span></p>
</div>
<div id="events" class="section level3">
<h3>Events</h3>
<p>Consider again the die experiment. Often, we are not interested in the
probability of observing a particular outcome, such as 3, but rather in
a collection of outcomes together. For example, we might be interested
in the probability of observing an even number.</p>
<p>Such collections of outcomes are called <strong>events.</strong> More formally, an
event is a set of outcomes.</p>
<p>Each individual outcome is also considered an event. To distinguish,
some people call <em>simple events</em> the individual outcomes, and <em>compound
events</em> a collection of two or more outcomes.</p>
<p>The event “an even number appears” is simply the collection of even
outcomes. We could call it “E” for “even” and write it
as: <span class="math display">\[E = \{ 2, 4, 6\}\]</span></p>
<p>Two important events are:</p>
<ul>
<li>the <strong>empty set</strong>: the set of no outcomes, denoted <span class="math inline">\(\emptyset\)</span>;</li>
<li>the <strong>sample space</strong>: the set of all outcomes, denoted <span class="math inline">\(S\)</span>.</li>
</ul>
<p>In general, a finite sample space is written
<span class="math display">\[
S = \{s_1, s_2, ..., s_n\}
\]</span></p>
<p>where each <span class="math inline">\(s_i\)</span> represents an outcome or simple event.</p>
</div>
<div id="example-3-flipping-2-coins" class="section level3">
<h3>Example 3: Flipping 2 coins</h3>
<p>Consider flipping 2 coins simultaneously. The sample space is:
<span class="math display">\[
S = \{ (H,H), (H,T), (T,H), (T,T)\}
\]</span></p>
<p>Typical events could be:</p>
<ul>
<li>Observing tails at least once, <span class="math inline">\(A = \{(H,T), (T,H), (T,T)\}\)</span></li>
<li>Observing the same face twice, <span class="math inline">\(B = \{(H,H), (T,T)\}\)</span></li>
</ul>
</div>
</div>
<div id="defining-probability" class="section level2">
<h2>Defining probability</h2>
<p>Consider repeating the random process of throwing a die many times, 500
say, and recording whether or not an even number appears. We will now
create a table listing the result of each trial.</p>
<p>First, we load the <code>tidyverse</code> package:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<p>Next, we create the sample space:</p>
<pre class="r"><code>S &lt;- 1:6
S</code></pre>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>The following code defines the event “an even number appears”:</p>
<pre class="r"><code>E &lt;- c(2, 4, 6)
E</code></pre>
<pre><code>## [1] 2 4 6</code></pre>
<p>Say, now, that the outcome of a roll is 3. How can we check whether the
outcome belongs to the event of interest <span class="math inline">\(E\)</span>?</p>
<p>We can use the <code>%in%</code> function to ask R: “Is 3 in E?” The answer can be
TRUE or FALSE.</p>
<pre class="r"><code>3 %in% E</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Suppose instead, that the outcome of a roll is 2. Is 2 in E?</p>
<pre class="r"><code>4 %in% E</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>We now specify how many trials we will be performing:</p>
<pre class="r"><code>num_trials &lt;- 500</code></pre>
<p>Next, we repeat the experiment <code>num_trials</code> times and compute the
accumulated percentage of even outcomes:</p>
<pre class="r"><code>experiment &lt;- tibble(
    trial = 1:num_trials,
    outcome = sample(S, num_trials, replace = TRUE),
    is_even = outcome %in% E,
    cumul_even = cumsum(is_even),
    cumul_perc_even = 100 * cumsum(is_even) / trial
)</code></pre>
<p>The following code displays the top 10 rows of the experiment:</p>
<pre class="r"><code>head(experiment, n = 10)</code></pre>
<pre><code>## # A tibble: 10 x 5
##    trial outcome is_even cumul_even cumul_perc_even
##    &lt;int&gt;   &lt;int&gt; &lt;lgl&gt;        &lt;int&gt;           &lt;dbl&gt;
##  1     1       5 FALSE            0             0  
##  2     2       2 TRUE             1            50  
##  3     3       4 TRUE             2            66.7
##  4     4       4 TRUE             3            75  
##  5     5       2 TRUE             4            80  
##  6     6       3 FALSE            4            66.7
##  7     7       4 TRUE             5            71.4
##  8     8       2 TRUE             6            75  
##  9     9       5 FALSE            6            66.7
## 10    10       2 TRUE             7            70</code></pre>
<hr />
<p><strong>Understanding the code</strong>. Let’s inspect each column in turn:</p>
<ul>
<li><code>trial</code> records the number of each trial: 1, 2, …, 500;</li>
<li><code>outcome</code> lists the result of each trial: 1, or 2, …, or 6;</li>
<li><code>is_even</code> checks whether the outcome of each trial belongs to the
event <span class="math inline">\(E\)</span> (=TRUE) or not (=FALSE);</li>
<li><code>cumul_even</code> computes the cumulative sum of <code>is_even</code>.</li>
</ul>
<p>As we saw, the <code>is_even</code> column contains either TRUE or FALSE. This was
created with the function <code>%in%</code>, which is equivalent to asking a
question: Is the outcome in <span class="math inline">\(E\)</span>? The result will be either TRUE or
FALSE. We note that, when summed, R considers a TRUE as 1, and a FALSE
as 0. For example, the cumulative sum of
<code>c(TRUE, FALSE, TRUE, TRUE, FALSE)</code> is <code>c(1, 1, 2, 3, 3)</code>. Finally, the
column <code>cumul_perc_even</code> computes the accumulate percentage of even
outcomes.</p>
<hr />
<p>The first trial’s outcome was 5, which is not an even number. Hence the
cumulative percentage of even outcomes is 0 out of 100, or 0%. The next
four trials lead to 2, 4, 4, and 2 respectively, which all are even
numbers. The cumulative percentages will be 1 out of 2 (50%), 2 out of 3
(66.67%), 3 out of 4 (75%), and 4 out of 5 (80%). Next, we observe 3,
which is odd, hence the cumulative percentage of even outcomes is now 4
out of 66.67%, and so on.</p>
<p>Finally, we plot the accumulated percentage of even numbers against the
trial number:</p>
<pre class="r"><code>ggplot(experiment, aes(x = trial, 
                       y = cumul_perc_even)) +
    geom_point(color = &#39;darkolivegreen4&#39;) +
    geom_line(color = &#39;darkolivegreen4&#39;) +
    geom_hline(aes(yintercept = 50), color = &#39;red&#39;, linetype = 2) +
    labs(x = &quot;Trial number&quot;, y = &quot;Accumulated percent even&quot;)</code></pre>
<p><img src="07_probability_basics_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>As the number of trials increase, we see that the curve approaches 50%,
which is 0.5, and that the cumulative percentage of even outcomes keeps
fluctuating around 50%.</p>
<div class="question-begin">
Checkpoint
</div>
<div class="question-body">
<p>What’s the probability of obtaining an even number when throwing a fair
die?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-61" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-61&#39;, &#39;sol-start-61&#39;)"></span>
</div>
<div id="sol-body-61" class="solution-body" style="display: none;">
<p>If you answered 0.5 (or 50%), then you are on the right track!</p>
</div>
<p class="solution-end">
</p>
<p>Based on the graph, it looks like the relative frequency of an even
number settles down to about 50%, so saying that the probability is
about 0.5 seems like a reasonable answer.</p>
<p>But do random experiments always behave well enough for this definition
of probability to always apply? Perhaps the relative frequency of an
event can bounce back and forth between two values forever, never
settling on just one number?</p>
</div>
<div id="the-law-of-large-numbers" class="section level2">
<h2>The law of large numbers</h2>
<p>Fortunately, Jacob Bernoulli proved the <em>Law of large numbers (LLN)</em> in
the 18th century, giving us the peace of mind that we need.</p>
<div class="yellow">
<p><strong>Law of large numbers</strong></p>
<p>The law of large numbers (LLN) states that as we repeat a random
experiment over and over, the proportion of times that an event occurs
does settle down to a single number. We call this number the
<strong>probability</strong> of that event.</p>
</div>
<p>However, it is not that simple. The LLN requires two key assumptions:</p>
<ol style="list-style-type: decimal">
<li><em>Identical distribution</em>: The outcomes of the random experiment must
have the same probabilities of occurring in each trial. That is, we
can not have in trial 1 a 50% chance of observing an even number,
and then a 80% chance in trial 2. The underlying chance needs to be
the same. This is accomplished by not changing the random experiment
we are studying, the repeated trials must happen in the <em>same
conditions.</em></li>
<li><em>Independence</em>: The outcome of one trial must not affect the
outcomes of other trials.</li>
</ol>
<p>For the die experiment, we can now write that the probability of
observing an even number is 0.5 as follows. First, we need to define the
event of interest, <span class="math inline">\(E = \{2, 4, 6\}\)</span>, and then we can write:
<span class="math display">\[
P(E) = 0.5
\]</span></p>
<p>If you do not give a name to the event, you must specify it inside of
the parentheses. Note the use of round parentheses for probability <span class="math inline">\(P()\)</span>
and the curly brackets to list the outcomes of interest.
<span class="math display">\[
P(\{2, 4, 6\}) = 0.5
\]</span></p>
<p>We reached this definition of the probability of the event <span class="math inline">\(E\)</span>. In the
long run,
<span class="math display">\[
P(E) = \frac{\text{number of times outcome was in the event } E}{\text{total number of trials}}
\]</span></p>
<div class="frame">
<p><strong>NOTATION</strong></p>
<p>We typically use the first few capital letters of the alphabet to name
events. The letter <span class="math inline">\(P\)</span> will always be reserved for probability.</p>
<p>When we write <span class="math inline">\(P(A) = 0.5\)</span> we mean “the probability of the event <span class="math inline">\(A\)</span> is
0.5”.</p>
<p>We use proportions (or decimal numbers) when reporting probability
values in a formal situation like writing a report or a paper. However,
when discussing probability informally, we often use percentages.</p>
</div>
</div>
<div id="law-of-averages-unicorn" class="section level2">
<h2>Law of averages = unicorn</h2>
<p>You might have heard from friends or TV shows that sometimes the random
experiment “owes” you a particular outcome. Let’s try to entangle this in
more detail and understand where the pitfall of this reasoning is.</p>
<p>The law of large numbers tells us that the probability of an event is
the proportion of times we would observe it <strong>in the long run.</strong> The
long run is really long - infinitely long. We, as humans and finite
entities, can not generate an infinitely long sequence of trials and
memorise it.</p>
<p>Many people believe that if you flip a fair coin, where fair means that
the chance of getting heads is the same as the chance of getting tails
(0.5) we expect the coin to “even out” the results in the coming trials
if heads has not appeared in the recent ones.</p>
<p>Say, for example, that in 10 trials you only observed 1 head. This is
quite a low proportion, 0.1 (1 out of 10) compared to the 0.5 (5 out of
10) that the player expected. Does this mean that the coin due to show
heads in the near future, as the coin “owes” us some heads to even out
the proportions?</p>
<p>The answer is <strong>no.</strong></p>
<p>The long run means that the proportions will eventually even out in the
infinite sequence of trials, but you will not know when this happens and
there is absolutely no requirement for the coin to show heads again in
the upcoming trials in order to keep a probability of 0.5.</p>
</div>
<div id="modelling-probability" class="section level2">
<h2>Modelling probability</h2>
<p>To assign a probability value to different events, we should make sure
that these coherence principles are satisfied:</p>
<p><strong>Rule 1: Probability assignment rule</strong></p>
<p>The probability of an impossible event (an event which never occurs) is
0 and the probability of a certain event (an event which always occurs)
is 1.</p>
<p>Hence, we have that <em>the probability is a number between 0 and 1</em>:
<span class="math display">\[\text{for any event }A, \\ 0 \leq P(A) \leq 1\]</span></p>
<p><strong>Rule 2: Total probability rule</strong></p>
<p>If an experiment has a single possible outcome, it is not random as that
outcome will happen with certainty (i.e. probability 1).</p>
<p>When dealing with two or more possible outcomes, we need to be sure to
distribute the entire probability among all of the possible outcomes in
the sample space <span class="math inline">\(S\)</span>.</p>
<p>The sample space must have probability 1: <span class="math display">\[P(S) = 1\]</span></p>
<p>It must be that the will observe one of the outcomes listed within the
collection of all possible outcomes of the experiment.</p>
<p><strong>Rule 3: Complement rule</strong></p>
<p>If the probability of observing the face “2” in a die is 1/6 = 0.17,
what’s the probability of not observing the face “2”? It must be 1 - 1/6
= 5/6 = 0.83.</p>
<p>If <span class="math inline">\(A = \{2\}\)</span>, the event not A is written <span class="math inline">\(\sim A\)</span>, which is a shortcut
for <span class="math inline">\(S\)</span> without <span class="math inline">\(A\)</span>, that is <span class="math inline">\(\{1, 3, 4, 5, 6\}\)</span>.</p>
<p><span class="math display">\[P(\sim A) = 1 - P(A)\]</span></p>
<p><strong>Rule 4: Addition rule for disjoint events</strong></p>
<p>Suppose the probability that a randomly picked person in a town is <span class="math inline">\(A\)</span> =
“a high school student” is <span class="math inline">\(P(A) = 0.3\)</span> and that the probability of
being <span class="math inline">\(B\)</span> = “a university student” is <span class="math inline">\(P(B) = 0.5\)</span>.</p>
<p>What is the probability that a randomly picked person from the town is
<em>either</em> a high school student <em>or</em> a university student? We write the
event “either A or B” as <span class="math inline">\(A \cup B\)</span>, pronounced “A union B”.</p>
<p>If you said 0.8, because it is 0.3 + 0.5, then you just applied the
<em>addition rule</em>:
<span class="math display">\[
\text{If }A \text{ and } B \text{ are mutually exclusive events,}\\
P(A \cup B) = P(A) + P(B)
\]</span></p>
<p><strong>Rule 5: Multiplication rule for independent events</strong></p>
<p>We saw that probability of observing an even number (<span class="math inline">\(E\)</span>) when throwing
a die is 0.5.</p>
<p>You also know that the probability of observing heads (<span class="math inline">\(H\)</span>) when
throwing a fair coin is 0.5.</p>
<p>What’s the probability of observing an even number and heads (that is,
<span class="math inline">\(E\)</span> <em>and</em> <span class="math inline">\(H\)</span>, written <span class="math inline">\(E \cap H\)</span>) when throwing both items together?</p>
<p>The rule simply says that in this case we multiply the two probabilities
together: 0.5 * 0.5 = 0.25.</p>
<p>The <em>multiplication rule for independent events</em> says:
<span class="math display">\[
\text{If }A \text{ and } B \text{ are independent events,}\\
P(A \cap B) = P(A) \times P(B)
\]</span></p>
<div id="probability-in-the-case-of-equally-likely-outcomes" class="section level3">
<h3>Probability in the case of equally likely outcomes</h3>
<p>Consider a sample space of <span class="math inline">\(n\)</span> outcomes</p>
<p><span class="math display">\[
S = \{s_1, s_2, \dots, s_n \}
\]</span></p>
<p>and suppose these are all equally likely, with <span class="math inline">\(p\)</span> denoting the probability of each outcome:
<span class="math display">\[
P(\{s_1\}) = P(\{s_2\}) = \cdots = P(\{s_n\}) = p
\]</span></p>
<p>As the outcomes in the sample space are mutually exclusive events,<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> we can compute the probability of the sample space as</p>
<p><span class="math display">\[
1 = P(S) = P(\{s_1\}) + P(\{s_2\}) + \cdots + P(\{s_n\}) = p + p + \cdots + p = n p
\]</span></p>
<p>which leads to
<span class="math display">\[
p = P(\{s_i\}) = \frac{1}{n}
\]</span></p>
<p>Next, consider an event <span class="math inline">\(A\)</span> comprising a few of the outcomes from <span class="math inline">\(S\)</span></p>
<p><span class="math display">\[
A = \{s_2, s_5, s_9\}
\]</span>
which can be also written as the union of disjoint events</p>
<p><span class="math display">\[
A = \{s_2\} \cup \{s_5\} \cup \{s_9\}
\]</span></p>
<p>We can compute the probability of <span class="math inline">\(A\)</span> as follows</p>
<p><span class="math display">\[
\begin{aligned}
P(A) &amp;= P(\{s_2\}) + P(\{s_5\}) + P(\{s_9\}) \\
&amp;= p + p + p \\
&amp;= 3 p \\
&amp;= 3 \left(\frac{1}{n}\right) \\
&amp;= \frac{3}{n} \\
&amp;= \frac{n_A}{n} \\
&amp;= \frac{\text{number of outcomes within }A}{\text{number of possible outcomes}}
\end{aligned}
\]</span>
where <span class="math inline">\(n_A\)</span> is the number of outcomes within <span class="math inline">\(A\)</span> and <span class="math inline">\(n\)</span> is the total number of possible outcomes in <span class="math inline">\(S\)</span>.</p>
<hr />
</div>
</div>
<div id="glossary" class="section level2">
<h2>Glossary</h2>
<ul>
<li><strong>Random experiment.</strong> A process or phenomenon which can have two
ore more possible outcomes.</li>
<li><strong>Trial.</strong> A single repetition of the experiment</li>
<li><strong>Outcome.</strong> The value observed after running a trial</li>
<li><strong>Sample space.</strong> The collection of all possible outcomes. The
sample space is denoted <span class="math inline">\(S\)</span> and has probability 1.</li>
<li><strong>Event.</strong> Either a single outcome (simple event) or a collection of
outcomes (compound event).</li>
<li><strong>Probability.</strong> A number reporting how likely is an even to occur
when performing a trial (that is, obtaining an outcome within that
event or satisfying the proposition of the event)</li>
<li><strong>Disjoint (or mutually exclusive) events.</strong> Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>
are disjoint if they share no outcomes in common. For disjoint
events, knowing that one event occurs tells us that the other cannot
occur.</li>
<li><strong>Independent events.</strong> Two events are independent if learning that
one event occurs does not change the probability that the other
event occurs.</li>
<li><strong>Probability assignment rule.</strong> Says that the probability of any
event must be between 0 (the probability of an impossible event) and
1 (the probability of a certain event).</li>
<li><strong>Total probability rule.</strong> The probability that the experiment’s
outcome is in the sample space must be 1.</li>
<li><strong>Complement rule.</strong> If <span class="math inline">\(P(A)\)</span> denotes the probability of the event
<span class="math inline">\(A\)</span> occurring, the probability of “not A” is <span class="math inline">\(P(\sim A) = 1 - P(A)\)</span>.</li>
<li><strong>Addition rule for disjoint events.</strong> If <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are disjoint
events, then <span class="math inline">\(P(A \cup B) = P(A) + P(B)\)</span>.</li>
<li><strong>Multiplication rule for independent events.</strong> If A and B are
independent events, then <span class="math inline">\(P(A \cap B) = P(A) \times P(B)\)</span>.</li>
</ul>
<hr />
</div>
<div id="exercises" class="section level2">
<h2>Exercises</h2>
<!--# 1 -->
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p><strong>Sample spaces</strong>. For each of the following experiments list the sample
space and tell whether you think the outcomes are equally likely or not.</p>
<ol style="list-style-type: lower-alpha">
<li>Rolling 2 six-sided dice.</li>
<li>A person has recently travelled back to the UK from abroad and is about to take a COVID-19 test.</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-62" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-62&#39;, &#39;sol-start-62&#39;)"></span>
</div>
<div id="sol-body-62" class="solution-body" style="display: none;">
<ol style="list-style-type: lower-alpha">
<li><p>The sample space is: <span class="math display">\[
S = \left\{
\begin{matrix}
(1,1) &amp; (1,2) &amp; (1,3) &amp; (1,4) &amp; (1,5) &amp; (1,6) \\
(2,1) &amp; (2,2) &amp; (2,3) &amp; (2,4) &amp; (2,5) &amp; (2,6) \\
(3,1) &amp; (3,2) &amp; (3,3) &amp; (3,4) &amp; (3,5) &amp; (3,6) \\
(4,1) &amp; (4,2) &amp; (4,3) &amp; (4,4) &amp; (4,5) &amp; (4,6) \\
(5,1) &amp; (5,2) &amp; (5,3) &amp; (5,4) &amp; (5,5) &amp; (5,6) \\
(6,1) &amp; (6,2) &amp; (6,3) &amp; (6,4) &amp; (6,5) &amp; (6,6)
\end{matrix}
\right\}
\]</span></p>
<p>All of the outcomes are equally likely to occur. Each outcome has a chance of 1/36 of occurring.</p></li>
<li><p>The sample space is <span class="math inline">\(S = \{ \text{Positive}, \text{Negative} \}\)</span>.</p>
<p>The two outcomes are not equally likely. The chance of the test being positive is higher if they have been in contact with anyone positive.</p></li>
</ol>
</div>
<p class="solution-end">
</p>
<!--# 2 -->
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p><strong>Rolling a die.</strong> Consider rolling a six-sided die. Recall that each of
the die’s six faces (1-6) are equally likely to occur, meaning that each
has a <em>long-run probability</em> of 1/6.</p>
<p>Relate the terms <em>trial</em>, <em>outcome</em>, <em>event</em>, and <em>sample space</em> to a
single roll of a die die. Provide an example of each.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-63" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-63&#39;, &#39;sol-start-63&#39;)"></span>
</div>
<div id="sol-body-63" class="solution-body" style="display: none;">
<ul>
<li>A trial a single roll of the die.</li>
<li>An outcome is the face resulting after rolling the die. For example,
when rolling the die, we might observe the face 4.</li>
<li>An event is a collection of one or more faces. For example, we might
be interested in the event “even number”, which can be written
<span class="math inline">\(E = \{2, 4, 6\}\)</span>.</li>
<li>The sample space is the collection of all possible faces of the die.
In this case, the sample space is <span class="math inline">\(S = \{1, 2, 3, 4, 5, 6\}\)</span>.</li>
</ul>
</div>
<p class="solution-end">
</p>
<!--# 3 -->
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Consider again rolling a six-sided die. State whether each of the
following is a simple or a compound event. Next, calculate the
corresponding probability either by directly listing the involved
outcomes or by applying the probability rules (addition rule, complement
rule, multiplication rule).</p>
<ol style="list-style-type: lower-alpha">
<li>Rolling a 6</li>
<li>Rolling a number less than or equal to 3</li>
<li>Rolling a number other than 1</li>
<li>Rolling a 1 or an even number</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-64" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-64&#39;, &#39;sol-start-64&#39;)"></span>
</div>
<div id="sol-body-64" class="solution-body" style="display: none;">
<p>The sample space is <span class="math inline">\(S = \{1, 2, 3, 4, 5, 6\}\)</span>. The number of its
elements is <span class="math inline">\(n = 6\)</span>. Furthermore, as the outcomes are equally likely,
we have that
<span class="math display">\[
P(\{1\}) = P(\{2\}) = \cdots = P(\{6\}) = \frac{1}{6}
\]</span></p>
<ol style="list-style-type: lower-alpha">
<li><p>The simple event “Rolling a 6” can only happen when we observe “6”. Let <span class="math inline">\(A = \{ 6 \}\)</span>. Then,
<span class="math display">\[
P(A) = \frac{n_A}{n} = \frac{1}{6} \approx 0.167
\]</span></p></li>
<li><p>The compound event “Rolling a number <span class="math inline">\(\leq 3\)</span>” can happen when we
observe 1, 2, or 3. Let <span class="math inline">\(B = \{1, 2, 3\}\)</span>. Then,
<span class="math display">\[
P(B) = \frac{n_B}{n} = \frac{3}{6} = \frac{1}{2}.
\]</span></p>
<p>Alternatively, as <span class="math inline">\(B\)</span> is the union of the disjoint events
<span class="math inline">\(\{1\}, \{2\}, \{3\}\)</span>, we can sum the probabilities of each simple
event:
<span class="math display">\[
P(B) = P(\{1\} \cup \{2 \} \cup \{3\}) 
= P(\{1\}) + P(\{2\}) + P(\{3\}) = 3 \times \frac{1}{6} 
= \frac{1}{2}
\]</span></p></li>
<li><p>The compound event “Rolling a number other than 1” can happen when
we observe 2, 3, 4, 5, 6. Let <span class="math inline">\(C = \{2, 3, 4, 5, 6\}\)</span>. Then,
<span class="math display">\[
P(C) = \frac{n_C}{n} = \frac{5}{6} \approx 0.833.
\]</span></p>
<p>Alternatively, as <span class="math inline">\(C\)</span> is equivalent to <span class="math inline">\(\sim \{1\}\)</span> (read “not
{1}”), we can use the complement rule:
<span class="math display">\[
P(\sim \{1\}) = 1 - P(\{1\}) = 1 - \frac{1}{6} 
= \frac{5}{6} \approx 0.833.
\]</span></p></li>
<li><p>The compound event “Rolling a 1 or an even number” can happen when
we observe 1, 2, 4, 6. Let <span class="math inline">\(D = \{1, 2, 4, 6\}\)</span>. Then,
<span class="math display">\[
P(D) = \frac{n_D}{n} = \frac{4}{6} \approx 0.667
\]</span></p>
<p>Alternatively, <span class="math inline">\(D\)</span> can be written as the union of four disjoint
simple events <span class="math display">\[
\begin{aligned}
P(D) &amp;= P(\{1\} \cup \{2\} \cup \{4 \} \cup \{6\}) \\
&amp;= P(\{1\}) + P(\{2\}) + P(\{4 \}) + P(\{6\}) \\
&amp;= 4 \times \frac{1}{6} \\
&amp;= \frac{4}{6} \\
&amp;\approx 0.667
\end{aligned}
\]</span></p></li>
</ol>
</div>
<p class="solution-end">
</p>
<!--# 4 -->
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p><strong>Playing cards.</strong> Consider a standard deck of 52 playing cards. These
are shown in the diagram below:</p>
<div class="figure" style="text-align: center"><span id="fig:cards-deck"></span>
<img src="images/prob/card-deck.png" alt="Example set of 52 playing cards; 13 of each suit clubs, diamonds, hearts, and spades. Source: Wikipedia (https://en.wikipedia.org/wiki/Standard_52-card_deck)" width="808" />
<p class="caption">
Figure 1: Example set of 52 playing cards; 13 of each suit clubs, diamonds, hearts, and spades. Source: Wikipedia (<a href="https://en.wikipedia.org/wiki/Standard_52-card_deck" class="uri">https://en.wikipedia.org/wiki/Standard_52-card_deck</a>)
</p>
</div>
<p>Relate the terms <em>trial</em>, <em>outcome</em>, <em>event</em>, and <em>sample space</em> to a
single draw from a standard deck of cards. Provide an example of each.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-65" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-65&#39;, &#39;sol-start-65&#39;)"></span>
</div>
<div id="sol-body-65" class="solution-body" style="display: none;">
<ul>
<li>A trial represents a single draw of a card from the deck of 52 playing cards.</li>
<li>The outcome is the result of a draw. For example, drawing a card from
the deck might result in the 5 of Hearts.</li>
<li>Events are combinations of one or more cards. For example, we might be interested in whether the event “drawing a red card” occurs. This event can be written <span class="math inline">\(R\)</span> = {AceDiamonds, 2Diamonds, …, KingDiamonds, AceHearts, 2Hearts, …, KingHearts}. We say the event occurred if the result of a trial is a card within that collection.</li>
<li>The sample space is the collection of all possible cards that can be drawn from the deck. In our case, the 52 cards shown in Figure <a href="#fig:cards-deck">1</a>.</li>
</ul>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="optional-begin">
Data: TipJoke.csv. Click the plus to expand →<span id="opt-start-66" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-66&#39;, &#39;opt-start-66&#39;)"></span>
</div>
<div id="opt-body-66" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/TipJoke.csv">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>A <a href="https://doi.org/10.1111/j.1559-1816.2002.tb00266.x">study</a> published
in the Journal of Applied Social Psychology<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>
investigated if telling a joke affected whether or not a customer let a tip.</p>
<p>The waiter at a coffee bar of a famous seaside resort on the west Atlantic coast of France randomly assigned coffee-ordering customers to one of three
groups.</p>
<p>When receiving the bill, one group also received a card telling a joke,
another group received a card containing an advertisement for a local
restaurant, and a third group received no card at all.</p>
<p>The dataset contains the variables:</p>
<ul>
<li><code>Card</code>: None, Joke, Ad.</li>
<li><code>Tip</code>: 1 = The customer left a tip, 0 = The customer did not leave
tip.</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Card
</th>
<th style="text-align:center;">
Tip
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
Joke
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
Ad
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
0
</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
<!--# 5 -->
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Load the TipJoke.csv data into R and call it <code>tipjoke</code>.</p>
<p>Recode the Tip variable so that</p>
<ul>
<li>1 becomes “Tipped”</li>
<li>0 becomes “Not tipped”</li>
</ul>
<p>Make sure that categorical variables are correctly encoded as factors.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-67" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-67&#39;, &#39;sol-start-67&#39;)"></span>
</div>
<div id="sol-body-67" class="solution-body" style="display: none;">
<p>Load the data into R:</p>
<pre class="r"><code>tipjoke &lt;- read_csv(&#39;https://uoepsy.github.io/data/TipJoke.csv&#39;)</code></pre>
<p>Check if the data were read into R correctly by examining the top 6
rows:</p>
<pre class="r"><code>head(tipjoke)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   Card    Tip
##   &lt;chr&gt; &lt;dbl&gt;
## 1 None      1
## 2 Joke      1
## 3 Ad        0
## 4 None      0
## 5 None      1
## 6 None      0</code></pre>
<p>Recode the Tip variable:</p>
<pre class="r"><code>tipjoke &lt;- tipjoke %&gt;%
  mutate(Tip = ifelse(Tip == 1, &#39;Tipped&#39;, &#39;Not tipped&#39;))

head(tipjoke)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   Card  Tip       
##   &lt;chr&gt; &lt;chr&gt;     
## 1 None  Tipped    
## 2 Joke  Tipped    
## 3 Ad    Not tipped
## 4 None  Not tipped
## 5 None  Tipped    
## 6 None  Not tipped</code></pre>
<div class="frame">
<p><strong>What is ifelse?</strong></p>
<p>The function ifelse works as follows: <code>ifelse(test, value_when_true, value_when_false)</code>.</p>
<p><code>test</code> is any condition on a vector. For example, if <code>x &lt;- c(2, 4, 6, 9)</code>, test could be <code>x &lt; 6</code>. This will return <code>c(TRUE, TRUE, FALSE, FALSE)</code>.
The TRUEs will be replaced with the value specified in <code>value_when_true</code>, and the FALSEs will be replaced with the value specified in <code>value_when_false</code>.</p>
<p>Other possible tests are <code>x &gt; 6</code>, <code>x == 6</code>, <code>x &lt;= 6</code>, <code>x &gt;= 6</code>, and so on…</p>
</div>
<p>Both variables represent categorical variables and so should be encoded
as factors (<code>&lt;fct&gt;</code>).</p>
<p>There are many different equivalent ways to do so, see below.</p>
<p><strong>Option 1.</strong></p>
<pre class="r"><code>tipjoke &lt;- tipjoke %&gt;% 
  mutate(
    Card = as.factor(Card),
    Tip = as.factor(Tip)
  )

head(tipjoke)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   Card  Tip       
##   &lt;fct&gt; &lt;fct&gt;     
## 1 None  Tipped    
## 2 Joke  Tipped    
## 3 Ad    Not tipped
## 4 None  Not tipped
## 5 None  Tipped    
## 6 None  Not tipped</code></pre>
<p><strong>Option 2.</strong></p>
<pre class="r"><code>tipjoke$Card &lt;- as.factor(tipjoke$Card)
tipjoke$Tip  &lt;- as.factor(tipjoke$Tip)</code></pre>
<p><strong>Option 3. (Advanced)</strong></p>
<pre class="r"><code>tipjoke &lt;- tipjoke %&gt;%
    mutate(across(c(Card, Tip), as.factor))</code></pre>
<p><strong>Option 4. (Advanced)</strong></p>
<pre class="r"><code>tipjoke &lt;- tipjoke %&gt;%
    mutate(across(everything(), as.factor))</code></pre>
</div>
<p class="solution-end">
</p>
<!-- # 6 -->
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Define the sample space for the card tipping experiment.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-68" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-68&#39;, &#39;sol-start-68&#39;)"></span>
</div>
<div id="sol-body-68" class="solution-body" style="display: none;">
<p>The set of possible outcomes is
<span class="math display">\[
S = \left\{
\begin{matrix}
(None,\ Tipped) &amp; (None,\ Not\ Tipped) \\
(Joke,\ Tipped) &amp; (Joke,\ Not\ Tipped) \\
(Ad,\ Tipped) &amp; (Ad,\ Not\ Tipped) \\
\end{matrix}
\right\}
\]</span></p>
</div>
<p class="solution-end">
</p>
<!-- # 7 -->
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Create a contingency table displaying how many customers
who were given no card, a a joke card, or an advertisement card left a
tip or not.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-69" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-69&#39;, &#39;sol-start-69&#39;)"></span>
</div>
<div id="sol-body-69" class="solution-body" style="display: none;">
<p>Create a table of counts:</p>
<pre class="r"><code>freq_tbl &lt;- tipjoke %&gt;%
    table()
freq_tbl</code></pre>
<pre><code>##       Tip
## Card   Not tipped Tipped
##   Ad           60     14
##   Joke         42     30
##   None         49     16</code></pre>
</div>
<p class="solution-end">
</p>
<!-- # 8 -->
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Transform the table of counts to a relative frequency table.</p>
<p>Do the numbers in the table satisfy the requirements of probabilities?</p>
<p>Display the relative frequency table as a mosaic plot and comment on
what it highlights.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-70" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-70&#39;, &#39;sol-start-70&#39;)"></span>
</div>
<div id="sol-body-70" class="solution-body" style="display: none;">
<p>Convert it to a table of proportions:</p>
<pre class="r"><code>rel_freq_tbl &lt;- freq_tbl %&gt;%
    prop.table()
rel_freq_tbl</code></pre>
<pre><code>##       Tip
## Card   Not tipped     Tipped
##   Ad   0.28436019 0.06635071
##   Joke 0.19905213 0.14218009
##   None 0.23222749 0.07582938</code></pre>
<p>All values in the proportions table are greater than or equal 0:</p>
<pre class="r"><code>all(rel_freq_tbl &gt;= 0)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>All values in the proportions table are less than or equal 1:</p>
<pre class="r"><code>all(rel_freq_tbl &lt;= 1)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>The values in the relative frequency table sum to 1, which is the probability of the sample space:</p>
<pre class="r"><code>sum(rel_freq_tbl)</code></pre>
<pre><code>## [1] 1</code></pre>
<p>Visualise the relative frequency table as a mosaic plot:</p>
<pre class="r"><code>plot(rel_freq_tbl)</code></pre>
<p><img src="07_probability_basics_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>The mosaic plot shows that roughly the same number of customers were
given no card, an ad card or a joke card. Those who were given a joke
card had the highest number of tips. The number of tipping customers
doesn’t seem to differ too much between those who were given no card or
an advertisement card.</p>
</div>
<p class="solution-end">
</p>
<!--# 9 -->
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>The proportions computed above can be considered as the probabilities for a person randomly drawn from the participants in the experiment.</p>
<p>Using the proportions table compute above,</p>
<ol style="list-style-type: decimal">
<li>What’s the probability that a randomly chosen customer isn’t given a
card and doesn’t tip?</li>
<li>What’s the probability that a randomly chosen customer is given an
advertisement card and tips?</li>
<li>What’s the probability that a randomly chosen customer is given a
joke card and tips?</li>
<li>What’s the probability that a randomly chosen customer is given some
card and tips?</li>
<li>What’s the probability that a randomly chosen customer is given some
card?</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-71" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-71&#39;, &#39;sol-start-71&#39;)"></span>
</div>
<div id="sol-body-71" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>P(no card and doesn’t tip) = 0.232</li>
<li>P(ad card and tips) = 0.0664</li>
<li>P(joke cards and tips) = 0.142</li>
<li>P(ad card and tips) + P(joke card and tips) = 0.06635071 + 0.14218009 = 0.209</li>
<li>1 - (P(none and doesn’t tip) + P(none and tips)) = 1 - (0.23222749 + 0.07582938) = 0.692</li>
</ol>
</div>
<p class="solution-end">
</p>
<p><br></p>
<p>Can telling a joke affect whether or not a waiter in a coffee bar
receives a tip from a customer?</p>
<p>To be continued next week…</p>
<!--# Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>In the die example, 1 has nothing in common with 2, 2 has nothing in common with 3, and so on.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Gueaguen, N. (2002). The Effects of a Joke on
Tipping When It Is Delivered at the Same Time as the Bill. <em>Journal
of Applied Social Psychology, 32</em>(9), 1955-1963.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
