<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Probability rules!</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR1</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li>
  <a href="intro_r_rstudio_year1.html">DAPR1 starts here</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to data and R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_data_types.html">1/1: Collecting data</a>
    </li>
    <li>
      <a href="02_categorical.html">1/2: Categorical data</a>
    </li>
    <li>
      <a href="03_numerical.html">1/3: Numerical data</a>
    </li>
    <li>
      <a href="04_relationships.html">1/4: Relationships</a>
    </li>
    <li>
      <a href="05_functions.html">1/5: Types of relations</a>
    </li>
    <li class="dropdown-header">1/6: Break week!</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Probability &amp; sampling
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_probability_basics.html">1/7: Probability basics</a>
    </li>
    <li>
      <a href="08_probability_rules.html">1/8: Probability rules!</a>
    </li>
    <li>
      <a href="09_discrete_distributions.html">1/9: Discrete random variables</a>
    </li>
    <li>
      <a href="10_continuous_distributions.html">1/10: Continuous random variables</a>
    </li>
    <li>
      <a href="11_sampling_distributions.html">1/11: Sampling distributions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Hypothesis testing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="12_bootstrap_cis.html">2/1: Bootstrap &amp; CIs</a>
    </li>
    <li>
      <a href="13_hypothesis_testing.html">2/2: Hypothesis testing: p-values</a>
    </li>
    <li>
      <a href="14_critical_values.html">2/3: Hypothesis testing: critical values</a>
    </li>
    <li>
      <a href="15_connecting_ci_ht.html">2/4: Hypothesis testing &amp; CIs</a>
    </li>
    <li>
      <a href="16_ht_errors.html">2/5: Making decisions</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Basic tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="17_one_sample_mean.html">2/7: Test for one mean</a>
    </li>
    <li>
      <a href="18_two_sample_means.html">2/8: Test for two means</a>
    </li>
    <li>
      <a href="19_paired_t_test.html">2/9: Test for paired samples</a>
    </li>
    <li>
      <a href="20_chi_square.html">2/10: Chi-square</a>
    </li>
    <li>
      <a href="21_covcor.html">2/11: Covariance and correlation</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Probability rules!</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand the use of probability rules</li>
<li>Understand the basics of and how to use Bayes’s equation</li>
<li>Understand use of probability to test independence</li>
</ol>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In this week’s exercises you will learn to apply the probability rules to compute the probability of <em>any</em> event, not just mutually exclusive or independent ones.</p>
<p>You will apply the rules of conditional probability to finish answering last week’s research question: “Can telling a joke affect whether or not a waiter in a coffee bar receives a tip from a customer?”</p>
</div>
<div id="recap" class="section level1">
<h1>Recap</h1>
<p>Let’s recap the probability rules discussed last week.</p>
<p><strong>Rule 1: Probability assignment rule</strong></p>
<p>The probability of an impossible event (an event which never occurs) is
0 and the probability of a certain event (an event which always occurs)
is 1.</p>
<p>Hence, we have that <em>the probability is a number between 0 and 1</em>:
<span class="math display">\[\text{for any event }A, \\ 0 \leq P(A) \leq 1\]</span></p>
<p><strong>Rule 2: Total probability rule</strong></p>
<p>If an experiment has a single possible outcome, it is not random as that
outcome will happen with certainty (i.e. probability 1).</p>
<p>When dealing with two or more possible outcomes, we need to be sure to
distribute the entire probability among all of the possible outcomes in
the sample space <span class="math inline">\(S\)</span>.</p>
<p>The sample space must have probability 1: <span class="math display">\[P(S) = 1\]</span></p>
<p>It must be that the will observe one of the outcomes listed within the
collection of all possible outcomes of the experiment.</p>
<p><strong>Rule 3: Complement rule</strong></p>
<p>If the probability of observing the face “2” in a die is 1/6 = 0.17,
what’s the probability of not observing the face “2”? It must be 1 - 1/6
= 5/6 = 0.83.</p>
<p>If <span class="math inline">\(A = \{2\}\)</span>, the event not A is written <span class="math inline">\(\sim A\)</span>, which is a shortcut
for <span class="math inline">\(S\)</span> without <span class="math inline">\(A\)</span>, that is <span class="math inline">\(\{1, 3, 4, 5, 6\}\)</span>.</p>
<p><span class="math display">\[P(\sim A) = 1 - P(A)\]</span></p>
<p><strong>Rule 4: Addition rule for disjoint events</strong></p>
<p>Suppose the probability that a randomly picked person in a town is <span class="math inline">\(A\)</span> =
“a high school student” is <span class="math inline">\(P(A) = 0.3\)</span> and that the probability of
being <span class="math inline">\(B\)</span> = “a university student” is <span class="math inline">\(P(B) = 0.5\)</span>.</p>
<p>What is the probability that a randomly picked person from the town is
<em>either</em> a high school student <em>or</em> a university student? We write the
event “either A or B” as <span class="math inline">\(A \cup B\)</span>, pronounced “A union B”.</p>
<p>If you said 0.8, because it is 0.3 + 0.5, then you just applied the
<em>addition rule</em>:
<span class="math display">\[
\text{If }A \text{ and } B \text{ are mutually exclusive events,}\\
P(A \cup B) = P(A) + P(B)
\]</span></p>
<p><strong>Rule 5: Multiplication rule for independent events</strong></p>
<p>We saw that probability of observing an even number (<span class="math inline">\(E\)</span>) when throwing
a die is 0.5.</p>
<p>You also know that the probability of observing heads (<span class="math inline">\(H\)</span>) when
throwing a fair coin is 0.5.</p>
<p>What’s the probability of observing an even number and heads (that is,
<span class="math inline">\(E\)</span> <em>and</em> <span class="math inline">\(H\)</span>, written <span class="math inline">\(E \cap H\)</span>) when throwing both items together?</p>
<p>The rule simply says that in this case we multiply the two probabilities
together: 0.5 * 0.5 = 0.25.</p>
<p>The <em>multiplication rule for independent events</em> says:
<span class="math display">\[
\text{If }A \text{ and } B \text{ are independent events,}\\
P(A \cap B) = P(A) \times P(B)
\]</span></p>
</div>
<div id="general-addition-rule" class="section level1">
<h1>General addition rule</h1>
<p>Consider throwing a six-sided die, for which we already know that the sample space is <span class="math inline">\(S = \{1, 2, 3, 4, 5, 6\}\)</span>.
What’s the probability of observing an odd number <em>or</em> a number which is less than 4?</p>
<p>The relevant events are:</p>
<ul>
<li><span class="math inline">\(A = \text{result is odd} = \{1, 3, 5\}\)</span></li>
<li><span class="math inline">\(B = \text{result is less than four} = \{1, 2, 3\}\)</span></li>
</ul>
<p>and we know that:</p>
<ul>
<li><span class="math inline">\(P(A) = 3/6 = 0.5\)</span></li>
<li><span class="math inline">\(P(B) = 3/6 = 0.5\)</span></li>
</ul>
<p>However, the probability of <span class="math inline">\(A\)</span> <em>or</em> <span class="math inline">\(B\)</span>, written <span class="math inline">\(P(A \cup B)\)</span>, is not simply <span class="math inline">\(P(A) + P(B)\)</span>, because the events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are not disjoint; they overlap.
The outcomes 1 and 3 play a crucial role here as they are both odd and are less than four, i.e. they are in both sets. They are both in <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, which places them in the intersection of the two circles.</p>
<p>The diagram below represents the sample space as <span class="math inline">\(S\)</span>. Notice that the outcomes 4 and 6 are neither odd nor less than four, so they sit outside both circles.</p>
<p><img src="images/prob/venn_die.png" width="70%" style="display: block; margin: auto;" /></p>
<p>The reason we can’t simply add the probabilities of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> is that we would count the outcomes 1 and 3 twice.
If we did add the two probabilities, we could compensate by subtracting the probability of the outcomes 1 and 3.</p>
<p><span class="math display">\[
\begin{aligned}
P(\text{odd or less than 4}) &amp;= P(\text{odd}) + P(\text{less than 4}) - P(\text{odd and less than 4}) \\
&amp;= P(\{1, 3, 5\}) + P(\{1, 2, 3\}) - P(\{1, 3\}) \\
&amp;= 3/6 + 3/6 - 2/6 \\
&amp;= 0.667
\end{aligned}
\]</span></p>
<p>This is true in general and is called the <strong>general addition rule</strong>, which does not require disjoint events. Consider two generic events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> such that</p>
<p><img src="images/prob/venn_gen_add.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Then, the probability of observing <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> is:
<span class="math display">\[
P(A \cup B) = P(A) + P(B) - P(A \cap B)
\]</span></p>
<p>Intuitively, <span class="math inline">\(P(A) + P(B)\)</span> counts <span class="math inline">\(A \cap B\)</span> twice, so we have to subtract <span class="math inline">\(P(A \cap B)\)</span> to make the net number of times <span class="math inline">\(A \cap B\)</span> is counted equal to 1.</p>
<p>When the two events have no outcomes in common, i.e. <span class="math inline">\(P(A \cap B) = 0\)</span> as the two events can’t happen together, the general addition rule reduces to the addition rule for disjoint events.</p>
<p><br></p>
<div class="frame">
<p><strong>TERMINOLOGY</strong></p>
<center>
<em>Would you like fruit or dessert?</em>
</center>
<p><br></p>
<p>Everyday language can be ambiguous. It’s not clear if by answering “yes” to the question above our choice is only one of the two options, or we can actually have both.</p>
<p>Typically, everyday language uses “or” meaning the exclusive version. That is, you can have one or the other, but not both. In other words, you can have fruit or dessert, but not both.</p>
<p>When talking about probability, being imprecise and ambiguous can get us into trouble. For this reason, we will here define once for all what we mean by “or” in a mathematical sense.</p>
<p>In statistics, when we say “or” we always mean the inclusive version.
In other words, the probability of <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> means the probability of either <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> or both.</p>
</div>
<p><br></p>
<p>Let’s consider another example. Suppose that 25% of people have an electric scooter, 29% of people have a bike, and 12% of people own both. What is the probability that someone owns an electric scooter or a bike?</p>
<p>This question concerns the following two events</p>
<ul>
<li><span class="math inline">\(A = \text{owning an electric scooter}\)</span></li>
<li><span class="math inline">\(B = \text{owning a bike}\)</span></li>
</ul>
<p>and we are told that</p>
<ul>
<li><span class="math inline">\(P(A) = 0.25\)</span></li>
<li><span class="math inline">\(P(B) = 0.29\)</span></li>
<li><span class="math inline">\(P(A \cap B) = 0.12\)</span></li>
</ul>
<p>Clearly, <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are not mutually exclusive (or disjoint) events. Having a scooter doesn’t exclude owning a bike, and vice versa.
In fact, the problem statements tells us exactly the percentage of people having <strong>both</strong> an electric scooter and a bike, 12%.</p>
<p>So… how do we calculate the probability of owning an electric scooter or a bike?</p>
<p>If we simply did <span class="math inline">\(P(A) + P(B)\)</span>, we would count twice those having both a scooter and a bike.
Hence, we need to subtract <span class="math inline">\(P(A \cap B)\)</span>:
<span class="math display">\[
\begin{aligned}
P(A \cup B) &amp;= P(A) + P(B) - P(A \cap B) \\
&amp;= 0.25 + 0.29 - 0.12 \\
&amp;= 0.42
\end{aligned}
\]</span></p>
</div>
<div id="conditional-probability" class="section level1">
<h1>Conditional probability</h1>
<p>The following <em>contingency table</em> displays the counts of passengers who did or did not survive the Titanic sinking by travelling class.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Survived
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;">
Class
</th>
<th style="text-align:right;">
No
</th>
<th style="text-align:right;">
Yes
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1st
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
203
</td>
<td style="text-align:right;">
325
</td>
</tr>
<tr>
<td style="text-align:left;">
2nd
</td>
<td style="text-align:right;">
167
</td>
<td style="text-align:right;">
118
</td>
<td style="text-align:right;">
285
</td>
</tr>
<tr>
<td style="text-align:left;">
3rd
</td>
<td style="text-align:right;">
528
</td>
<td style="text-align:right;">
178
</td>
<td style="text-align:right;">
706
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
817
</td>
<td style="text-align:right;">
499
</td>
<td style="text-align:right;">
1316
</td>
</tr>
</tbody>
</table>
<p>You already encountered contingency tables when studying the relationship between two categorical variables in <a href="https://uoepsy.github.io/dapr1/labs/04_relationships.html#categorical-and-categorical">week 4</a>.</p>
<p>If you divide the frequency table by the total number of passengers, 1316, you obtain a table of relative frequencies.
It is just a small step from these relative frequencies to probabilities.</p>
<p>Let;s focus on the Titanic survival study and make the sample space just the set of these 1316 passengers. If we select a passenger at random from this study, the probability we select a first class passenger is just the corresponding relative frequency (since we are equally likely to select any of the 1316 passengers).
There are 325 first class passengers in the data out of a total of 1316, giving a probability of
<span class="math display">\[
P( \text{1st} ) = \frac{325}{1316} = 0.247
\]</span>
The same method works for more complicated events like intersections. For example, what’s the probability of selecting a 1st class passenger who survived? Well, 203 first class passengers survived, so the probability is
<span class="math display">\[
P( \text{1st} \cap \text{survived} ) = \frac{203}{1316} = 0.154 
\]</span></p>
<p>The probability of selecting a passenger who survived is
<span class="math display">\[
P( \text{survived} ) = \frac{499}{1316} = 0.379
\]</span>
What if we are given the information that the selected passenger was in first class? Would that change the probability that the selected passenger survived? You bet it would!</p>
<p>When we restrict our focus to first class passengers, we look only at the row of the table where “Class” is “1st”.
Of the 325 first class passengers, only 203 of them said survived.
We write the probability that a selected passenger survived given that we have selected a first class passenger as
<span class="math display">\[
P(\text{survived} \mid \text{1st}) = \frac{203}{325} = 0.625
\]</span></p>
<p>Now, imagine dividing numerator and denominator by the total, 1316:
<span class="math display">\[
\begin{aligned}
P(\text{survived} \mid \text{1st}) 
= \frac{203 / 1316}{325 / 1316}
= \frac{P(\text{1st} \cap \text{survived})}{P(\text{1st})}
\end{aligned}
\]</span></p>
<p>A probability that takes into account a given <em>condition</em>, such as being a first class passenger, is called a <em>conditional probability.</em>
For generic events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, we write the conditional probability as <span class="math inline">\(P(B | A)\)</span> and pronounce it “the probability of <span class="math inline">\(B\)</span> given <span class="math inline">\(A\)</span>”.</p>
<p>Suppose we are told that the event <span class="math inline">\(A\)</span> with <span class="math inline">\(P(A) &gt; 0\)</span> occurs. The <strong>conditional probability</strong> of <span class="math inline">\(B\)</span> given <span class="math inline">\(A\)</span> is given by:
<span class="math display">\[
P(B | A) = \frac{P(A \cap B)}{P(A)}
\]</span>
Intuitively, we need to divide the formula by <span class="math inline">\(P(A)\)</span> to make sure that <span class="math inline">\(P(A|A) = 1\)</span>.</p>
<p>The formula wouldn’t work if <span class="math inline">\(P(A) = 0\)</span>, but this makes sense as <span class="math inline">\(A\)</span> we couldn’t be told that <span class="math inline">\(A\)</span> occurred if it was an impossible event!</p>
<div class="yellow">
<p><strong>NOTE</strong></p>
<p>The conditional probability <span class="math inline">\(P(\text{some event} | A)\)</span> satisfies the standard rules of probability. You can think of it as the same as <span class="math inline">\(P(\text{some event})\)</span> but after having replaced the sample space from <span class="math inline">\(S\)</span> to <span class="math inline">\(A\)</span>, which is the event that we have been told happened. As the event happened, we know that the new sample space is now <span class="math inline">\(A\)</span>, so that <span class="math inline">\(P(A) = 1\)</span>.</p>
<p>For example, according to the complement rule, <span class="math inline">\(P({}\sim B|A) = 1 - P(B|A)\)</span>.</p>
</div>
<p>Consider the following plot:</p>
<p><img src="08_probability_rules_files/figure-html/unnamed-chunk-5-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>On the y-axis we see the conditional probabilities of survival given the passenger class.
That is <span class="math inline">\(P(\text{survived} | \text{1st}) = 0.62\)</span>, <span class="math inline">\(P(\text{survived} | \text{2nd}) = 0.41\)</span>, and <span class="math inline">\(P(\text{survived} | \text{3rd}) = 0.25\)</span>.</p>
<p>The x-axis displays the probability of a randomly selected passenger to be in each travelling class. For example, <span class="math inline">\(P(\text{1st}) = 0.25\)</span>, <span class="math inline">\(P(\text{2nd}) = (0.46 - 0.25) = 0.21\)</span>, and <span class="math inline">\(P(\text{3rd}) = 1 - (P(\text{1st}) + P(\text{2nd})) = 1 - 0.25 - 0.21 = 1 - 0.46 = 0.54\)</span></p>
</div>
<div id="general-multiplication-rule" class="section level1">
<h1>General multiplication rule</h1>
<p>Consider two generic events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>. Before, we saw that
<span class="math display">\[
P(B | A) = \frac{P(A \cap B)}{P(A)}
\]</span></p>
<p>Rearranging the conditional probability formula we obtain the <strong>general multiplication rule</strong>:
<span class="math display">\[
P(A \cap B) = P(A) P(B|A)
\]</span></p>
<p>If you were to start from <span class="math inline">\(P(A | B)\)</span> you would reach to the equivalent version:
<span class="math display">\[
P(A \cap B) = P(B) P(A|B)
\]</span></p>
</div>
<div id="independence" class="section level1">
<h1>Independence</h1>
<p>We say that two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent, if knowing that one occurred doesn’t change the probability of the other occurring:</p>
<p><span class="math display">\[
P(B|A) = P(B)
\]</span></p>
<p>From this we have that</p>
<p><span class="math display">\[
P(B) = P(B|A) = \frac{P(A \cap B)}{P(A)}
\]</span></p>
<p>Leading to</p>
<p><span class="math display">\[
P(A \cap B) = P(A) P(B)
\]</span>
At the same time,</p>
<p><span class="math display">\[
P(A|B) = \frac{P(A \cap B)}{P(B)} = \frac{P(A) P(B)}{P(B)} = P(A)
\]</span></p>
<p>So, we have three <strong>equivalent</strong> definitions of independent events! If one holds, the remaining ones hold as well. Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if and only if
<span class="math display">\[
\begin{aligned}
P(A | B) &amp;= P(A) \\
P(B | A) &amp;= P(B) \\
P(A \cap B) &amp;= P(A) P(B)
\end{aligned}
\]</span></p>
<p><strong>In pictures:</strong></p>
<p>Independence happens when the probability of “Survived = Yes” is the same regardless of whether the passenger was in 1st, 2nd, or 3rd class.</p>
<p><img src="08_probability_rules_files/figure-html/unnamed-chunk-6-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Perfect dependence happens when knowing the passenger class leads to a perfect prediction of whether a passenger survived or not.</p>
<p><img src="08_probability_rules_files/figure-html/unnamed-chunk-7-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Note that, for independent events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> such that <span class="math inline">\(P(B | A) = P(B)\)</span>, the general multiplication rule reduces to the multiplication rule for independent events:
<span class="math display">\[
P(A \cap B) = P(B|A)P(A) = P(B) P(A)
\]</span></p>
</div>
<div id="bayes-rule-reversing-the-conditioning" class="section level1">
<h1>Bayes’ rule: reversing the conditioning</h1>
<p>Suppose we have <span class="math inline">\(P(A | B)\)</span> but we are interested in <span class="math inline">\(P(B | A)\)</span>. That is, we want to reverse the conditioning.</p>
<p>By applying the rule for conditional probability and the general multiplication rule, we have that:
<span class="math display">\[
P(B | A) = \frac{P(A \cap B)}{P(A)} = \frac{P(A|B)P(B)}{P(A)}
\]</span></p>
<hr />
</div>
<div id="glossary" class="section level1">
<h1>Glossary</h1>
<ul>
<li><strong>General addition rule</strong>. For any events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, <span class="math inline">\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\)</span>.</li>
<li><strong>General multiplication rule</strong>. For any events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, <span class="math inline">\(P(A \cap B) = P(B|A)P(A) = P(A | B) P(B)\)</span>.</li>
<li><strong>Independent events</strong>. Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if and only if <span class="math inline">\(P(A \cap B) = P(A) P(B)\)</span></li>
<li><strong>Bayes’ rule</strong>. <span class="math inline">\(P(B | A) = \frac{P(A | B)P(B)}{P(A)}\)</span></li>
</ul>
<hr />
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<div class="optional-begin">
Data: TipJoke.csv. Click the plus to expand →<span id="opt-start-72" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-72&#39;, &#39;opt-start-72&#39;)"></span>
</div>
<div id="opt-body-72" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/TipJoke.csv">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>A <a href="https://doi.org/10.1111/j.1559-1816.2002.tb00266.x">study</a> published
in the Journal of Applied Social Psychology<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
investigated if telling a joke affected whether or not a customer let a tip.</p>
<p>The waiter at a coffee bar of a famous seaside resort on the west Atlantic coast of France randomly assigned coffee-ordering customers to one of three
groups.</p>
<p>When receiving the bill, one group also received a card telling a joke,
another group received a card containing an advertisement for a local
restaurant, and a third group received no card at all.</p>
<p>The dataset contains the variables:</p>
<ul>
<li><code>Card</code>: None, Joke, Ad.</li>
<li><code>Tip</code>: 1 = The customer left a tip, 0 = The customer did not leave
tip.</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Card
</th>
<th style="text-align:center;">
Tip
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
Joke
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
Ad
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
None
</td>
<td style="text-align:center;">
0
</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
<!-- 1 -->
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Load the TipJoke.csv data into R and call it <code>tipjoke</code>.</p>
<p>Recode the Tip variable so that</p>
<ul>
<li>1 becomes “Tipped”</li>
<li>0 becomes “Not tipped”</li>
</ul>
<p>Create a relative frequency table displaying how many customers who did or did not tip were given a joke card, an advertisement card, or no card.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-73" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-73&#39;, &#39;sol-start-73&#39;)"></span>
</div>
<div id="sol-body-73" class="solution-body" style="display: none;">
<p>Load the data into R:</p>
<pre class="r"><code>library(tidyverse)

tipjoke &lt;- read_csv(&#39;https://uoepsy.github.io/data/TipJoke.csv&#39;)</code></pre>
<p>Check if the data were read into R correctly by examining the top 6
rows:</p>
<pre class="r"><code>head(tipjoke)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   Card    Tip
##   &lt;chr&gt; &lt;dbl&gt;
## 1 None      1
## 2 Joke      1
## 3 Ad        0
## 4 None      0
## 5 None      1
## 6 None      0</code></pre>
<p>Both variables represent categorical variables and so should be encoded
as factors (<code>&lt;fct&gt;</code>).</p>
<pre class="r"><code>tipjoke$Card &lt;- as.factor(tipjoke$Card)
tipjoke$Tip  &lt;- as.factor(tipjoke$Tip)

head(tipjoke)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   Card  Tip  
##   &lt;fct&gt; &lt;fct&gt;
## 1 None  1    
## 2 Joke  1    
## 3 Ad    0    
## 4 None  0    
## 5 None  1    
## 6 None  0</code></pre>
<p>Recode the levels of the Tip variable:</p>
<pre class="r"><code>tipjoke &lt;- tipjoke %&gt;%
  mutate(
    Tip = fct_recode(Tip, &#39;Tipped&#39; = &#39;1&#39;, &#39;Not tipped&#39; = &#39;0&#39;)
  )

head(tipjoke)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   Card  Tip       
##   &lt;fct&gt; &lt;fct&gt;     
## 1 None  Tipped    
## 2 Joke  Tipped    
## 3 Ad    Not tipped
## 4 None  Not tipped
## 5 None  Tipped    
## 6 None  Not tipped</code></pre>
<p>The relative frequency table is:</p>
<pre class="r"><code>rel_freq &lt;- tipjoke %&gt;%
  table() %&gt;%
  prop.table() %&gt;%
  addmargins()

rel_freq</code></pre>
<pre><code>##       Tip
## Card   Not tipped     Tipped        Sum
##   Ad   0.28436019 0.06635071 0.35071090
##   Joke 0.19905213 0.14218009 0.34123223
##   None 0.23222749 0.07582938 0.30805687
##   Sum  0.71563981 0.28436019 1.00000000</code></pre>
</div>
<p class="solution-end">
</p>
<!-- 2 -->
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Consider the 211 coffee-ordering customers as the population of reference.
Use the previously created relative frequency table to answer the following questions.</p>
<p>If we choose a customer at random from this study,</p>
<ol style="list-style-type: lower-alpha">
<li><p>what’s the probability of the customer getting a card <em>and</em> tipping?</p></li>
<li><p>what’s the probability of the customer getting a card <em>or</em> tipping?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-74" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-74&#39;, &#39;sol-start-74&#39;)"></span>
</div>
<div id="sol-body-74" class="solution-body" style="display: none;">
<ol style="list-style-type: lower-alpha">
<li><p>P(some card and tipping) = P(ad card and tipping) + P(joke card and tipping) = 0.06635071 + 0.14218009 = 0.2085308 <span class="math inline">\(\approx\)</span> 0.209</p>
<p>Equivalently,</p>
<p>P(some card and tipping) = P(some card) * P(tipping | some card) = (0.35071090 + 0.34123223) * (0.06635071 + 0.14218009) / (0.35071090 + 0.34123223) = 0.2085308 <span class="math inline">\(\approx\)</span> 0.209</p></li>
<li><p>P(some card or tipping) = P(some card) + P(tipping) - P(some card and tipping) = (0.35071090 + 0.34123223) + (0.28436019) - (0.2085308) = 0.7677725 <span class="math inline">\(\approx\)</span> 0.768</p>
<p>Equivalently,</p>
<p>P(some card or tipping) = 0.28436019 + 0.06635071 + 0.19905213 + 0.14218009 + 0.07582938 = 0.7677725 <span class="math inline">\(\approx\)</span> 0.768</p></li>
</ol>
</div>
<p class="solution-end">
</p>
<!-- 3 -->
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Consider again the relative frequency table for the restaurant tipping study.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What’s the probability of a customer tipping?</p></li>
<li><p>What’s the probability of getting a tip given that the customer received an advertisement card?</p></li>
<li><p>What’s the probability of getting a tip given that the customer received a joke card?</p></li>
<li><p>What’s the probability of getting a tip given that the customer received no card?</p></li>
<li><p>Do you think that tipping is independent of whether you are given an ad, joke, or no card?</p></li>
<li><p>Based on your analysis above, would you suggest a waiter that telling customers a joke while handing out the bill would improve their chance of receiving a tip?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-75" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-75&#39;, &#39;sol-start-75&#39;)"></span>
</div>
<div id="sol-body-75" class="solution-body" style="display: none;">
<ol style="list-style-type: lower-alpha">
<li><p>P(tipping) = 0.28436019 <span class="math inline">\(\approx\)</span> 0.284</p></li>
<li><p>P(tipping | ad card) = 0.06635071 / 0.35071090 = 0.1891892 <span class="math inline">\(\approx\)</span> 0.189</p></li>
<li><p>P(tipping | joke card) = 0.14218009 / 0.34123223 = 0.4166666 <span class="math inline">\(\approx\)</span> 0.417</p></li>
<li><p>P(tipping | no card) = 0.07582938 / 0.30805687 = 0.2461538 <span class="math inline">\(\approx\)</span> 0.246</p></li>
<li><p>No, the events seem to be dependent. The conditional probabilities are different from P(tipping). In particular, the probability of tipping given a joke card is much higher than P(tipping).</p></li>
<li><p>The above results suggest that handing out a joke card when bringing the bill to customers might increase your chance of receiving a tip. So, if you ever find yourself taking coffee orders in a cafe of a seaside resort in the west coast of France, you probably want to learn some jokes!</p></li>
</ol>
</div>
<p class="solution-end">
</p>
<!--# 4 -->
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p><strong>COVID-19 testing.</strong> It is now evident the need for rapidly available COVID-19 testing. However, the results of these tests are inherently governed by probability.
Most people who have COVID-19 will test positive (true positives), while others will test negative (false negatives).
Similarly, most people who do not have COVID-19 will test negative (true negatives), while others might test positive (false positives).</p>
<p>Define the following events:</p>
<ul>
<li><p><span class="math inline">\(T^+ = \text{the person tests positive}\)</span></p></li>
<li><p><span class="math inline">\(T^- = {}\sim T^+ = \text{the person tests negative}\)</span></p></li>
<li><p><span class="math inline">\(C^+ = \text{the person truly has COVID-19}\)</span></p></li>
<li><p><span class="math inline">\(C^- = {}\sim C^+ = \text{the person does not have COVID-19}\)</span></p></li>
</ul>
<p>This can be summarise according to the following table:</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">+ve test (<span class="math inline">\(T^+\)</span>)</th>
<th align="center">-ve test (<span class="math inline">\(T^-\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Has COVID-19 (<span class="math inline">\(C^+\)</span>)</td>
<td align="center">True Positives (TP)</td>
<td align="center">False Negatives (FN)</td>
</tr>
<tr class="even">
<td align="left">Hasn’t COVID-19 (<span class="math inline">\(C^-\)</span>)</td>
<td align="center">False Positives (FP)</td>
<td align="center">True Negatives (TN)</td>
</tr>
</tbody>
</table>
<p><strong>Sensitivity and Specificity.</strong> Infectious disease researchers tend to
rely on two different conditional probabilities when evaluating the
usefulness of a diagnostic test:</p>
<ol style="list-style-type: decimal">
<li><em>Sensitivity</em> - The probability that someone who has the disease
will receive a positive test result (suggesting they have the
disease)</li>
<li><em>Specificity</em> - The probability that someone who does not have the
disease will receive a negative test result (suggesting they do not
have the disease)</li>
</ol>
<p>The better a test is, the closer both of these probabilities will be to
1.</p>
<p>Define what sensitivity and specificity are using the notation for conditional probabilities.</p>
<p>Show how to calculate sensitivity and specificity when starting from a table of true positives, false positives, true negatives, and false negatives.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-76" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-76&#39;, &#39;sol-start-76&#39;)"></span>
</div>
<div id="sol-body-76" class="solution-body" style="display: none;">
<p><span class="math display">\[\text{Sensitivity} = P(T^+ \mid C^+) = \frac{P(T^+ \cap C^+)}{P(C^+)} = \frac{TP}{TP + FN}\]</span></p>
<p><span class="math display">\[\text{Specificity} = P(T^- \mid C^-) = \frac{P(T^- \cap C^-)}{P(C^-)} = \frac{TN}{TN + FP}\]</span></p>
</div>
<p class="solution-end">
</p>
<!-- # 5 -->
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>One recently approved COVID-19 test was created by Abbott Labs and advertises 97.1% sensitivity, and 98.5% specificity (in addition to a claim that its results are available within 15 minutes).</p>
<p>Suppose one person who has COVID-19 takes Abbott Labs’ 15-minute test.
What is the probability they receive a negative test result (suggesting they do not have the disease)?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-77" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-77&#39;, &#39;sol-start-77&#39;)"></span>
</div>
<div id="sol-body-77" class="solution-body" style="display: none;">
<p>We are told that</p>
<p><span class="math display">\[
\text{Sensitivity} = P(T^+ | C^+) = 0.971 \\
\text{Specificity} = P(T^- | C^-) = 0.985
\]</span></p>
<p>The question asks us to compute</p>
<p><span class="math display">\[
P(T^- | C^+) = 1 - P(T^+ | C^+) = 1 - 0.971 = 0.029
\]</span></p>
</div>
<p class="solution-end">
</p>
<!--# 6 -->
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Suppose two people who have COVID-19 each take Abbott Labs’ 15-minute test.</p>
<ul>
<li>What is a <em>trial</em> in this scenario?</li>
<li>What is an <em>outcome</em>?</li>
<li>What is the <em>sample space</em> of the experiment?</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-78" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-78&#39;, &#39;sol-start-78&#39;)"></span>
</div>
<div id="sol-body-78" class="solution-body" style="display: none;">
<ul>
<li><p>Trial: Performing two Abbott Labs’ 15-minute tests on the two individuals.</p></li>
<li><p>Outcome: The potential results of the two tests. For example, the first individual could test negative and the second test positive: <span class="math inline">\((T^-, T^+)\)</span>.</p></li>
<li><p>Sample space: The set of all potential results of the experiment. In this case
<span class="math display">\[
S = \{ (T^-, T^-),\ (T^-, T^+),\ (T^+, T^-),\ (T^+, T^+) \}
\]</span></p></li>
</ul>
</div>
<p class="solution-end">
</p>
<!--# 7 -->
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Suppose two people who have COVID-19 each take Abbott Labs’ 15-minute test. Calculate the probability that <em>both</em> receive a negative test result (suggesting they do not have the disease).
Show your work using proper notation.</p>
<p><strong>Hint:</strong></p>
<ul>
<li><p>Define the events <span class="math inline">\(T_1^- = \text{individual 1 tests negative}\)</span>, <span class="math inline">\(T_2^- = \text{individual 2 tests negative}\)</span>, <span class="math inline">\(C_1^+ = \text{individual 1 has COVID-19}\)</span>, and <span class="math inline">\(C_2^+ = \text{individual 2 has COVID-19}\)</span>.</p></li>
<li><p><span class="math inline">\(P(T_1^- \mid C_1^+ \cap C_2^+) = P(T_1^- \mid C_1^+)\)</span> as the result of the test is independent of the fact that individual 2 has COVID-19.</p></li>
<li><p><span class="math inline">\(P(T_2^- \mid C_1^+ \cap C_2^+) = P(T_2^- \mid C_2^+)\)</span> as the result of the test is independent of the fact that individual 1 has COVID-19.</p></li>
<li><p>Use the two facts above to calculate <span class="math inline">\(P(T_1^- \cap T_2^- \mid C_1^+ \cap C_2^+)\)</span></p></li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-79" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-79&#39;, &#39;sol-start-79&#39;)"></span>
</div>
<div id="sol-body-79" class="solution-body" style="display: none;">
<p>Let <span class="math inline">\(T_1^- = \text{individual 1 tests negative}\)</span>, <span class="math inline">\(T_2^- = \text{individual 2 tests negative}\)</span>, <span class="math inline">\(C_1^+ = \text{individual 1 has COVID-19}\)</span>, and <span class="math inline">\(C_2^+ = \text{individual 2 has COVID-19}\)</span>.</p>
<p>We already found in question 5 that <span class="math inline">\(P(T^- | C^+) = 0.029\)</span>.</p>
<p>The probability of both individuals testing negative is</p>
<p><span class="math display">\[
\begin{aligned}
P(T_1^- \cap T_2^- \mid C_1^+ \cap C_2^+) 
&amp;= P(T_1^- \mid C_1^+ \cap C_2^+) P(T_2^- \mid C_1^+ \cap C_2^+) \\
&amp;= P(T_1^- \mid C_1^+) P(T_2^- \mid C_2^+) \\
&amp;= 0.029 \times 0.029  \\
&amp;= 0.000841 \\
&amp;\approx 0.08 \%
\end{aligned}
\]</span></p>
<p>where we have used the fact that <span class="math inline">\(P(T_1^- \mid C_1^+ \cap C_2^+) = P(T_1^- \mid C_1^+)\)</span> as the result of the test is independent of the fact that individual 2 has COVID-19.</p>
<p>Similarly, <span class="math inline">\(P(T_2^- \mid C_1^+ \cap C_2^+) = P(T_2^- \mid C_2^+)\)</span> as the result of the test is independent of the fact that individual 1 has COVID-19.</p>
</div>
<p class="solution-end">
</p>
<!-- # 8 -->
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Suppose two people who have COVID-19 each take Abbott Labs’ 15-minute test. Calculate the probability that <em>at least one</em> receives a negative test result (suggesting they do not have the disease). Show your work using proper notation.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-80" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-80&#39;, &#39;sol-start-80&#39;)"></span>
</div>
<div id="sol-body-80" class="solution-body" style="display: none;">
<p><span class="math display">\[
\begin{aligned}
P(T_1^{-} \cup T_2^{-} \mid C_1^+ \cap C_2^+) 
&amp;= P(T_1^- | C_1^+ \cap C_2^+) + P(T_2^- | C_1^+ \cap C_2^+) - P(T_1^- \cap T_2^- | C_1^+ \cap C_2^+) \\
&amp;= P(T_1^- | C_1^+) + P(T_2^- | C_2^+) - P(T_1^- \cap T_2^- | C_1^+ \cap C_2^+) \\
&amp;= 0.029 + 0.029 - 0.000841 \\
&amp;= 0.057159 \\
&amp;\approx 5.72\%
\end{aligned}
\]</span></p>
</div>
<p class="solution-end">
</p>
<!--# 9 -->
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Finally, suppose that 25 people who <em>do not have</em> COVID-19 each take Abbott Labs’ 15-minute test. Calculate the probability that <em>at least one</em> receives a positive test result. Show your work using proper notation.</p>
<p><strong>Hint:</strong> Use the complement rule.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-81" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-81&#39;, &#39;sol-start-81&#39;)"></span>
</div>
<div id="sol-body-81" class="solution-body" style="display: none;">
<p>Let <span class="math inline">\(T_i^- = \text{individual i tests negative}\)</span> and <span class="math inline">\(C_i^- = \text{individual i does not have COVID-19}\)</span>.</p>
<p>The probability that at least one individual receives a positive test result is equal to 1 minus the probability that all individuals receive a negative result:</p>
<p><span class="math display">\[
\begin{aligned}
1 - \left( \underbrace{P(T^-_i \mid C_i^-) \times P(T^-_i \mid C_i^-) \times \cdots \times P(T^-_i \mid C_i^-)}_{25 \text{ times}} \right) 
&amp;= 1 - 0.985^{25} \\
&amp;= 0.3146605 \\
&amp;\approx 31.5 \%
\end{aligned}
\]</span></p>
</div>
<p class="solution-end">
</p>
<!-- # 10 -->
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p><strong>Prevalence.</strong>
One issue with screening tests is that probabilities like sensitivity and specificity are <em>conditional probabilities.</em> That is, these probabilities are <em>dependent</em> upon a certain prior event (actually having COVID-19 or not). Infectious disease specialists call the probability of this prior event (actually having the disease) the <em>prevalence.</em> For example, if 10% of the population has COVID-19, we would say the prevalence is 10%.</p>
<p>Suppose 3% of the population of Scotland currently has COVID-19.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability that a randomly selected person (from Scotland) has the disease <em>and</em> tests positive?</p></li>
<li><p>What is the probability that a randomly selected person (from Scotland) does not have the disease <em>and</em> tests positive?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-82" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-82&#39;, &#39;sol-start-82&#39;)"></span>
</div>
<div id="sol-body-82" class="solution-body" style="display: none;">
<p>The question tells us that <span class="math inline">\(P(C^+) = 0.03\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math display">\[
\begin{aligned}
P(C^+ \cap T^+) &amp;= P(C^+) P(T^+ | C^+) \\
&amp;= 0.03 \times 0.971 \\
&amp;= 0.02913 \\
&amp;\approx 2.9 \%
\end{aligned}
\]</span></p></li>
<li><p><span class="math display">\[
\begin{aligned}
P(C^- \cap T^+) &amp;= P(C^-) P(T^+ | C^-) \\
&amp;= (1 - P(C^+)) \times (1 - P(T^- | C^-)) \\
&amp;= (1 - 0.03) \times (1 - 0.985) \\
&amp;= 0.01455 \\
&amp;\approx 1.46 \%
\end{aligned}
\]</span></p></li>
</ol>
</div>
<p class="solution-end">
</p>
<!-- # 11 -->
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Suppose instead that 30% of the population of Scotland currently has COVID-19.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability that a randomly selected person (from Scotland) has the disease <em>and</em> tests positive?</p></li>
<li><p>What is the probability that a randomly selected person (from Scotland) does not have the disease <em>and</em> tests positive?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-83" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-83&#39;, &#39;sol-start-83&#39;)"></span>
</div>
<div id="sol-body-83" class="solution-body" style="display: none;">
<p>The question tells us that <span class="math inline">\(P(C^+) = 0.3\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math display">\[
\begin{aligned}
P(C^+ \cap T^+) &amp;= P(C^+) P(T^+ | C^+) \\
&amp;= 0.3 \times 0.971 \\
&amp;= 0.2913 \\
&amp;\approx 29.1 \%
\end{aligned}
\]</span></p></li>
<li><p><span class="math display">\[
\begin{aligned}
P(C^- \cap T^+) &amp;= P(C^-) P(T^+ | C^-) \\
&amp;= (1 - P(C^+)) \times (1 - P(T^- | C^-)) \\
&amp;= (1 - 0.3) \times (1 - 0.985) \\
&amp;= 0.0105 \\
&amp;\approx 1.05 \%
\end{aligned}
\]</span></p></li>
</ol>
<p>If you compare your answers to question 10 (a) and question 11 (a) you can see that, for a test with a given accuracy, the number of true positives reported depends on how prevalent the disease is in the population, i.e. how many people have COVID-19 in the population.</p>
</div>
<p class="solution-end">
</p>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Gueaguen, N. (2002). The Effects of a Joke on
Tipping When It Is Delivered at the Same Time as the Bill. <em>Journal
of Applied Social Psychology, 32</em>(9), 1955-1963.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
