<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Discrete random variables</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR1</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li>
  <a href="intro_r_rstudio_year1.html">DAPR1 starts here</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to data and R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_data_types.html">1/1: Collecting data</a>
    </li>
    <li>
      <a href="02_categorical.html">1/2: Categorical data</a>
    </li>
    <li>
      <a href="03_numerical.html">1/3: Numerical data</a>
    </li>
    <li>
      <a href="04_relationships.html">1/4: Relationships</a>
    </li>
    <li>
      <a href="05_functions.html">1/5: Types of relations</a>
    </li>
    <li class="dropdown-header">1/6: Break week!</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Probability &amp; sampling
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_probability_basics.html">1/7: Probability basics</a>
    </li>
    <li>
      <a href="08_probability_rules.html">1/8: Probability rules!</a>
    </li>
    <li>
      <a href="09_discrete_distributions.html">1/9: Discrete random variables</a>
    </li>
    <li>
      <a href="10_continuous_distributions.html">1/10: Continuous random variables</a>
    </li>
    <li>
      <a href="11_sampling_distributions.html">1/11: Sampling distributions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Hypothesis testing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="12_bootstrap_cis.html">2/1: Bootstrap &amp; CIs</a>
    </li>
    <li>
      <a href="13_hypothesis_testing.html">2/2: Hypothesis testing: p-values</a>
    </li>
    <li>
      <a href="14_critical_values.html">2/3: Hypothesis testing: critical values</a>
    </li>
    <li>
      <a href="15_connecting_ci_ht.html">2/4: Hypothesis testing &amp; CIs</a>
    </li>
    <li>
      <a href="16_ht_errors.html">2/5: Making decisions</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Basic tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="17_one_sample_mean.html">2/7: Test for one mean</a>
    </li>
    <li>
      <a href="18_two_sample_means.html">2/8: Test for two means</a>
    </li>
    <li>
      <a href="19_paired_t_test.html">2/9: Test for paired samples</a>
    </li>
    <li>
      <a href="20_chi_square.html">2/10: Chi-square</a>
    </li>
    <li>
      <a href="21_covcor.html">2/11: Covariance and correlation</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Discrete random variables</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Distinguish between discrete and continuous random variables</li>
<li>Identify discrete probability distributions</li>
<li>Graph discrete probability distributions</li>
<li>Compute and interpret the mean of a discrete random variable</li>
<li>Compute and interpret the standard deviation of a discrete random variable</li>
</ol>
</div>
<div id="random-variables" class="section level1">
<h1>Random variables</h1>
<p>Consider throwing three fair coins. The sample space of this random experiment is</p>
<p><span class="math display">\[
S = \{
    TTT, \ 
    TTH, \ 
    THT, \ 
    HTT, \ 
    THH, \ 
    HTH, \ 
    HHT, \ 
    HHH
\}
\]</span></p>
<p>Each outcome has an equal chance of occurring of <span class="math inline">\(1 / 8 = 0.125\)</span>, computed as one outcome divided by the total number of possible outcomes.</p>
<p>Often, we are only interested in a numerical summary of the random experiment. One such summary could be the total number of heads.</p>
<div class="yellow">
<p><strong>Random variable</strong></p>
<p>We call a numerical summary of a random process a <strong>random variable</strong>.</p>
<p>Random variables are typically denoted using the last uppercase letters of the alphabet (<span class="math inline">\(X, Y, Z\)</span>). Sometimes we might also use an uppercase letter with a subscript to distinguish them, e.g. <span class="math inline">\(X_1, X_2, X_3\)</span>.</p>
</div>
<p>A random variable, like a random experiment, also has a sample space and this is called the <strong>support</strong> or <strong>range</strong> of <span class="math inline">\(X\)</span>, written <span class="math inline">\(R_X\)</span>. This represents the set of possible values that the random variable can take.</p>
</div>
<div id="discrete-vs-continuous-random-variables" class="section level1">
<h1>Discrete vs continuous random variables</h1>
<p>There are two different types of random variables, and the type is defined by their range.</p>
<p>We call a variable discrete or continuous depending on the “gappiness” of its range, i.e. depending on whether or not there are gaps between successive possible values of a random variable.</p>
<p><img src="images/prob/rvs_range.png" width="90%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>A <strong>discrete</strong> random variable has gaps in between its possible values. An example is the number of children in a randomly chosen family (0, 1, 2, 3, …). Clearly, you can’t have 2.3 children…</p></li>
<li><p>A <strong>continuous</strong> random variable has no gaps in between the its possible values. An example is the height in cm of a randomly chosen individual.</p></li>
</ul>
<p>In this week’s exercises we will study discrete random variables.</p>
</div>
<div id="three-coins-example-continued" class="section level1">
<h1>Three coins example (continued)</h1>
<p>In the 3 coins example, the possible values of the random variable <span class="math inline">\(X\)</span> = “number of heads in 3 tosses” are
<span class="math display">\[
R_X = \{0, 1, 2, 3\}
\]</span></p>
<p>meaning that <span class="math inline">\(X\)</span> is a discrete random variable.</p>
<p>We denote a potential value of the random variable using a lowercase <span class="math inline">\(x\)</span> and a subscript to number the possible values.</p>
<p>This is obtained as follows:
<img src="images/prob/exp_to_rvs.png" width="80%" style="display: block; margin: auto;" /></p>
<p>As we can see, each value of the random variable is computed from the underlying random experiment. There is one outcome only (TTT) leading to zero heads, i.e. <span class="math inline">\(X = 0\)</span>. There are three outcomes (TTH, THT, HTT) leading to one head, i.e. <span class="math inline">\(X = 1\)</span>. And so on…</p>
<p>The experiment’s outcomes are all equally likely, each having a <span class="math inline">\(1/8\)</span> chance of occurring. However, since the random variable aggregates the experiment’s outcomes, the probability of the random variable taking a particular value is computed by summing the probabilities of the outcomes leading to that value.</p>
<p>Let’s try and obtain the same diagram as that shown above using R. We will be using the function <code>expand_grid</code>, which creates the sample space by listing all possible combinations.</p>
<pre class="r"><code>library(tidyverse)

experiment &lt;- expand_grid(coin1 = c(&#39;T&#39;, &#39;H&#39;),
                          coin2 = c(&#39;T&#39;, &#39;H&#39;),
                          coin3 = c(&#39;T&#39;, &#39;H&#39;))
experiment</code></pre>
<pre><code>## # A tibble: 8 x 3
##   coin1 coin2 coin3
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 T     T     T    
## 2 T     T     H    
## 3 T     H     T    
## 4 T     H     H    
## 5 H     T     T    
## 6 H     T     H    
## 7 H     H     T    
## 8 H     H     H</code></pre>
<pre class="r"><code>experiment &lt;- experiment %&gt;% 
    mutate(
        prob = rep( 1/n(), n() )
    )
experiment</code></pre>
<pre><code>## # A tibble: 8 x 4
##   coin1 coin2 coin3  prob
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;
## 1 T     T     T     0.125
## 2 T     T     H     0.125
## 3 T     H     T     0.125
## 4 T     H     H     0.125
## 5 H     T     T     0.125
## 6 H     T     H     0.125
## 7 H     H     T     0.125
## 8 H     H     H     0.125</code></pre>
<pre class="r"><code>rv &lt;- experiment %&gt;%
    mutate(
        value = (coin1 == &#39;H&#39;) + (coin2 == &#39;H&#39;) + (coin3 == &#39;H&#39;)
    ) %&gt;%
    group_by(value) %&gt;%
    summarise(prob = sum(prob))
rv</code></pre>
<pre><code>## # A tibble: 4 x 2
##   value  prob
##   &lt;int&gt; &lt;dbl&gt;
## 1     0 0.125
## 2     1 0.375
## 3     2 0.375
## 4     3 0.125</code></pre>
<p>where <span class="math inline">\(1/8 = 0.125\)</span> and <span class="math inline">\(3/8 = 0.375\)</span>.</p>
<p><br></p>
<p>We can provide a concise representation of a random variable <span class="math inline">\(X\)</span>, the set of all its possible values, and the probabilities of those values by providing the probability distribution of <span class="math inline">\(X\)</span>.
You can think of the probability distribution of a random variable as a succinct way to provide a global picture of the random variable.</p>
<div class="yellow">
<p><strong>Probability distribution</strong></p>
<p>The <strong>probability distribution</strong> of a discrete random variable <span class="math inline">\(X\)</span> provides the possible values of the random variable and their corresponding probabilities.</p>
<p>A probability distribution can be in the form of a table, graph, or mathematical formula.</p>
</div>
<p>We visualise the distribution of a discrete random variable via a <strong>line graph.</strong> This graph gives us, with just a glance, an immediate representation of the distribution of that random variable.</p>
<pre class="r"><code>ggplot(data = rv) +
    geom_segment(aes(x = value, xend = value, y = 0, yend = prob)) +
    geom_point(aes(x = value, y = prob)) +
    labs(x = &quot;Possible values, x&quot;, y = &quot;Probabilities, P(X = x)&quot;)</code></pre>
<p><img src="09_discrete_distributions_files/figure-html/unnamed-chunk-5-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>As you can see, a line graph has gaps in between the possible values the random variable can take, exactly to remind us that the random variable can’t take values that are different from 0, 1, 2, and 3.</p>
<p>Alternatively, you could provide the probability distribution of the random variable in tabular form:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
x
</th>
<th style="text-align:center;">
P(X = x)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
1/8
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3/8
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3/8
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1/8
</td>
</tr>
</tbody>
</table>
<p>Statisticians have also spent lots of time trying to find a mathematical formula for that probability distribution.
The formula is the most concise way to obtain the probabilities as it gives you a generic rule which you can use to compute the probability of any possible value of that random variable. All you have to do is substitute to <span class="math inline">\(x\)</span> the value you are interested in, e.g. 0, 1, 2, or 3.</p>
<div class="yellow">
<p><strong>Probability mass function</strong></p>
<p>The <strong>probability mass function</strong> (pmf) of <span class="math inline">\(X\)</span> assigns a probability, between 0 and 1, to every value of the discrete random variable <span class="math inline">\(X\)</span>.</p>
<p>Either of the following symbols are often used:
<span class="math display">\[
f(x) = P(x) = P(X = x) \qquad \text{for all possible }x
\]</span>
where <span class="math inline">\(P(X = x)\)</span> reads as “the probability that the random variable <span class="math inline">\(X\)</span> equals <span class="math inline">\(x\)</span>”.</p>
<p>The sum of all of these probabilities must be one, i.e.
<span class="math display">\[
\sum_{i} f(x_i) = \sum_{i} P(X = x_i) = 1
\]</span></p>
</div>
<p>Before we define the mathematical function, I need to tell you what a number followed by an exclamation mark means.</p>
<p>In mathematics <span class="math inline">\(n!\)</span>, pronounced “<span class="math inline">\(n\)</span> factorial”, is the product of all the integers from 1 to <span class="math inline">\(n\)</span>. For example, <span class="math inline">\(4! = 4 \cdot 3 \cdot 2 \cdot 1 = 24\)</span>, and <span class="math inline">\(3! = 3 \cdot 2 \cdot 1 = 6\)</span>. By convention, mathematician have decided that <span class="math inline">\(0! = 1\)</span>.</p>
<p>The probability function of <span class="math inline">\(X\)</span> = “number of heads in 3 tosses” makes use of the following numbers:</p>
<ul>
<li><span class="math inline">\(3\)</span>, representing the number of coin flips</li>
<li><span class="math inline">\(\frac{1}{2}\)</span>, the probability of observing heads in a single flip of a fair coin</li>
</ul>
<p>For the three coins example, the probability function of <span class="math inline">\(X\)</span> is
<span class="math display">\[
P(X = x) = \frac{3!}{x!\ (3-x)!} \cdot (1/2)^x \cdot (1/2)^{3-x}
\]</span></p>
<p>Let’s see if the formula gives back the table we created above.</p>
<ul>
<li><p>For <span class="math inline">\(x=0\)</span> we have:</p>
<p><span class="math display">\[
P(X = 0) = \frac{3!}{0!\ 3!} \cdot (1/2)^0 \cdot (1/2)^3 = \frac{6}{6} \cdot 1 \cdot (1/8) = 1/8
\]</span></p></li>
</ul>
<p>And so on… If you want to see the rest, check the optional box below.</p>
<div class="optional-begin">
Optional: I want to see the other probabilities…<span id="opt-start-84" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-84&#39;, &#39;opt-start-84&#39;)"></span>
</div>
<div id="opt-body-84" class="optional-body" style="display: none;">
<ul>
<li><p>For <span class="math inline">\(x = 1\)</span> we have</p>
<p><span class="math display">\[
P(X = 1) = \frac{3!}{1!\ 2!} \cdot (1/2)^1 \cdot (1/2)^2 = \frac{6}{2} \cdot (1/2) \cdot (1/4) = 3 \cdot (1/8) = 3/8
\]</span></p></li>
<li><p>For <span class="math inline">\(x = 2\)</span> we have</p>
<p><span class="math display">\[
P(X = 2) = \frac{3!}{2!\ 1!} \cdot (1/2)^2 \cdot (1/2)^1= \frac{6}{2} \cdot (1/4) \cdot (1/2) = 3 \cdot (1/8) = 3/8
\]</span></p></li>
<li><p>For <span class="math inline">\(x=3\)</span> we have</p>
<p><span class="math display">\[
P(X = 3) = \frac{3!}{3!\ 0!} \cdot (1/2)^3 \cdot (1/2)^0 = \frac{6}{6} \cdot (1/8) \cdot 1 = 1/8
\]</span></p></li>
</ul>
</div>
<p class="optional-end">
</p>
<p>As you can see, this formula will provide you the same values that are listed in the tabular representation of the probability distribution.</p>
</div>
<div id="centre-the-expected-value" class="section level1">
<h1>Centre: the expected value</h1>
<p>Consider a discrete random variable with range <span class="math inline">\(R_X = \{x_1, x_2, \dots, x_n\}\)</span></p>
<p>The expected value (or mean) of a random variable <span class="math inline">\(X\)</span>, denoted by <span class="math inline">\(E(X)\)</span>, <span class="math inline">\(\mu\)</span>, or <span class="math inline">\(\mu_X\)</span>, describes where the probability distribution of <span class="math inline">\(X\)</span> is centred.</p>
<p>We tend to prefer the name “expected value” to “mean” as the random variable is not something the has happened yet, it’s a potentially observable value.
So, the expected value is the typical value we <strong>expect</strong> to observe.</p>
<p>The expected value of <span class="math inline">\(X\)</span> is computed by multiplying each value by its probability and then summing everything:</p>
<p><span class="math display">\[
\begin{aligned}
\mu = E(X) &amp;= x_1 \cdot P(x_1) + x_2 \cdot P(x_2) + \cdots + x_n \cdot P(x_n) \\
&amp;= \sum_{i} x_i \cdot P(x_i)
\end{aligned}
\]</span></p>
<p>For the three coins, the expected value is:
<span class="math display">\[
\mu = 0 \cdot \frac{1}{8} + 1 \cdot \frac{3}{8} + 2 \cdot \frac{3}{8} + 3 \cdot \frac{1}{8} = \frac{3}{2} = 1.5
\]</span></p>
<p>As you can see, 1.5 is not one of the possible values that <span class="math inline">\(X\)</span> can take in that case, as it lies in the gap between the values 1 and 2. However, it is a fictitious number which seems to well represent the centre of that distribution and hence a typical value from that distribution.</p>
</div>
<div id="spread-the-standard-deviation" class="section level1">
<h1>Spread: the standard deviation</h1>
<p>The variability of a random variable <span class="math inline">\(X\)</span> is measured by its standard deviation.</p>
<div class="yellow">
<p><strong>Variance and standard deviation</strong></p>
<p>If <span class="math inline">\(X\)</span> has expected value <span class="math inline">\(\mu\)</span>, the <strong>variance</strong> of <span class="math inline">\(X\)</span> is
<span class="math display">\[
\sigma^2 = \sum_i (x_i - \mu)^2 \cdot P(x_i)
\]</span>
and the <strong>standard deviation</strong> is defined as
<span class="math display">\[
\sigma = \sqrt{\sigma^2}
\]</span></p>
</div>
<!-- # Shifting and combining random variables -->
<!-- Suppose you have a probability distribution with random variable $X$, mean $\mu_X$, and standard deviation $\sigma_X$. -->
<!-- If you compute a new random variable $Y = c + d X$ transforming each value of $X$ by multiplying it by $d$ and then adding $c$, where $c$ and $d$ are constants, then the mean and variance of $Y$ are given by -->
<!-- $$ -->
<!-- \begin{aligned} -->
<!-- \mu_{Y} &= \mu_{c + dX} = c + d \mu_X \\ -->
<!-- \sigma_{Y}^2 &= \sigma_{c + dX}^2 = d^2 \sigma_X^2 -->
<!-- \end{aligned} -->
<!-- $$ -->
<!-- **Addition and subtraction rules for random variables** -->
<!-- If $X$ and $Y$ are random variables, then -->
<!-- $$ -->
<!-- \mu_{X + Y} = \mu_X + \mu_Y \\ -->
<!-- \mu_{X - Y} = \mu_X - \mu_Y -->
<!-- $$ -->
<!-- If $X$ and $Y$ are independent, then -->
<!-- $$ -->
<!-- \sigma^2_{X + Y} = \sigma^2_X + \sigma^2_Y \\ -->
<!-- \sigma^2_{X - Y} = \sigma^2_X + \sigma^2_Y -->
<!-- $$ -->
<!-- No, it's not a typo, the last two formulas both have a plus! -->
</div>
<div id="underlying-random-experiments" class="section level1">
<h1>Underlying random experiments</h1>
<p>As we saw, each random variable is a numerical summary of a random experiment and, as such, it arises from an underlying random experiment.</p>
<p>In this section we will analyse different random experiments, also called <strong>models</strong>, commonly arising in every day situations.</p>
<div id="binomial-model" class="section level2">
<h2>Binomial model</h2>
<div class="frame">
<p><strong>NOTATION</strong></p>
<p><span class="math inline">\(p\)</span> is the probability of a success on any one trial, and <span class="math inline">\(n\)</span> is the number of trials.</p>
</div>
<p>Suppose you have a series of trials that satisfy these conditions:</p>
<ul>
<li><p><strong>B:</strong> They are <em>Bernoulli</em> — that is, each trial must have one of two different outcomes, one called a “success” and the other a “failure.”</p></li>
<li><p><strong>I:</strong> Each trial is <em>independent</em> of the others — that is, the probability of a success doesn’t change depending on what has happened before.</p></li>
<li><p><strong>N:</strong> There is a fixed <em>number</em>, <span class="math inline">\(n\)</span>, of trials.</p></li>
<li><p><strong>S:</strong> The probability, <span class="math inline">\(p\)</span>, of a <em>success</em> is the same on each trial, with <span class="math inline">\(0 \leq p \leq 1\)</span>.</p></li>
</ul>
<p>Then the distribution of the random variable <span class="math inline">\(X\)</span> that counts the number of successes in <span class="math inline">\(n\)</span> trials (each with a probability of success = <span class="math inline">\(p\)</span>) is called a <strong>binomial distribution</strong>.</p>
<p>The numbers <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> are called the <strong>parameters</strong> of the binomial distribution. We write that <span class="math inline">\(X\)</span> follows a binomial distribution with parameters <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> as follows:
<span class="math display">\[
X \sim \text{Binomial}(n,p)
\]</span></p>
<p>Further, the probability that you get exactly <span class="math inline">\(X = x\)</span> successes is
<span class="math display">\[
P(X = x) = \frac{n!}{x!\ (n-x)!} \cdot p^x \cdot (1-p)^{n-x}, \qquad R_X = \{0, 1, 2, ..., n\}
\]</span>
where <span class="math inline">\(n! = n (n-1) (n-2) \cdots 3 \cdot 2 \cdot 1\)</span>.</p>
<p>Do you recognise it from the coins example?</p>
<div id="visual-exploration" class="section level3">
<h3>Visual exploration</h3>
The figure below displays different binomial distributions as <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> vary:
<div class="figure" style="text-align: center"><span id="fig:binom-distrib"></span>
<img src="09_discrete_distributions_files/figure-html/binom-distrib-1.png" alt="The binomial probability distribution as n and p vary." width="90%" />
<p class="caption">
Figure 1: The binomial probability distribution as n and p vary.
</p>
</div>
</div>
<div id="centre-and-spread" class="section level3">
<h3>Centre and spread</h3>
<p>For a random variable <span class="math inline">\(X\)</span> having a binomial distribution with <span class="math inline">\(n\)</span> trials and probability of success <span class="math inline">\(p\)</span>, the mean (expected value) and standard deviation for the distribution are given by
<span class="math display">\[
\mu_X = n p \qquad \text{and} \qquad \sigma_X = \sqrt{n p (1 - p)}
\]</span></p>
</div>
<div id="binomial-distribution-in-r" class="section level3">
<h3>Binomial distribution in R</h3>
<p>The function to compute the binomial probability distribution is</p>
<pre><code>dbinom(x, size, prob)</code></pre>
<p>where:</p>
<ul>
<li><code>x</code> is the values for which we want to compute the probabilities</li>
<li><code>size</code> is <span class="math inline">\(n\)</span> in our notation, the number of trials</li>
<li><code>prob</code> is <span class="math inline">\(p\)</span> in our notation, the probability of success in each trial.</li>
</ul>
<div id="example" class="section level4">
<h4>Example</h4>
<p>A student is attempting a 10-questions multiple choice test. Each question has four different options. If the student answers at random, what is the chance that they correctly answers 2 out of the 10 questions?</p>
<p>As we know that the student is randomly guessing the answers, the probability of a correct answer is <span class="math inline">\(p = 1/4\)</span>.
The probability of answering 2 questions correctly out of the 10 in the test is <span class="math inline">\(P(X = 2)\)</span>:</p>
<pre class="r"><code>dbinom(x = 2, size = 10, prob = 1/4)</code></pre>
<pre><code>## [1] 0.2815676</code></pre>
<p>In a multiple choice test comprising 10 questions having each 4 possible answers, there is a 28% chance of answering exactly 2 questions out of 10 correctly just by random guessing.</p>
<p><br></p>
<p>Note that you can also compute the probabilities for all possible values of <span class="math inline">\(X\)</span> at once:</p>
<pre class="r"><code>tibble(
    values = 0:10,
    prob = dbinom(x = 0:10, size = 10, prob = 1/4)
)</code></pre>
<pre><code>## # A tibble: 11 x 2
##    values        prob
##     &lt;int&gt;       &lt;dbl&gt;
##  1      0 0.0563     
##  2      1 0.188      
##  3      2 0.282      
##  4      3 0.250      
##  5      4 0.146      
##  6      5 0.0584     
##  7      6 0.0162     
##  8      7 0.00309    
##  9      8 0.000386   
## 10      9 0.0000286  
## 11     10 0.000000954</code></pre>
</div>
</div>
</div>
<div id="geometric-model" class="section level2">
<h2>Geometric model</h2>
<p>Suppose you have a series of trials that satisfy these conditions:</p>
<ul>
<li><p>They are Bernoulli — that is, each trial must have one of two different outcomes, one called a “success” and the other a “failure”.</p></li>
<li><p>Each trial is independent of the others; that is, the probability of a success doesn’t change depending on what has happened before.</p></li>
<li><p>The trials continue until the first success.</p></li>
<li><p>The probability, <span class="math inline">\(p\)</span>, of a success is the same on each trial, <span class="math inline">\(0 \leq p \leq 1\)</span>.</p></li>
</ul>
<p>Then the distribution of the random variable <span class="math inline">\(X\)</span> that counts the number of failures before the first “success” is called a geometric distribution.</p>
<p>The probability that the first success occurs after <span class="math inline">\(X = x\)</span> failures is
<span class="math display">\[
P(X = x) = (1 - p)^{x} p, \qquad R_X = \{0, 1, 2, ...\}
\]</span></p>
<p>We write that <span class="math inline">\(X\)</span> follow a geometric distribution with parameter <span class="math inline">\(p\)</span> as follows:
<span class="math display">\[
X \sim \text{Geometric}(p)
\]</span></p>
<div id="visual-exploration-1" class="section level3">
<h3>Visual exploration</h3>
<p>The figure below displays different geometric distributions as <span class="math inline">\(p\)</span> varies:</p>
<p><img src="09_discrete_distributions_files/figure-html/unnamed-chunk-9-1.png" width="90%" style="display: block; margin: auto;" /></p>
</div>
<div id="centre-and-spread-1" class="section level3">
<h3>Centre and spread</h3>
<p>A random variable <span class="math inline">\(X\)</span> that has a geometric distribution with probability of success <span class="math inline">\(p\)</span> has an expected value (mean) and standard deviation of
<span class="math display">\[
\mu_X = \frac{1 - p}{p} \qquad \text{and} \qquad \sigma_X = \sqrt{\frac{1-p}{p^2}}
\]</span></p>
</div>
<div id="geometric-distribution-in-r" class="section level3">
<h3>Geometric distribution in R</h3>
<p>The function to compute the geometric probability distribution is</p>
<pre><code>dgeom(x, prob)</code></pre>
<p>where:</p>
<ul>
<li><code>x</code> is the number of <strong>failures</strong> before the first success</li>
<li><code>prob</code> is <span class="math inline">\(p\)</span> in our notation, the probability of success in each trial.</li>
</ul>
<div id="example-1" class="section level4">
<h4>Example</h4>
<p>Consider rolling a fair six-sided die until a five appears. What is the probability of rolling the first five on the third roll?</p>
<p>First, note that the probability of “success” (observing a five) is <span class="math inline">\(p = 1/6\)</span>.
We are asked to compute the probability of having the first “success” on the 3rd trial.
We want to compute <span class="math inline">\(P(X = 2)\)</span> because we need to have 2 failures followed by a success:</p>
<pre class="r"><code>dgeom(x = 2, prob = 1/6)</code></pre>
<pre><code>## [1] 0.1157407</code></pre>
<p>Thus, there is a 12% chance of obtaining the first five on the 3rd roll of a die.</p>
<hr />
</div>
</div>
</div>
</div>
<div id="glossary" class="section level1">
<h1>Glossary</h1>
<ul>
<li><strong>Random variable.</strong> A numerical summary of a random experiment.</li>
<li><strong>Range of a random variable.</strong> The set of possible values the random variable can take.</li>
<li><strong>Probability distribution.</strong> A table, graph, or formula showing how likely each possible value of a random variable is to occur.</li>
<li><strong>Probability (mass) function.</strong> A function providing the probabilities, between 0 and 1, for each value that the random variable can take. These probabilities must sum to 1.</li>
<li><strong>Binomial random variable.</strong> <span class="math inline">\(X\)</span> represents the number of successes in <span class="math inline">\(n\)</span> trials where the probability of success, <span class="math inline">\(p\)</span>, is constant from trial to trial. It has range <span class="math inline">\(R_X = \{0, 1, 2, ..., n\}\)</span>.</li>
<li><strong>Geometric random variable.</strong> <span class="math inline">\(X\)</span> represents the number of failures until the first success, where the probability of success, <span class="math inline">\(p\)</span>, is constant from trial to trial. It has range <span class="math inline">\(R_X = \{0, 1, 2, ...\}\)</span>.</li>
</ul>
<hr />
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Consider throwing 2 six-sided dice. Using the <code>expand_grid()</code>, <code>mutate()</code>, <code>group_by()</code>, and <code>summarise()</code> functions, compute the probability distribution of the discrete random variable
<span class="math display">\[
X = \text{sum of the two faces}
\]</span></p>
<p>Check if the two requirements of probability functions are met:</p>
<ul>
<li>Are all probabilities between 0 and 1?</li>
<li>Do the probabilities sum to 1?</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-85" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-85&#39;, &#39;sol-start-85&#39;)"></span>
</div>
<div id="sol-body-85" class="solution-body" style="display: none;">
<pre class="r"><code>experiment &lt;- expand_grid(die1 = 1:6,
                          die2 = 1:6)
experiment</code></pre>
<pre><code>## # A tibble: 36 x 2
##     die1  die2
##    &lt;int&gt; &lt;int&gt;
##  1     1     1
##  2     1     2
##  3     1     3
##  4     1     4
##  5     1     5
##  6     1     6
##  7     2     1
##  8     2     2
##  9     2     3
## 10     2     4
## # … with 26 more rows</code></pre>
<pre class="r"><code>experiment &lt;- experiment %&gt;%
    mutate(
        prob = rep( 1/n(), n() )
    )
experiment</code></pre>
<pre><code>## # A tibble: 36 x 3
##     die1  die2   prob
##    &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
##  1     1     1 0.0278
##  2     1     2 0.0278
##  3     1     3 0.0278
##  4     1     4 0.0278
##  5     1     5 0.0278
##  6     1     6 0.0278
##  7     2     1 0.0278
##  8     2     2 0.0278
##  9     2     3 0.0278
## 10     2     4 0.0278
## # … with 26 more rows</code></pre>
<pre class="r"><code>distrib_x &lt;- experiment %&gt;%
    mutate(
        value = die1 + die2
    ) %&gt;%
    group_by(value) %&gt;%
    summarise(prob = sum(prob))
distrib_x</code></pre>
<pre><code>## # A tibble: 11 x 2
##    value   prob
##    &lt;int&gt;  &lt;dbl&gt;
##  1     2 0.0278
##  2     3 0.0556
##  3     4 0.0833
##  4     5 0.111 
##  5     6 0.139 
##  6     7 0.167 
##  7     8 0.139 
##  8     9 0.111 
##  9    10 0.0833
## 10    11 0.0556
## 11    12 0.0278</code></pre>
<p>Check if the probabilities are between 0 and 1:</p>
<pre class="r"><code>all(distrib_x$prob &gt;= 0)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>all(distrib_x$prob &lt;= 1)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Check if the probabilities sum to 1:</p>
<pre class="r"><code>sum(distrib_x$prob)</code></pre>
<pre><code>## [1] 1</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Plot the probability distribution of the random variable <span class="math inline">\(X\)</span> = “sum of the faces of two dice” which you derived in the previous question.</p>
<p>Comment on what the distribution tells us.</p>
<p>Compute the centre and spread of the distribution and interpret them in context.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-86" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-86&#39;, &#39;sol-start-86&#39;)"></span>
</div>
<div id="sol-body-86" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(data = distrib_x) +
    geom_segment(aes(x = value, xend = value, y = 0, yend = prob)) +
    geom_point(aes(x = value, y = prob)) +
    labs(x = &quot;Possible values, x&quot;, y = &quot;Probabilities, P(X = x)&quot;,
         title = &quot;Distribution of the sum of two dice&quot;)</code></pre>
<p><img src="09_discrete_distributions_files/figure-html/unnamed-chunk-14-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Expected value and standard deviation</p>
<pre class="r"><code>distrib_x %&gt;%
    summarise(
        mu = sum(value * prob),
        sigma = sqrt( sum((value - mu)^2 * prob) )
    )</code></pre>
<pre><code>## # A tibble: 1 x 2
##      mu sigma
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     7  2.42</code></pre>
<p>The distribution tells us how likely each sum of the two dice is to happen.
We can see that 7 has the highest chance of occurring, followed by 6 and 8, 5 and 9, and so on.</p>
<p>The distribution is centred at 7 with a standard deviation of 2.4.
Hence, a typical sum from two dice will be roughly 7, while a typical distance of a single sum from the mean is around 2.4.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Create a graph showing the distribution of a Binomial random variable <span class="math inline">\(X\)</span> when <span class="math inline">\(n = 10\)</span> and <span class="math inline">\(p = 0.5\)</span>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-87" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-87&#39;, &#39;sol-start-87&#39;)"></span>
</div>
<div id="sol-body-87" class="solution-body" style="display: none;">
<pre class="r"><code>n &lt;- 10
p &lt;- 0.5

tibble(
    x = 0:n,
    prob = dbinom(x = x, size = n, prob = p)
) %&gt;%
    ggplot() +
    geom_segment(aes(x = x, xend = x, y = 0, yend = prob)) +
    geom_point(aes(x = x, y = prob)) +
    labs(x = &quot;Possible values, x&quot;, y = &quot;Probabilities, P(X = x)&quot;,
         title = &quot;Binomial(n = 10, p = 0.5)&quot;)</code></pre>
<p><img src="09_discrete_distributions_files/figure-html/unnamed-chunk-16-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Create a graph showing the distribution of a Geometric random variable <span class="math inline">\(X\)</span> when <span class="math inline">\(p = 0.5\)</span>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-88" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-88&#39;, &#39;sol-start-88&#39;)"></span>
</div>
<div id="sol-body-88" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 0.5

tibble(
    x = 0:10, # grid of values for plotting, the upper value can be whatever
    prob = dgeom(x = x, prob = p)
) %&gt;%
    ggplot() +
    geom_segment(aes(x = x, xend = x, y = 0, yend = prob)) +
    geom_point(aes(x = x, y = prob)) +
    labs(x = &quot;Possible values, x&quot;, y = &quot;Probabilities, P(X = x)&quot;,
         title = &quot;Geometric(p = 0.5)&quot;)</code></pre>
<p><img src="09_discrete_distributions_files/figure-html/unnamed-chunk-17-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Consider a random variable <span class="math inline">\(X\)</span> having the following distribution. Compute the expected value and standard deviation of <span class="math inline">\(X\)</span>.</p>
<table>
<thead>
<tr class="header">
<th align="center">Value</th>
<th align="center">Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0</td>
<td align="center"><span class="math inline">\(1 - p\)</span></td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center"><span class="math inline">\(p\)</span></td>
</tr>
</tbody>
</table>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-89" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-89&#39;, &#39;sol-start-89&#39;)"></span>
</div>
<div id="sol-body-89" class="solution-body" style="display: none;">
<p>Expected value:
<span class="math display">\[
\mu = 0 \cdot (1 - p) + 1 \cdot p = p
\]</span></p>
<p>Variance:
<span class="math display">\[
\sigma^2 = (0 - p)^2 \cdot (1 - p) + (1 - p)^2 \cdot p = (1 - p) (p^2 + p (1-p)) = (1 - p) \cdot p
\]</span></p>
<p>Standard deviation:
<span class="math display">\[
\sigma = \sqrt{\sigma^2} = \sqrt{p \cdot (1 - p)}
\]</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>According to a briefing paper to the UK House of Commons, nearly 29% of the population, or 19 million, live below the poverty level.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
Suppose these figures hold true for the region in which you live. You plan to randomly sample 25 individuals from your region.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability that your sample will include at least two people with incomes below the poverty level?</p>
<p><strong>Hint:</strong> <span class="math inline">\(P(X \geq 2) = 1 - P(X = 0) - P(X = 1)\)</span>.</p></li>
<li><p>What are the expected value and standard deviation of the number of people in your sample with incomes below the poverty level?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-90" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-90&#39;, &#39;sol-start-90&#39;)"></span>
</div>
<div id="sol-body-90" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 0.29
n &lt;- 25

1 - dbinom(0, n, p) - dbinom(1, n, p)</code></pre>
<pre><code>## [1] 0.9978565</code></pre>
<p>The probability that our sample will include at least two people with incomes below poverty level is 0.998.</p>
<pre class="r"><code>n*p</code></pre>
<pre><code>## [1] 7.25</code></pre>
<pre class="r"><code>sqrt(n * p * (1 - p))</code></pre>
<pre><code>## [1] 2.26881</code></pre>
<p>On average, roughly 7 people in the sample will have incomes below poverty level, with a standard deviation of approximately 2 people.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>A recent survey has found that about 16% of residents have no home insurance. You are to randomly sample 20 residents for a survey.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability that your sample will include at least three people who do not have home insurance?</p></li>
<li><p>What are the expected value and standard deviation of the number of people in your sample without home insurance?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-91" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-91&#39;, &#39;sol-start-91&#39;)"></span>
</div>
<div id="sol-body-91" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 0.16
n &lt;- 20

1 - dbinom(0, n, p) - dbinom(1, n, p) - dbinom(2, n, p)</code></pre>
<pre><code>## [1] 0.6420017</code></pre>
<p>There is a 64% chance that at least three people in the sample will not have home insurance.</p>
<pre class="r"><code>n * p</code></pre>
<pre><code>## [1] 3.2</code></pre>
<pre class="r"><code>sqrt(n * p * (1 - p))</code></pre>
<pre><code>## [1] 1.639512</code></pre>
<p>On average, among the 20 people in the sample, 3 will not have home insurance, with a standard deviation of roughly 2 individuals.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Suppose you are rolling a pair of dice and waiting for a sum of 7 to occur.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability that you get a sum of 7 for the first time on your first roll?</p></li>
<li><p>What is the probability that you get a sum of 7 for the first time on your second roll?</p></li>
<li><p>What is the probability that it takes more than 10 rolls to get a sum of 7?</p></li>
</ol>
<p><strong>Hint</strong>: Getting a success for the first time on the 3rd trial means having 2 failures first, so we would use <code>dgeom(2, p)</code>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-92" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-92&#39;, &#39;sol-start-92&#39;)"></span>
</div>
<div id="sol-body-92" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 6/36

dgeom(0, p)</code></pre>
<pre><code>## [1] 0.1666667</code></pre>
<p>The probability of getting a sum of 7 for the first time on the first roll is approximately 0.167.</p>
<pre class="r"><code>dgeom(1, p)</code></pre>
<pre><code>## [1] 0.1388889</code></pre>
<p>The probability of getting a sum of 7 for the first time on the second roll is approximately 0.139.</p>
<pre class="r"><code>1 - sum(dgeom(0:10, p))</code></pre>
<pre><code>## [1] 0.134588</code></pre>
<p>The probability that it takes more than 10 rolls to get a sum of 7 is 0.135 approximately.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>A light bulb company advertises a fault rate of 1.1%</p>
<p>Suppose you buy 20 light bulbs all of the same model by randomly picking one from 20 different stores in your area.</p>
<p>You find that among the bulbs that you bought, the number of faulty ones is 3 out of 20.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Visualise the probability distribution of the number of faulty light bulbs out of a sample of 20, if the probability of a faulty light bulb is truly 1.1%</p></li>
<li><p>What’s the chance of observing 3 faulty light bulbs out of 20, if the true fault rate is 1.1%?</p></li>
<li><p>Based on your answer to part b, do you think there is enough evidence to doubt the fault rate advertised by the company? In other words, under the advertised fault rate of 1.1%, is this chance of getting 3 faulty bulbs out of 20 high enough to support the company’s claim?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-93" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-93&#39;, &#39;sol-start-93&#39;)"></span>
</div>
<div id="sol-body-93" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 1.1 / 100
n &lt;- 20

tibble(
    value = 0:n,
    prob = dbinom(value, n, p)
) %&gt;%
    ggplot() +
    geom_segment(aes(x = value, xend = value, y = 0, yend = prob)) +
    geom_point(aes(x = value, y = prob)) +
    labs(x = &quot;Possible values, x&quot;, y = &quot;Probabilities, P(X = x)&quot;)</code></pre>
<p><img src="09_discrete_distributions_files/figure-html/unnamed-chunk-25-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p><strong>If the true fault rate is really 1.1%,</strong> out of 20 light bulbs we would expect either 0 or 1 to be faulty, as those numbers have a relatively higher chance of occurring.
The chance of having no faulty bulbs in the sample is 80%, while the chance of having 1 faulty one in the sample is roughly 20%.</p>
<p>Having 3 faulty bulbs in a sample of 20 appears to be quite rare according to the distribution which assumes that the probability of a faulty bulb is 1.1%.</p>
<pre class="r"><code>dbinom(3, n, p)</code></pre>
<pre><code>## [1] 0.001257245</code></pre>
<p>In fact, the probability of observing 3 faulty bulbs in a sample of 20 is 0.001, or 1 out of 1000.</p>
<p>Due to this extremely low chance of observing 3 faulty light bulbs in a sample of 20 we consider the company advertised fault rate of 1.1% to be false advertisement.</p>
<p><br></p>
<p><strong>Optional: Testing a claim</strong></p>
<p>Statisticians typically decide whether there is sufficient evidence in favour of the company’s claim or if there is strong evidence against the company’s claim by computing the probability of obtaining as many faulty ones as in the sample, or even more.</p>
<p>That represents the probability of getting a result as extreme as the sample, or more extreme. Statisticians call this quantity probability value, or <strong>p-value</strong> in short.</p>
<p>In our case this would be</p>
<pre class="r"><code>1 - sum(dbinom(0:2, n, p))</code></pre>
<pre><code>## [1] 0.00131885</code></pre>
<p>Under the advertised fault rate of 1.1%, there is only a .001 chance of obtaining 3 or more faulty light bulbs in a sample of 20 light bulbs.
That is, this would happen only 1 in 1000 times — this means one sample of 20 bulbs will have 3 or more faulty light bulbs out of 1000 samples of 20 light bulbs each.</p>
<p>There is strong evidence against the company’s advertised fault rate. Hence, we conclude that the true fault rate is not 1.1%, and it might actually be higher.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Source: Poverty in the UK: statistics, Briefing Paper Number 7096, 18 June 2020, <a href="https://researchbriefings.files.parliament.uk/documents/SN07096/SN07096.pdf" class="uri">https://researchbriefings.files.parliament.uk/documents/SN07096/SN07096.pdf</a>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
