<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Continuous random variables</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR1</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li>
  <a href="intro_r_rstudio_year1.html">DAPR1 starts here</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to data and R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_data_types.html">1/1: Collecting data</a>
    </li>
    <li>
      <a href="02_categorical.html">1/2: Categorical data</a>
    </li>
    <li>
      <a href="03_numerical.html">1/3: Numerical data</a>
    </li>
    <li>
      <a href="04_relationships.html">1/4: Relationships</a>
    </li>
    <li>
      <a href="05_functions.html">1/5: Types of relations</a>
    </li>
    <li class="dropdown-header">1/6: Break week!</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Probability &amp; sampling
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_probability_basics.html">1/7: Probability basics</a>
    </li>
    <li>
      <a href="08_probability_rules.html">1/8: Probability rules!</a>
    </li>
    <li>
      <a href="09_discrete_distributions.html">1/9: Discrete random variables</a>
    </li>
    <li>
      <a href="10_continuous_distributions.html">1/10: Continuous random variables</a>
    </li>
    <li>
      <a href="11_sampling_distributions.html">1/11: Sampling distributions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Hypothesis testing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="12_bootstrap_cis.html">2/1: Bootstrap &amp; CIs</a>
    </li>
    <li>
      <a href="13_hypothesis_testing.html">2/2: Hypothesis testing: p-values</a>
    </li>
    <li>
      <a href="14_critical_values.html">2/3: Hypothesis testing: critical values</a>
    </li>
    <li>
      <a href="15_connecting_ci_ht.html">2/4: Hypothesis testing &amp; CIs</a>
    </li>
    <li>
      <a href="16_ht_errors.html">2/5: Making decisions</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Basic tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="17_one_sample_mean.html">2/7: Test for one mean</a>
    </li>
    <li>
      <a href="18_two_sample_means.html">2/8: Test for two means</a>
    </li>
    <li>
      <a href="19_paired_t_test.html">2/9: Test for paired samples</a>
    </li>
    <li>
      <a href="20_chi_square.html">2/10: Chi-square</a>
    </li>
    <li>
      <a href="21_covcor.html">2/11: Covariance and correlation</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Continuous random variables</h1>

</div>


<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand the concept of density function.</li>
<li>Be able to link probabilities to areas under a density function.</li>
<li>Recognise the mean as the centre of gravity of a density curve and the standard deviation as the spread of the density curve.</li>
<li>Be able to work with a normal distribution.</li>
</ol>
</div>
<div id="continuous-random-variables" class="section level1">
<h1>Continuous random variables</h1>
<p>Recall that a random variable is continuous if there are no gaps between the possible values it can take.</p>
<p><img src="images/prob/rvs_range.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Imagine a spinner numbered with the hours of the day. If you were to spin it with some strength, what’s the probability of the hand stopping <em>exactly</em> at 3.5173847294 hours?</p>
<p>Well, there is only one way to observe 3.5173847294, while there are an infinite number of possibilities between 0 and 24 hours (you could have as many decimals as you wish).</p>
<p>Define the event <span class="math inline">\(A = \{ 3.5173847294 \}\)</span>. If you were to calculate the probability of observing <span class="math inline">\(A\)</span> using the standard formula you would get:
<span class="math display">\[
P(A) = \frac{n_A}{n} = \frac{1}{\infty} = 0
\]</span></p>
<p>The probability of the hand stopping <em>exactly</em> at 3.5173847294 hours is 0.</p>
<p>Check this with R:</p>
<pre class="r"><code>1 / Inf</code></pre>
<pre><code>## [1] 0</code></pre>
<p>For this reason, we cannot compute probabilities for continuous random variables in the same way as we did in the previous weeks (number of outcomes in the event / number of possible outcomes).</p>
<div class="frame">
<p><strong>Key point</strong></p>
<p>For continuous random variables we can only compute the probability of observing a value <em><strong>in a given interval.</strong></em>
For example, the probability that the hand stops in between 3 and 3.5 hours.</p>
</div>
<p>Consider the histogram shown below. The height of each rectangle will tell you the number of people having a value within a specific interval. For example, the number of people having a value of <span class="math inline">\(x\)</span> between 20 and 22.5.</p>
<p><img src="10_continuous_distributions_files/figure-html/unnamed-chunk-4-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<div id="proportions-as-areas-the-density-histogram" class="section level1">
<h1>Proportions as areas: the density histogram</h1>
<p>The natural gestation period for human births has a mean of about 266 days and a standard deviation of about 16 days.
A group of researchers recorded the gestation period (in days) of 10,000 babies and the distribution is shown below as a <em>frequency histogram</em> (left panel) and <em>relative frequency</em> histogram (right panel).</p>
<p><br></p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-5"></span>
<img src="10_continuous_distributions_files/figure-html/unnamed-chunk-5-1.png" alt="Frequency histogram (left panel) and relative frequency histogram (right panel) of gestation period." width="100%" />
<p class="caption">
Figure 1: Frequency histogram (left panel) and relative frequency histogram (right panel) of gestation period.
</p>
</div>
<p><br></p>
<p>The histogram is unimodal, with the modal interval extending from 266 to 270 days.
The distribution is symmetric around the centre (266). This means that if you were the fold the histogram at 266 days, the two halves would match when superimposed.</p>
<p>The histogram also highlights some variability in gestation days from person to person, with some women giving birth after as low as 200 days or as high as 320 days.</p>
<p>Usually, histograms are drawn with the height of the rectangle for the <span class="math inline">\(j\)</span>th interval being either the frequency (count) <span class="math inline">\(n_j\)</span> or the relative frequency <span class="math inline">\(n_j / n\)</span> of observations falling into that interval.</p>
<p>For example, for roughly 400 women the gestation period was between 240 and 245 days.
If we use the relative frequency, instead, the <em>height</em> of the rectangle tells us the proportion of observations in that interval. In this case, the proportion of women with a gestation period between 240 and 245 days is <span class="math inline">\(400 / 10,000 = 0.04\)</span>.</p>
<p>We now discuss a third type of histogram called the <em><strong>density histogram</strong></em>, in which we adjust the heigh of the rectangle so that the <em>area</em> is equal to the relative frequency.
This is accomplished by changing the height to <span class="math inline">\(n_j / (n w)\)</span> where <span class="math inline">\(w\)</span> is the interval width.</p>
<p>Why does this work?
<span class="math display">\[
area = width \cdot height = w \cdot \frac{n_j}{n w} = \frac{n_j}{n}
\]</span></p>
<p>So now it is the <em>area</em> of the <span class="math inline">\(j\)</span>th rectangle that tells us the proportion of observations in the <span class="math inline">\(j\)</span>th interval.</p>
<p><br></p>
<div class="figure" style="text-align: center"><span id="fig:dens-hist-ab"></span>
<img src="10_continuous_distributions_files/figure-html/dens-hist-ab-1.png" alt="Density histogram of the gestation period for the 10,000 women in the study." width="100%" />
<p class="caption">
Figure 2: Density histogram of the gestation period for the 10,000 women in the study.
</p>
</div>
<p><br></p>
<p>In Figure <a href="#fig:dens-hist-ab">2</a>(a) the proportion of women under study whose gestation period falls within any class interval is the area of the corresponding rectangle.
For example the proportion of women with a gestation period between 240 and 245 days is equal to <span class="math inline">\(area = width \cdot height = 5 \cdot 0.008 = 0.04\)</span>, which matches the relative frequency histogram.</p>
<p>Furthermore, we can obtain the proportion of women whose gestation period falls between the limits <span class="math inline">\(a = 240\)</span> days and <span class="math inline">\(b = 255\)</span> days by adding the areas of all the rectangles between these limits. As the graph in Figure <a href="#fig:dens-hist-ab">2</a>(b) tells us, the area of the shaded part is .196.
Thus, the proportion of women with a gestation period between 240 and 255 days is 0.196 or 19.6% of the women in the study population.</p>
<p>This correspondence between area and proportions is the foundation on which the probability for continuous random variables is built.
In fact, we can say that the probability that a randomly picked woman from the study population has a gestation period between 240 and 255 days is 0.196.</p>
<p>Also, note that the total area under a density histogram is
<span class="math display">\[
\sum \left( \frac{n_j}{n w} \cdot w \right) = \frac{\sum  n_j}{n} = 1
\]</span></p>
<p><br></p>
<div class="frame">
<p>Let’s now summarise what we have learned about <em><strong>density histograms</strong></em>:</p>
<ul>
<li><p>the vertical scale is <em><strong>relative frequency / interval width</strong></em></p></li>
<li><p>the total area under the histogram is 1</p></li>
<li><p>the <em><strong>proportion</strong></em> of data between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> is the <em><strong>area</strong></em> under the histogram between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span></p></li>
</ul>
</div>
<p><br></p>
<div class="figure" style="text-align: center"><span id="fig:dens-hist-cd"></span>
<img src="10_continuous_distributions_files/figure-html/dens-hist-cd-1.png" alt="Density curve of the gestation period for the 10,000 women in the sample." width="100%" />
<p class="caption">
Figure 3: Density curve of the gestation period for the 10,000 women in the sample.
</p>
</div>
<p><br></p>
<p>In Figure <a href="#fig:dens-hist-cd">3</a>(c) we have superimposed an approximating smooth curve on top of the density histogram. Figure <a href="#fig:dens-hist-cd">3</a>(d) displays only the approximating smooth curve. Furthermore, we have also highlighted in green the area under that curve in between the same limit as the histogram (<span class="math inline">\(a = 240\)</span> and <span class="math inline">\(b = 255\)</span>) and calculated the highlighted area.
That area turned out to be 0.194, which is very close to the area of 0.196 computed from the density histogram.</p>
<p>From this, it is quite easy to see how areas under the smooth curve in between two particular limits are in good agreement with the same areas computed using a density histogram, and thus with proportions of people in the study.</p>
<p>Such smooth curve is called a <em><strong>density curve</strong></em> or <em><strong>density function</strong></em>. The probability distribution of a continuous random variable <span class="math inline">\(X\)</span> is specified in terms of its density function. We calculate the probability that the random variable <span class="math inline">\(X\)</span> is between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> by finding the area under the density curve between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>.</p>
<div class="frame">
<p>Let’s now summarise what we have learned about <em><strong>density functions</strong></em>:</p>
<ul>
<li><p>The probability distribution of a continuous random variable is specified in terms of a density function (i.e., a density curve).</p></li>
<li><p>Probabilities are obtained as areas under the density curve.</p></li>
<li><p>The total area under the curve is one.</p>
<p>This is because the total probability must be one: <span class="math inline">\(P(R_X) = 1\)</span>.</p></li>
<li><p>The curve is always greater than or equal to zero for all possible values of the random variable.</p>
<p>This is similar to saying that probabilities cannot be negative.</p></li>
</ul>
</div>
<p>Last week we said that the probability distribution of a random variable <span class="math inline">\(X\)</span> provides a concise representation of the random variable in terms of the set of all the possible values it can take and the corresponding probabilities.
Clearly, this gives an immediate global picture of the random variable.</p>
<div class="yellow">
<p><strong>Probability distribution for a continuous random variable</strong></p>
<p>The <em><strong>probability distribution</strong></em> of a continuous random variable <span class="math inline">\(X\)</span> provides the possible values of the random variable and their corresponding <em><strong>probability densities</strong></em>.</p>
<p>A probability distribution can be in the form of a graph or mathematical formula.</p>
</div>
<p>The density curve is the graphical representation of the probability distribution, while the density function is the mathematical formula of the curve.</p>
<div class="optional-begin">
Help! I am slightly lost…<span id="opt-start-94" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-94&#39;, &#39;opt-start-94&#39;)"></span>
</div>
<div id="opt-body-94" class="optional-body" style="display: none;">
<p>To revise the following topics click on the links below:</p>
<ul>
<li><p>Semester 1, Week 2: <a href="https://uoepsy.github.io/dapr1/labs/02_categorical.html#Frequency_table">Frequency distributions</a></p></li>
<li><p>Semester 1, Week 3: <a href="https://uoepsy.github.io/dapr1/labs/03_numerical.html#Histograms">Histograms and densities</a></p></li>
</ul>
</div>
<p class="optional-end">
</p>
<!-- # Probabilities and density curves -->
<!-- We are now going to take one step further. Think of the density function as a _model_ for the random process generating sample data on a continuous variable $X$, such as gestation period, in which the probability distribution is described by that smooth curve. -->
<!-- ```{r, echo=FALSE, fig.height = 8, out.width='90%'} -->
<!-- plot_dens <- function(n, b) { -->
<!--     df <- tibble( -->
<!--         y = rnorm(n, 100, 16) -->
<!--     ) -->
<!--     plt <- ggplot(df, aes(x = y)) + -->
<!--         geom_histogram(aes(y = ..density..),  -->
<!--                        fill = 'gray',color = 'white', bins = b) + -->
<!--         geom_function(fun = dnorm, args = list(mean = 100, sd = 16)) +  -->
<!--         theme_minimal() + -->
<!--         labs(x = 'IQ score', y = 'Density', -->
<!--              title = sprintf('%d observations, %d class intervals', n, b)) -->
<!--     return(plt) -->
<!-- } -->
<!-- (plot_dens(300, 30) | plot_dens(300, 70)) / -->
<!--     (plot_dens(300, 30) | plot_dens(300, 70)) / -->
<!--     (plot_dens(5000, 30) | plot_dens(5000, 70)) / -->
<!--     (plot_dens(100000, 30) | plot_dens(500000, 70)) -->
<!-- ``` -->
<!-- The distribution generating data on a continuous variable is described by a smooth curve called a density function. -->
<!-- Probabilities are represented by areas under the curve. -->
<!-- The total area under the curve is 1. -->
<!-- It takes very large sample sizes before the regularity of the underlying curve is reliably reflected in histograms of data from the distribution. -->
<!-- In the _long_ run, randomness will even out "noise" and show us the true density curve of the data. -->
</div>
<div id="the-normal-distribution" class="section level1">
<h1>The normal distribution</h1>
<p>A symmetric and bell-shaped density curve is called a <em><strong>normal</strong></em> density curve.</p>
<div class="yellow">
<p><strong>Normal distribution</strong></p>
<p>A continuous random variable is said to be <em><strong>normally distributed</strong></em>, or to have a <em><strong>normal probability distribution</strong></em>, if its distribution has the shape of a normal curve (it is symmetric and bell-shaped).</p>
</div>
<p>The normal density function is the function used to calculate probabilities (as areas under the density curve) for a normally distributed random variable.</p>
<div class="frame">
<p><strong>Key question</strong></p>
<p>How can we make sure that the normal curve can adapt to any symmetric and bell-shaped density histogram?</p>
</div>
<p>Every histogram can be centred at a different value and have a different spread. Hence, we need to specify:</p>
<ol style="list-style-type: decimal">
<li>where the normal curve should be centred at;</li>
<li>what should the spread of the normal curve be.</li>
</ol>
<p>From this we can see that the normal curve depends on two quantities called the <em><strong>parameters</strong></em> of the normal distribution (see Figure <a href="#fig:normal-vary-params">4</a>):</p>
<ol style="list-style-type: decimal">
<li>the mean <span class="math inline">\(\mu\)</span>, specifying the centre of the distribution;</li>
<li>the standard deviation <span class="math inline">\(\sigma\)</span>, specifying the spread of the distribution.</li>
</ol>
<div class="figure" style="text-align: center"><span id="fig:normal-vary-params"></span>
<img src="10_continuous_distributions_files/figure-html/normal-vary-params-1.png" alt="Normal curves for different means and standard deviations." width="100%" />
<p class="caption">
Figure 4: Normal curves for different means and standard deviations.
</p>
</div>
<p>As we can see, changing <span class="math inline">\(\mu\)</span> shifts the curve along the axis, while increasing <span class="math inline">\(\sigma\)</span> increases the spread and flattens the curve.</p>
<p>The formula for the normal density curve which we plotted above is provided below. However, you do not have to memorise it as this is already implemented in R:
<span class="math display">\[
f(x) = \frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{(x - \mu)^2}{2 \sigma^2}}
\]</span>
for some values of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>.</p>
<p>The same function in R is:</p>
<pre><code>dnorm(x, mean = &lt;mean&gt;, sd = &lt;sd&gt;)</code></pre>
<p>where:</p>
<ul>
<li><code>x</code> represents the value of the random variable</li>
<li><code>mean</code> the mean of the normal curve</li>
<li><code>sd</code> the standard deviation of the curve</li>
</ul>
<p>We write that a random variable <span class="math inline">\(X\)</span> <em>follows</em> a normal distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> as
<span class="math display">\[
X \sim N(\mu, \sigma)
\]</span></p>
<p>Clearly, the mean and standard deviation of <span class="math inline">\(X\)</span> will be <span class="math inline">\(E(X) = \mu\)</span> and <span class="math inline">\(SD(X) = \sigma\)</span> respectively.</p>
<p>We use lowercase letters such as <span class="math inline">\(x, a, b\)</span> to denote an observed value, or a particular value, of the random variable <span class="math inline">\(X\)</span>.</p>
</div>
<div id="the-68-95-99.7-rule" class="section level1">
<h1>The 68-95-99.7% rule</h1>
<p>A variable which is normally distributed has:</p>
<ul>
<li><p>68% of the observations (values) within <span class="math inline">\(1\sigma\)</span> of the <span class="math inline">\(\mu\)</span></p></li>
<li><p>95% of its observations (values) within <span class="math inline">\(2\sigma\)</span> of the <span class="math inline">\(\mu\)</span></p></li>
<li><p>99.7% of its observations (values) within <span class="math inline">\(3\sigma\)</span> of the <span class="math inline">\(\mu\)</span></p></li>
</ul>
<p><img src="images/prob/normal_rule.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="obtaining-probabilities" class="section level1">
<h1>Obtaining probabilities</h1>
<p>Before describing how to compute the probabilities for a continuous random variable using R, we need to discuss an important property that only holds for <em>continuous</em> random variables:</p>
<div class="yellow">
<p><strong>Interval endpoints for continuous random variables</strong></p>
<p>When performing calculations involving a <em>continuous</em> random variable, we do not have to worry about whether interval endpoints are included or not in the calculation:
<span class="math display">\[
P(a \leq X \leq b) = P(a \leq X &lt; b) = P(a &lt; X \leq b) = P(a &lt; X &lt; b)
\]</span></p>
<p>This is due to the fact that the probability of <span class="math inline">\(X\)</span> being equal to a specific value is 0:
<span class="math display">\[
\begin{aligned}
P(X \leq x) &amp;= P(X &lt; x) + P(X = x) \\
&amp;= P(X &lt; x) + 0 \\
&amp;= P(X &lt; x)
\end{aligned}
\]</span></p>
</div>
<p>We compute areas under the normal curve using the function <code>pnorm(x, mean, sd)</code>.
This returns the area to the left of <code>x</code> in a normal curve centred at <code>mean</code> and having standard deviation <code>sd</code>:
<span class="math display">\[
P(X \leq x) = P(X &lt; x) = \texttt{pnorm}(x, \texttt{ mean = } \mu, \texttt{ sd = } \sigma)
\]</span></p>
<p>The following figure shows the type of areas returned by the <code>pnorm</code> function:</p>
<div class="figure" style="text-align: center"><span id="fig:norm-dist-pnorm"></span>
<img src="images/prob/normal_pnorm.png" alt="R computes lower-tail probabilities." width="80%" />
<p class="caption">
Figure 5: R computes lower-tail probabilities.
</p>
</div>
<p>For example, the probability that the random variable <span class="math inline">\(X \sim N(\mu = 5, \sigma = 2)\)</span> is less than 1 is:</p>
<pre class="r"><code>pnorm(1, mean = 5, sd = 2)</code></pre>
<pre><code>## [1] 0.02275013</code></pre>
<p><br></p>
<p>There are three types of probabilities that we might want to compute:</p>
<ol style="list-style-type: decimal">
<li><p>The probability that <span class="math inline">\(X\)</span> is less than a given value: <span class="math inline">\(P(X &lt; x)\)</span></p></li>
<li><p>The probability that <span class="math inline">\(X\)</span> is between a lower and an upper value: <span class="math inline">\(P(x_l &lt; X &lt; x_u)\)</span></p></li>
<li><p>The probability that <span class="math inline">\(X\)</span> is greater than a given value: <span class="math inline">\(P(X &gt; x)\)</span></p></li>
</ol>
<p>We will now analyse each case in turn and show how each of these is computed.</p>
<div id="area-to-the-left-of-a-value-x" class="section level2">
<h2>1. Area to the left of a value <span class="math inline">\(x\)</span></h2>
<p>The probability that <span class="math inline">\(X &lt; x\)</span> is directly returned by <code>pnorm()</code>:</p>
<p><img src="images/prob/pnorm_left.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="area-between-the-values-x_l-and-x_u" class="section level2">
<h2>2. Area between the values <span class="math inline">\(x_l\)</span> and <span class="math inline">\(x_u\)</span></h2>
<p>The probability that <span class="math inline">\(X\)</span> is between a lower (<span class="math inline">\(x_l\)</span>) and an upper (<span class="math inline">\(x_u\)</span>) value can be obtained as:
<span class="math display">\[
P(x_l &lt; X &lt; x_u) = P(X &lt; x_u) - P(X &lt; x_l)
\]</span></p>
<p><img src="images/prob/pnorm_interval.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="area-to-the-right-of-x" class="section level2">
<h2>3. Area to the right of <span class="math inline">\(x\)</span></h2>
<p>The probability to the right of <span class="math inline">\(x\)</span> is one minus the probability to the left of <span class="math inline">\(x\)</span>:
<span class="math display">\[
P(X &gt; x) = 1 - P(X &lt; x)
\]</span></p>
<p><img src="images/prob/pnorm_right.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="symmetry-of-the-normal-distribution" class="section level1">
<h1>Symmetry of the normal distribution</h1>
<p>We now stress an important property of the normal distribution, namely that it is <em><strong>symmetric</strong></em> around the mean.</p>
<p>For simplicity, we will start by discussing the case when <span class="math inline">\(X \sim N(0, 1)\)</span>. For a normally distributed random variable <span class="math inline">\(X\)</span> with mean 0 and standard deviation 1 we have that <span class="math inline">\(P(X &lt; -a) = P(X &gt; a)\)</span>:</p>
<p><img src="images/prob/normal_symmetry.png" width="100%" style="display: block; margin: auto;" /></p>
<p>We will verify this with R. If <span class="math inline">\(X \sim N(0,1)\)</span>, we have that <span class="math inline">\(P(X &lt; -1) = P(X &gt; 1)\)</span>:</p>
<pre class="r"><code># P(X &lt; -1)
pnorm(-1, mean = 0, sd = 1)</code></pre>
<pre><code>## [1] 0.1586553</code></pre>
<pre class="r"><code># P(X &gt; 1)
1 - pnorm(1, mean = 0, sd = 1)</code></pre>
<pre><code>## [1] 0.1586553</code></pre>
<p><br></p>
<p>In the case of a generic mean <span class="math inline">\(\mu\)</span>, the two endpoints will change according to the distance from the mean. Consider <span class="math inline">\(X \sim N(3, 1)\)</span> and let’s focus on <span class="math inline">\(P(X &lt; 2)\)</span>. The value 2 is one below the mean, so the corresponding upper value should be one above the mean, i.e. <span class="math inline">\(P(X &gt; 4)\)</span>.</p>
<p>In general, if the lower endpoint is <span class="math inline">\(a\)</span>, the upper endpoint <span class="math inline">\(b\)</span> is found by:</p>
<ol style="list-style-type: decimal">
<li>Computing the distance from the mean, <span class="math inline">\(dist = \mu - a\)</span></li>
<li>Adding to the mean the distance previously found, <span class="math inline">\(b = \mu + dist = \mu + (\mu - a)\)</span></li>
</ol>
<pre class="r"><code># P(X &lt; a)
pnorm(2, mean = 3, sd = 1)</code></pre>
<pre><code>## [1] 0.1586553</code></pre>
<pre class="r"><code># P(X &gt; b)
1 - pnorm(3 + (3 - 2), mean = 3, sd = 1)</code></pre>
<pre><code>## [1] 0.1586553</code></pre>
<p><br></p>
<p>We conclude this section with an important observation.
The probability that a random variable <span class="math inline">\(X \sim N(0, 1)\)</span> is less than <span class="math inline">\(-a\)</span> <em><strong>or</strong></em> greater than <span class="math inline">\(a\)</span> can be simply computed as twice either of those probabilities because of symmetry:
<span class="math display">\[
P(X &lt; -a) + P(X &gt; a) = 2 \cdot P(X &lt; -a) = 2 \cdot P(X &gt; a)
\]</span></p>
</div>
<div id="the-inverse-problem-quantiles-and-percentiles" class="section level1">
<h1>The inverse problem: quantiles and percentiles</h1>
<p>In this section we will examine the inverse problem to the one of calculating the probability that <span class="math inline">\(X &lt; x\)</span>.</p>
<p>Given a probability <span class="math inline">\(p\)</span>, what’s the value <span class="math inline">\(x\)</span> that cuts to its left a probability of <span class="math inline">\(p\)</span>?</p>
<p><img src="images/prob/normal_quantile.png" width="40%" style="display: block; margin: auto;" /></p>
<p>That value, called the <em><strong><span class="math inline">\(p\)</span>-quantile</strong></em>, is the value <span class="math inline">\(x_p\)</span> for which the lower-tail probability is <span class="math inline">\(p\)</span>:</p>
<p><span class="math display">\[
\text{value }x_p\text{ such that} \qquad P(X \leq x_p) = p
\]</span></p>
<p>Percentiles and quantiles are two words used to express the same idea.
We use <em><strong>percentile</strong></em> when speaking in terms of percentages and <em><strong>quantile</strong></em> when speaking in terms of proportions (or probabilities) between 0 and 1.</p>
<p>The 50th percentile (or <span class="math inline">\(0.5\)</span>-quantile) is the value <span class="math inline">\(x_{0.5}\)</span> that cuts a 0.5 probability to its left. You actually know that the value such that 50% of the observations are lower and 50% are higher is called the median.</p>
<p><br>
In R, you calculate the <span class="math inline">\(p\)</span>-quantile with the function</p>
<pre><code>qnorm(p, mean, sd)</code></pre>
<p>This will return the value <span class="math inline">\(x\)</span> such that <span class="math inline">\(P(X \leq x) = p\)</span>. That value is typically written <span class="math inline">\(x_p\)</span>.</p>
<p><br>
For example, if <span class="math inline">\(X \sim N(0, 1)\)</span>, the value cutting an area of 0.025 to its left is</p>
<pre class="r"><code>qnorm(0.025, 0, 1)</code></pre>
<pre><code>## [1] -1.959964</code></pre>
<p>while that cutting an area of 0.975 to its left is</p>
<pre class="r"><code>qnorm(0.975, 0, 1)</code></pre>
<pre><code>## [1] 1.959964</code></pre>
<p>The <span class="math inline">\(0.025\)</span>-quantile is <span class="math inline">\(x_{0.025} = -1.96\)</span>, and the <span class="math inline">\(0.975\)</span>-quantile is <span class="math inline">\(x_{0.975} = 1.96\)</span>.</p>
</div>
<div id="working-in-standard-units" class="section level1">
<h1>Working in standard units</h1>
<p>Instead of always specifying the mean and the standard deviation of the normal distribution, we can work with a reference normal distribution that has a mean equal to 0 and standard deviation equal to 1. This is known as the <strong>standard normal distribution</strong>.</p>
<div class="yellow">
<p><strong>Standard normal distribution</strong></p>
<p>The standard normal distribution, denoted <span class="math inline">\(Z \sim N(0, 1)\)</span>, is a normal distribution with mean = 0 and standard deviation = 1.</p>
</div>
<p>The R functions <code>dnorm(x, mean, sd)</code> and <code>pnorm(x, mean, sd)</code> assume that mean = 0 and sd = 1 if not provided. In other words, they assume a standard normal distribution by default.</p>
<p>For example, the following two functions return the same output</p>
<pre class="r"><code>dnorm(2)</code></pre>
<pre><code>## [1] 0.05399097</code></pre>
<pre class="r"><code>dnorm(2, mean = 0, sd = 1)</code></pre>
<pre><code>## [1] 0.05399097</code></pre>
<p>and similarly for <code>pnorm()</code>.</p>
<p>In order to transform a value <span class="math inline">\(x\)</span> from a normal distribution with mean = <span class="math inline">\(\mu\)</span> and sd = <span class="math inline">\(\sigma\)</span> to a score on the standard normal scale, we must use the z-score transformation.</p>
<p>The z-score measures distance in terms of the number of standard deviations from the mean:
<span class="math display">\[
z = \frac{x - \mu}{\sigma} \qquad (\text{standard units or } z\text{-}scores)
\]</span></p>
<div class="yellow">
<p><strong>z-score</strong></p>
<p>The z-score of <span class="math inline">\(x\)</span> is the number of standard deviations <span class="math inline">\(x\)</span> is from the mean.</p>
</div>
<p><br></p>
<p>Let <span class="math inline">\(X \sim N(\mu, \sigma)\)</span> and <span class="math inline">\(Z \sim N(0, 1)\)</span>. The following relation holds:
<span class="math display">\[
P(X &lt; x) = P \left( \frac{X - \mu}{\sigma} &lt; \frac{x - \mu}{\sigma} \right) = P(Z &lt; z)
\]</span></p>
<p>This means that the probability, when computed on the original normal distribution or on the standard normal distribution, will be the same as long as you use the z-score of <span class="math inline">\(x\)</span> for the standard normal distribution.</p>
<p><br></p>
<p>Consider the following cases:</p>
<ol style="list-style-type: lower-alpha">
<li>You observe <span class="math inline">\(x = 4.3\)</span> from a <span class="math inline">\(N(3, 2)\)</span> distribution. The z-score is <span class="math inline">\(z = (4.3 - 3) / 2 = 0.65\)</span></li>
<li>You observe <span class="math inline">\(x = 4.3\)</span> from a <span class="math inline">\(N(3, 0.2)\)</span> distribution. The z-score is <span class="math inline">\(z = (4.3 - 3) / 0.2 = 6.5\)</span></li>
</ol>
<p>In case (a), your observed value 4.3 is 0.65 standard deviations away from the mean.
In case (b), the observed value 4.3 is 6.5 standard deviations away from the mean.</p>
<p>Observing a value of 4.3 from a <span class="math inline">\(N(3,2)\)</span> population is very likely, as 68% of the observations are within 1 <span class="math inline">\(\sigma\)</span> of the mean.
However, observing a value of 4.3 from a <span class="math inline">\(N(3,0.2)\)</span> distribution is very unlikely, as almost all the values will be within 3 <span class="math inline">\(\sigma\)</span> of the mean. Such a high z-score provides us with an element of surprise. We might want to inspect that value further as it could be an outlier or a typing error of who has entered the data.</p>
<p>As you can see, z-scores are particularly useful for comparing observations across distributions having a different mean and standard deviation.</p>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>When a histogram shows that a variable’s distribution is symmetric and bell-shaped, we can say that the variable is normally distributed and we can model the distribution with a mathematical curve called the normal density function.</p>
<p>We saw that the normal distribution depends on two parameters that control the centre and spread of the normal density curve:</p>
<ul>
<li>the mean;</li>
<li>the standard deviation.</li>
</ul>
<p>These two parameters make sure that the normal curve can fit histograms that have different centres and spreads.</p>
<p>In other words, if you know that a distribution is normal (shape), then the mean (centre) and standard deviation (spread) tell you everything else about the distribution.</p>
<p>In R, the equation of the normal density curve is given by the function <code>dnorm(x, mean, sd)</code>.</p>
<p>We can use the normal curve to compute the probability of intervals as the area under the curve in that interval.
The function to compute the area under a normal curve to the left of <code>x</code> is <code>pnorm(x, mean, sd)</code>.</p>
<table>
<colgroup>
<col width="54%" />
<col width="45%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Probability</th>
<th align="left">R command</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Probability of observing a value less than or equal <code>x</code></td>
<td align="left"><code>pnorm(x, mean, sd)</code></td>
</tr>
<tr class="even">
<td align="left">Probability of observing a value between <code>xl</code> and <code>xu</code></td>
<td align="left"><code>pnorm(xu, mean, sd) - pnorm(xl, mean, sd)</code></td>
</tr>
<tr class="odd">
<td align="left">Probability of observing a value greater than <code>xu</code></td>
<td align="left"><code>1 - pnorm(xu, mean, sd)</code></td>
</tr>
</tbody>
</table>
<p>The value <span class="math inline">\(x_p\)</span> cutting an area = <span class="math inline">\(p\)</span> to its left is returned by <code>qnorm(p, mean, sd)</code>. This is called the <span class="math inline">\(p\)</span>-quantile of <span class="math inline">\(X\)</span>.</p>
<hr />
</div>
<div id="glossary" class="section level1">
<h1>Glossary</h1>
<ul>
<li><strong>Continuous random variable.</strong> A variable that takes on numerical values determined by a chance process which can have any number of decimals.</li>
<li><strong>Density function.</strong> The function which provides the probability that a random variable is within an interval in terms of the area under that curve between that interval.</li>
<li><strong>Normal distribution.</strong> The probability distribution of a random variable which has a symmetric and bell shaped density curve.</li>
<li><span class="math inline">\(p\)</span>-<strong>quantile.</strong> The <span class="math inline">\(x_p\)</span> value cutting an area = <span class="math inline">\(p\)</span> to its left. In other words, the <span class="math inline">\(x_p\)</span> value such that <span class="math inline">\(P(X \leq x_p) = p\)</span>.</li>
</ul>
<hr />
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<div id="a-test-for-verbal-memory" class="section level2">
<h2>A test for verbal memory</h2>
<p>The Selective Reminding Task (SRT) test is sometimes used to test several aspects of verbal memory. It involves hearing, recalling, and learning 12 presented words.
The scores corresponding to different aspects of verbal memory such as total recall, storage into long-term memory, and so on are combined to give an overall score.
Let <span class="math inline">\(X\)</span> represent the SRT score of a female student in an age group of interest, and suppose that <span class="math inline">\(X \sim N(\mu = 126, \sigma = 10)\)</span>.</p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Find the following probabilities:</p>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(P(X &gt; 140)\)</span></li>
<li><span class="math inline">\(P(120 &lt; X &lt; 133)\)</span></li>
<li><span class="math inline">\(P(X &lt; 119.5)\)</span></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-95" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-95&#39;, &#39;sol-start-95&#39;)"></span>
</div>
<div id="sol-body-95" class="solution-body" style="display: none;">
<pre class="r"><code>mu &lt;- 126
sigma &lt;- 10

# i.
1 - pnorm(140, mu, sigma)</code></pre>
<pre><code>## [1] 0.08075666</code></pre>
<pre class="r"><code># ii.
pnorm(133, mu, sigma) - pnorm(120, mu, sigma)</code></pre>
<pre><code>## [1] 0.4837832</code></pre>
<pre class="r"><code># iii.
pnorm(119.5, mu, sigma)</code></pre>
<pre><code>## [1] 0.2578461</code></pre>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(P(X &gt; 140) = 1 - P(X &lt; 140) = 0.0808\)</span></li>
<li><span class="math inline">\(P(120 &lt; X &lt; 133) = P(X &lt; 133) - P(X &lt; 120) = 0.484\)</span></li>
<li><span class="math inline">\(P(X &lt; 119.5) = 0.258\)</span></li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>What’s the z-score for someone who scored 120 on the SRT test? Also comment on what the z-score means.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-96" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-96&#39;, &#39;sol-start-96&#39;)"></span>
</div>
<div id="sol-body-96" class="solution-body" style="display: none;">
<pre class="r"><code>z &lt;- (120 - mu) / sigma
z</code></pre>
<pre><code>## [1] -0.6</code></pre>
<p>The z-score corresponding to an SRT score of 120 is <span class="math inline">\(z = -0.6\)</span>, telling us that 120 is 0.6 standard deviations below the mean.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>What would the answer to question 2 be for someone who scored 140 on the SRT test?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-97" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-97&#39;, &#39;sol-start-97&#39;)"></span>
</div>
<div id="sol-body-97" class="solution-body" style="display: none;">
<pre class="r"><code>z &lt;- (140 - mu) / sigma
z</code></pre>
<pre><code>## [1] 1.4</code></pre>
<p>The z-score corresponding to an SRT score of 140 is <span class="math inline">\(z = 1.4\)</span>, telling us that 140 is 1.4 standard deviations above the mean.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>A research company wants to use the SRT test to identify study participants with good memory skills. They are going to recruit candidates among the top 15% for the test. What should a participant score in order to be eligible?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-98" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-98&#39;, &#39;sol-start-98&#39;)"></span>
</div>
<div id="sol-body-98" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 1 - (15/100)
qnorm(p, mu, sigma)</code></pre>
<pre><code>## [1] 136.3643</code></pre>
<p>We are asked to find the 85th percentile (0.85-quantile). This is the value <span class="math inline">\(x_{0.85}\)</span> such that <span class="math inline">\(P(X \leq x_{0.85}) = 0.85\)</span>. Using technology we find that <span class="math inline">\(x_{0.85} = 136.4\)</span>.</p>
<p>For a participant to be eligible, they need to score at least 136.4 in the SRT test.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>What would the answer to the previous question be if the company considered the top 10%?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-99" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-99&#39;, &#39;sol-start-99&#39;)"></span>
</div>
<div id="sol-body-99" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 1 - (10/100)
qnorm(p, mu, sigma)</code></pre>
<pre><code>## [1] 138.8155</code></pre>
<p>We are asked to find the 90th percentile (0.9-quantile). This is the value <span class="math inline">\(x_{0.9}\)</span> such that <span class="math inline">\(P(X \leq x_{0.9}) = 0.9\)</span>. Using technology we find that <span class="math inline">\(x_{0.9} = 138.8\)</span>.</p>
<p>For a participant to be eligible, they need to score at least 138.8 in the SRT test.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>A clinic is using the SRT test to check whether a student involved in an accident could have internal head injuries.
The doctors suspect a patient has internal head injuries if their score is too low.
Below what value do 1% of the students’ SRT test scores fall?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-100" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-100&#39;, &#39;sol-start-100&#39;)"></span>
</div>
<div id="sol-body-100" class="solution-body" style="display: none;">
<pre class="r"><code>p &lt;- 1/100
qnorm(p, mu, sigma)</code></pre>
<pre><code>## [1] 102.7365</code></pre>
<p>We are asked to find the 1st percentile (0.01-quantile). This is the value <span class="math inline">\(x_{0.01}\)</span> such that <span class="math inline">\(P(X \leq x_{0.01}) = 0.01\)</span>. Using technology we find that <span class="math inline">\(x_{0.01} = 102.7\)</span>.</p>
<p>When an SRT test is administer to a student who had an accident, the doctors will suspect they have internal head injuries when their score on the SRT test is below 136.4.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>What interval of SRT scores covers the central 90% of students’ test results?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-101" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-101&#39;, &#39;sol-start-101&#39;)"></span>
</div>
<div id="sol-body-101" class="solution-body" style="display: none;">
<p>This will be the range from the 5th to the 95th percentiles:</p>
<pre class="r"><code>qnorm(c(0.05, 0.95), mu, sigma)</code></pre>
<pre><code>## [1] 109.5515 142.4485</code></pre>
<p>We find that 95% of student results on the SRT test are between 109.6 and 142.4.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>And for the central 60% of test results?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-102" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-102&#39;, &#39;sol-start-102&#39;)"></span>
</div>
<div id="sol-body-102" class="solution-body" style="display: none;">
<p>This will be the range from the 20th to the 80th percentiles:</p>
<pre class="r"><code>qnorm(c(0.20, 0.80), mu, sigma)</code></pre>
<pre><code>## [1] 117.5838 134.4162</code></pre>
<p>We find that 60% of student results on the SRT test are between 117.6 and 134.4.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="a-test-for-diabetes" class="section level2">
<h2>A test for diabetes</h2>
<p>A standard test for diabetes is based on measuring glucose levels in blood after a patient has been told to fast for a certain amount of time. For healthy people the mean glucose level after fasting is found to be 5.31 mmol/L with a standard deviation of 0.58 mmol/L.
For untreated diabetics the mean is 11.74 mmol/L, and the standard deviation is 3.50 mmol/L. The distribution of fasting glucose levels in both groups appears to be approximately normally distributed.</p>
<p>To carry out a clinical test based on fasting glucose levels, we need to set a cutoff point, <span class="math inline">\(C\)</span>, so that if the patient’s glucose level after fasting is at least <span class="math inline">\(C\)</span> we say they have diabetes.
If it is lower than the cutoff point, we can say they do not have diabetes. Suppose we use <span class="math inline">\(C = 6.5\)</span>.</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability that a person with diabetes is correctly diagnosed as having diabetes?</p></li>
<li><p>What is the probability that someone without diabetes is correctly diagnosed as not having diabetes?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-103" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-103&#39;, &#39;sol-start-103&#39;)"></span>
</div>
<div id="sol-body-103" class="solution-body" style="display: none;">
<p>Let <span class="math inline">\(X_H \sim N(\mu_H = 5.31, \sigma_H = 0.58)\)</span> be the random variable representing the fasting glucose level for a healthy individual.</p>
<p>Similarly, let <span class="math inline">\(X_D \sim N(\mu_D = 11.74, \sigma_D = 3.50)\)</span> be the random variable representing the fasting glucose level for a diabetic individual.</p>
<pre class="r"><code>mu_healthy &lt;- 5.31
sigma_healthy &lt;- 0.58

mu_diab &lt;- 11.74
sigma_diab &lt;- 3.50</code></pre>
<pre class="r"><code>1 - pnorm(6.5, mu_diab, sigma_diab)</code></pre>
<pre><code>## [1] 0.932822</code></pre>
<pre class="r"><code>pnorm(6.5, mu_healthy, sigma_healthy)</code></pre>
<pre><code>## [1] 0.9799018</code></pre>
<ol style="list-style-type: lower-alpha">
<li><p>The probability that a diabetic is correctly diagnosed as having diabetes is <span class="math inline">\(P(X_D &gt; 6.5) = 1 - P(X_D &lt; 6.5) = 0.933\)</span>.</p></li>
<li><p>The probability that a nondiabetic is correctly diagnosed as not having diabetes is <span class="math inline">\(P(X_H &lt; 6.5) = 0.98\)</span>.</p></li>
</ol>
</div>
<p class="solution-end">
</p>
<p>The probability of correctly diagnosing a patient as having diabetes is called the <em>sensitivity</em> of the test, while the probability of correctly diagnosing that a healthy individual does not have diabetes is called the <em>specificity</em> of the test.
In an ideal situation, we want tests to be both very sensitive (very good at spotting the condition if it is there) and very specific (rarely signalling the presence of the condition if it is not there).
However, with blood glucose levels tests (and many other tests), there is some overlap in fasting glucose levels between the two groups (healthy and diabetic).
Some healthy individuals have higher levels than some diabetics, so our test cannot be both 100% sensitive and 100% specific.</p>
<p><img src="images/prob/normal_test_ideal.png" width="90%" style="display: block; margin: auto;" /></p>
<p><img src="images/prob/normal_test_real.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<ol start="3" style="list-style-type: lower-alpha">
<li><p>What is the sensitivity of the test if we use <span class="math inline">\(C = 5.7\)</span>?</p></li>
<li><p>What is the specificity?</p></li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-104" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-104&#39;, &#39;sol-start-104&#39;)"></span>
</div>
<div id="sol-body-104" class="solution-body" style="display: none;">
<pre class="r"><code>1 - pnorm(5.7, mu_diab, sigma_diab)</code></pre>
<pre><code>## [1] 0.9578006</code></pre>
<pre class="r"><code>pnorm(5.7, mu_healthy, sigma_healthy)</code></pre>
<pre><code>## [1] 0.7493398</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>The sensitivity of the test for a threshold <span class="math inline">\(C = 5.7\)</span> is given by <span class="math inline">\(P(X_D &gt; 5.7) = 1 - P(X_D &lt; 5.7) = 0.958\)</span>.</p></li>
<li><p>The specificity is the probability that a healthy individual is not diagnosed as having diabetes, i.e. <span class="math inline">\(P(X_H &lt; 5.7) = 0.749\)</span>.</p></li>
</ol>
</div>
<p class="solution-end">
</p>
<p>If you look at your answers to (a), (b), (c), and (d), you will see that by making <span class="math inline">\(C\)</span> smaller, we get a more sensitive test that is less specific, whereas by making <span class="math inline">\(C\)</span> large, we get a more specific test that is less sensitive. In deciding what value of <span class="math inline">\(C\)</span> to use, we have to trade off sensitivity for specificity. To do so in a reasonable way, some assessment is required of the relative “costs” of misdiagnosing a diabetic and misdiagnosing a nondiabetic.
Suppose we required 98% sensitivity.</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<ol start="5" style="list-style-type: lower-alpha">
<li><p>What is the value of <span class="math inline">\(C\)</span> giving a sensitivity of 0.98?</p></li>
<li><p>How specific is the test when <span class="math inline">\(C\)</span> has this value?</p></li>
</ol>
<!-- g. What is the probability that a randomly chosen nondiabetic has a higher fasting glucose level than a random untreated diabetic? -->
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-105" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-105&#39;, &#39;sol-start-105&#39;)"></span>
</div>
<div id="sol-body-105" class="solution-body" style="display: none;">
<pre class="r"><code>Cres &lt;- qnorm(1 - 0.98, mu_diab, sigma_diab)
Cres</code></pre>
<pre><code>## [1] 4.551879</code></pre>
<pre class="r"><code>pnorm(Cres, mu_healthy, sigma_healthy)</code></pre>
<pre><code>## [1] 0.09558844</code></pre>
<ol start="5" style="list-style-type: lower-alpha">
<li><p>The question asks us to compute the 2nd percentile: <span class="math inline">\(P(X_D &lt; C) = 0.02\)</span>. We find that <span class="math inline">\(C = 4.552\)</span></p></li>
<li><p>The specificity at <span class="math inline">\(C = 4.552\)</span> is <span class="math inline">\(P(X_H &lt; C) = P(X_H &lt; 4.552) = 0.0956\)</span></p></li>
</ol>
<!-- ```{r} -->
<!-- 1 - pnorm(0, mu_healthy - mu_diab, sqrt(sigma_healthy^2 + sigma_diab^2)) -->
<!-- ``` -->
</div>
<p class="solution-end">
</p>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
