<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Categorical predictors and assumptions</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>




<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">1/2: Simple linear regression</a>
    </li>
    <li>
      <a href="03_slr_model_fit.html">1/3: Model Fit, Standardized Coefficients</a>
    </li>
    <li>
      <a href="04_slr_assumptions.html">1/4: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="05_slr_writeup.html">1/5: Writing-up</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">1/7: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">1/8: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">1/10: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="11_anova.html">2/1: ANOVA</a>
    </li>
    <li>
      <a href="11_anova.html">2/2: ANOVA (again)</a>
    </li>
    <li>
      <a href="12_factorial_anova.html">2/3: 2x2 ANOVA</a>
    </li>
    <li>
      <a href="13_multiplecomp.html">2/4: Multiple Comparisons</a>
    </li>
    <li class="dropdown-header">2/5: No exercises</li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="14_bootstrap_reg.html">2/7: Bootstrap</a>
    </li>
    <li>
      <a href="15_binary_logistic.html">2/8: Binary Logistic Regression</a>
    </li>
    <li>
      <a href="16_more_about_logistic.html">2/9: More About Logistic Regression</a>
    </li>
    <li>
      <a href="17_power_regression.html">2/10: Sample Size and Power Analysis</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Categorical predictors and assumptions</h1>

</div>


<div class="green">
<p>Be sure to check the <a href="03_slr_model_fit.html"><strong>solutions to last week’s exercises</strong></a>.<br>You can still ask any questions about previous weeks’ materials if things aren’t clear!</p>
</div>
<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand the meaning of model coefficients in the case of a binary predictor.</li>
<li>Be able to state the assumptions underlying a linear model.</li>
<li>Understand how to assess if a fitted model satisfies the linear model assumptions.</li>
<li>Understand how to use transformations when the model violates assumptions.</li>
</ol>
</div>
<div id="research-question" class="section level1">
<h1>Research question</h1>
<p><em>Do distracting colours influence game completion time?</em></p>
<p>A group of students wanted to answer the above research question. To do so, they designed a standard computerized game and a second version with distracting colours. Time to completion and type of game played were recorded for each study participant.
See the data description below for more information.</p>
<div class="optional-begin">
Data: perfection.csv. Click the plus to expand →<span id="opt-start-45" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-45&#39;, &#39;opt-start-45&#39;)"></span>
</div>
<div id="opt-body-45" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/perfection.csv">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>A group of students wanted to investigate the impact of colour distracters on game completion time.
They hypothesized a slower completion time for those playing a game with distracting colours, as a consequence of the widely known <em>Stroop effect</em> <span class="citation">(<a href="#ref-Stroop1935" role="doc-biblioref">Stroop 1935</a>)</span>.</p>
<p>The students created two computer versions of the Perfection game.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
In one version of the computerised game, the “standard” game type, all pegs and shapes would be of the same colour.
In the other version of the game, the “colour” game type, pegs and shapes did not have matching colours, hence there was a colour distracter effect.
The task was to click and drag each peg to the space with the matching shape.</p>
<p>They randomly recruited 40 students from the same university. Half were randomly assigned to the standard game and the other half to the colour distracter version.
All participants would play in similar conditions: same location and similar background noise to control for possible distractions.</p>
<div class="figure" style="text-align: center"><span id="fig:dc-perfection-image"></span>
<img src="images/perfection.png" alt="Electronic Perfection game with and without colour distracters. The instructions for the game were to click and drag each peg to the space with the matching shape." width="60%" />
<p class="caption">
Figure 1: Electronic Perfection game with and without colour distracters. The instructions for the game were to click and drag each peg to the space with the matching shape.
</p>
</div>
<p>The following variables were collected:</p>
<ul>
<li><code>student_id</code>: Identifier for each student</li>
<li><code>type</code>: game type: Standard or Colour</li>
<li><code>time</code>: time (in seconds) from the start of the game to completion</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data, provided by <span class="citation"><a href="#ref-Kuiper2012" role="doc-biblioref">Kuiper and Sklar</a> (<a href="#ref-Kuiper2012" role="doc-biblioref">2012</a>)</span>, are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
student_id
</th>
<th style="text-align:center;">
type
</th>
<th style="text-align:center;">
time
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
Standard
</td>
<td style="text-align:center;">
38
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
Colour
</td>
<td style="text-align:center;">
36
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
Colour
</td>
<td style="text-align:center;">
42
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
Standard
</td>
<td style="text-align:center;">
35
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
Standard
</td>
<td style="text-align:center;">
32
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
Colour
</td>
<td style="text-align:center;">
37
</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
</div>
<div id="data-exploration" class="section level1">
<h1>Data exploration</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read the Perfection game data into R and name the data frame <code>perfection</code>.</p>
<p>Check for the correct encoding of all variables — that is, categorical variables should be factors and numeric variables should be numeric.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-46" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-46&#39;, &#39;sol-start-46&#39;)"></span>
</div>
<div id="sol-body-46" class="solution-body" style="display: none;">
<pre class="r"><code>library(tidyverse)

perfection &lt;- read_csv(&#39;https://uoepsy.github.io/data/perfection.csv&#39;)
head(perfection)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   student_id type      time
##        &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
## 1          1 Standard    38
## 2          2 Colour      36
## 3          3 Colour      42
## 4          4 Standard    35
## 5          5 Standard    32
## 6          6 Colour      37</code></pre>
<p>Game type is a categorical variable but is encoded as a character (<code>&lt;chr&gt;</code>) variable rather than a factor.
Let’s fix it:</p>
<pre class="r"><code>perfection &lt;- perfection %&gt;%
  mutate(type = as.factor(type))

head(perfection)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   student_id type      time
##        &lt;dbl&gt; &lt;fct&gt;    &lt;dbl&gt;
## 1          1 Standard    38
## 2          2 Colour      36
## 3          3 Colour      42
## 4          4 Standard    35
## 5          5 Standard    32
## 6          6 Colour      37</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Identify the units, the population to which conclusions can be generalised to, the explanatory variable and the response variable. Also classify the variables according to their type.</p>
<p>Is this study an experiment or an observational study?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-47" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-47&#39;, &#39;sol-start-47&#39;)"></span>
</div>
<div id="sol-body-47" class="solution-body" style="display: none;">
<p>Units: each student.</p>
<p>Population: set of all students at this university who would be willing to be part of the study.</p>
<p>Explanatory variable: type of game (standard or with a colour distracter). Type: categorical.</p>
<p>Response variable: the completion time (in seconds). Type: numeric.</p>
<p>This study is an experiment, since students were randomly allocated to one of the two types of games.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Display and describe the marginal distribution of game type.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-48" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-48&#39;, &#39;sol-start-48&#39;)"></span>
</div>
<div id="sol-body-48" class="solution-body" style="display: none;">
<p>Type of game played is a categorical variable. We visualise it, for example, with a bar plot:</p>
<pre class="r"><code>ggplot(perfection, aes(x = type)) +
  geom_bar()</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-4-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>perfection %&gt;%
  group_by(type) %&gt;%
  summarise(n = n())</code></pre>
<pre><code>## # A tibble: 2 x 2
##   type         n
##   &lt;fct&gt;    &lt;int&gt;
## 1 Colour      20
## 2 Standard    20</code></pre>
<div class="int">
<p>The forty students were evenly split at random to take either the standard game or the one with distracting colours.
Each group consisted of 20 students.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Display and describe the marginal distribution of completion times.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-49" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-49&#39;, &#39;sol-start-49&#39;)"></span>
</div>
<div id="sol-body-49" class="solution-body" style="display: none;">
<pre class="r"><code>ggplot(perfection, aes(x = time)) +
  geom_density() +
  geom_boxplot(width = 1/100)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-5-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>perfection %&gt;%
  summarise(M = mean(time),
            SD = sd(time))</code></pre>
<pre><code>## # A tibble: 1 x 2
##       M    SD
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  36.8  3.71</code></pre>
<div class="int">
<p>The distribution completion times appears to be unimodal, centred at approximately 37 seconds, with a SD of roughly 4 seconds.</p>
<p>The boxplot does not highlight any outliers.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Display and describe the relationship between game type and completion times.</p>
<p>Does it look like the groups have equal mean or spread? Are there any extreme observations?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-50" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-50&#39;, &#39;sol-start-50&#39;)"></span>
</div>
<div id="sol-body-50" class="solution-body" style="display: none;">
<p>There are many correct way to investigate the distribution of completion times by group.</p>
<p><strong>Option 1: Boxplots by group</strong></p>
<pre class="r"><code>ggplot(perfection, aes(x = type, y = time)) +
  geom_boxplot()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:perfection-boxplots"></span>
<img src="04_slr_assumptions_files/figure-html/perfection-boxplots-1.png" alt="Boxplots of competion times by game type." width="60%" />
<p class="caption">
Figure 2: Boxplots of competion times by game type.
</p>
</div>
<p><strong>Option 2: Dotplots by group</strong></p>
<pre class="r"><code>ggplot(perfection, aes(x = type, y = time)) +
  geom_dotplot(binaxis = &#39;y&#39;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:perfection-dotplots"></span>
<img src="04_slr_assumptions_files/figure-html/perfection-dotplots-1.png" alt="Dotplots of competion times by game type." width="60%" />
<p class="caption">
Figure 3: Dotplots of competion times by game type.
</p>
</div>
<p>or</p>
<pre class="r"><code>ggplot(perfection, aes(x = time )) +
  geom_dotplot() + 
  facet_grid(type ~ .)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-6-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p><strong>Option 3: Histograms by group</strong></p>
<pre class="r"><code>ggplot(perfection, aes(x = time)) +
  geom_histogram(binwidth = 1, color = &#39;white&#39;) +
  facet_grid(rows = vars(type))</code></pre>
<div class="figure" style="text-align: center"><span id="fig:perfection-histograms"></span>
<img src="04_slr_assumptions_files/figure-html/perfection-histograms-1.png" alt="Histograms of competion times for each game type." width="60%" />
<p class="caption">
Figure 4: Histograms of competion times for each game type.
</p>
</div>
<p><strong>Option 4: Violin plots by group</strong></p>
<p>The following code creates two violin plots, one for each group, with the group means denoted by red points:</p>
<pre class="r"><code>ggplot(perfection, aes(x = type, y = time)) +
  geom_violin() +
  stat_summary(fun = mean, color = &#39;red&#39;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:perfection-violins"></span>
<img src="04_slr_assumptions_files/figure-html/perfection-violins-1.png" alt="Histograms of competion times for each game type." width="60%" />
<p class="caption">
Figure 5: Histograms of competion times for each game type.
</p>
</div>
<p>And many other options…</p>
<p><br>
The summary statistics by group can be computed as follows:</p>
<pre class="r"><code>stats_time &lt;- perfection %&gt;%
  group_by(type) %&gt;%
  summarise(n = n(),
            mean_time = mean(time), 
            sd_time = sd(time))

stats_time</code></pre>
<pre><code>## # A tibble: 2 x 4
##   type         n mean_time sd_time
##   &lt;fct&gt;    &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 Colour      20      38.1    3.65
## 2 Standard    20      35.6    3.39</code></pre>
<p>The summary statistics of completion time by group are as follows:</p>
<table>
<thead>
<tr class="header">
<th align="left">Group Type</th>
<th align="left">Summary statistics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Colour distracter</td>
<td align="left"><span class="math inline">\(n_{C} = 20\)</span>, <span class="math inline">\(\bar y_C = 38.10\)</span>, <span class="math inline">\(s_C = 3.65\)</span></td>
</tr>
<tr class="even">
<td align="left">Standard group</td>
<td align="left"><span class="math inline">\(n_{S} = 20\)</span>, <span class="math inline">\(\bar y_S = 35.55\)</span>, <span class="math inline">\(s_S = 3.39\)</span></td>
</tr>
</tbody>
</table>
<p>For the write-up let’s focus, for example, on Figures <a href="#fig:perfection-boxplots">2</a> and <a href="#fig:perfection-dotplots">3</a>. We could write:</p>
<div class="int">
<p>The distribution of game completion times is fairly symmetric and bell-shaped in both groups, as highlighted by the dotplots in Figure <a href="#fig:perfection-dotplots">3</a>.
Furthermore, the spread (standard deviation) of the two distributions appears to be similar.</p>
<p>The boxplots in Figure <a href="#fig:perfection-boxplots">2</a> do not highlight any outliers. They suggest a higher mean completion time in the colour distracter group (<span class="math inline">\(\bar y_C = 38.10\)</span> s) than the standard group (<span class="math inline">\(\bar y_S = 35.55\)</span> s). The standard deviation of completion time in the colour distracter group (<span class="math inline">\(s_C = 3.65\)</span> s) is similar to that in the standard group (<span class="math inline">\(s_S = 3.39\)</span> s).</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-specification-and-fitting" class="section level1">
<h1>Model specification and fitting</h1>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>The researchers hope to determine if distracting colours could impact response times when playing a computerised version of the Perfection game.</p>
<p>Using a two-sided alternative, write out in words and in symbols appropriate null and alternative hypothesis for the research question of interest.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-51" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-51&#39;, &#39;sol-start-51&#39;)"></span>
</div>
<div id="sol-body-51" class="solution-body" style="display: none;">
<p>Let <span class="math inline">\(\mu_C\)</span> represent the true mean response time of the colour group and <span class="math inline">\(\mu_S\)</span> the true mean response time of the standard group.</p>
<ul>
<li><p>Null hypothesis: <span class="math inline">\(H_0: \mu_C = \mu_S\)</span> (the mean completion time for the colour distracter game is equal to the mean completion time for the standard game).</p></li>
<li><p>Alternative hypothesis: <span class="math inline">\(H_0: \mu_C \neq \mu_S\)</span> (the mean completion time for the colour distracter game is not equal to the mean completion time for the standard game).</p></li>
</ul>
<p><br>
Equivalently, you could have specified:</p>
<ul>
<li><p>Null hypothesis: <span class="math inline">\(H_0: \mu_C - \mu_S = 0\)</span> (the difference in mean completion time between the colour distracter game and the standard game is zero).</p></li>
<li><p>Alternative hypothesis: <span class="math inline">\(H_0: \mu_C - \mu_S \neq 0\)</span> (the difference in mean completion time between the colour distracter game and the standard game is different from zero).</p></li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Using the <code>t.test()</code> function, perform a statistical test against the null hypothesis specified above.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-52" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-52&#39;, &#39;sol-start-52&#39;)"></span>
</div>
<div id="sol-body-52" class="solution-body" style="display: none;">
<p>First, we need to check if the two samples come from populations having the same variance:</p>
<pre class="r"><code>var.test(time ~ type, data = perfection)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  time by type
## F = 1.1592, num df = 19, denom df = 19, p-value = 0.7508
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.4588131 2.9285830
## sample estimates:
## ratio of variances 
##           1.159169</code></pre>
<div class="int">
<p>We performed an F-test against the null of equal population variances (<span class="math inline">\(F(19, 19) = 1.16, p = 0.75\)</span>, two-sided).</p>
<p>The sample results do not provide sufficient evidence to reject the null hypothesis of equal population variances.</p>
</div>
<p>In light of the previous test results we will tell R to perform a pooled t-test by saying that the variances are equal with <code>var.equal = TRUE</code>:</p>
<pre class="r"><code>t_res &lt;- t.test(time ~ type, data = perfection, var.equal = TRUE)
t_res</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  time by type
## t = 2.2862, df = 38, p-value = 0.02791
## alternative hypothesis: true difference in means between group Colour and group Standard is not equal to 0
## 95 percent confidence interval:
##  0.2920254 4.8079746
## sample estimates:
##   mean in group Colour mean in group Standard 
##                  38.10                  35.55</code></pre>
<div class="int">
<p>We performed a two-sample t-test against the null hypothesis of equal mean time to complete the colour distracter game and standard game.</p>
<p>At the 5% significance level, the observed difference in mean completion times between the colour distracter and standard game is significantly different from 0 (<span class="math inline">\(t(38) = 2.29\)</span>, <span class="math inline">\(p = 0.028\)</span>, two-sided).</p>
<p>The sample data provide strong evidence that, on average, the time taken to complete the game with distracting colours is different from the standard game.
As the t-statistic is positive (2.29), we can also say that the colour distracter game had a significantly higher average completion time than the standard game.</p>
</div>
<p>To comment on the magnitude of this observed difference in the population means we must resort to the confidence interval: <span class="math inline">\([0.29, 4.81]\)</span>.</p>
<div class="int">
<p>We are 95% confident that participants playing the colour distracter game take between 0.29 and 4.81 seconds longer to complete the game, on average, than those playing the standard game.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Using the linear model function, <code>lm()</code>, fit the following linear model to the Perfection game data:
<span class="math display">\[
Time = \beta_0 + \beta_1 \ Type + \epsilon
\]</span></p>
<p>Write down the equation of the fitted line.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-53" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-53&#39;, &#39;sol-start-53&#39;)"></span>
</div>
<div id="sol-body-53" class="solution-body" style="display: none;">
<pre class="r"><code>mdl_perf &lt;- lm(time ~ 1 + type, data = perfection)
summary(mdl_perf)</code></pre>
<pre><code>## 
## Call:
## lm(formula = time ~ 1 + type, data = perfection)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.100 -2.550  0.175  2.038  7.900 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   38.1000     0.7887  48.308   &lt;2e-16 ***
## typeStandard  -2.5500     1.1154  -2.286   0.0279 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.527 on 38 degrees of freedom
## Multiple R-squared:  0.1209, Adjusted R-squared:  0.09778 
## F-statistic: 5.227 on 1 and 38 DF,  p-value: 0.02791</code></pre>
<p>The fitted model is:
<span class="math display">\[
\widehat{Time} = 38.1 - 2.55 \ Type
\]</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>At the 5% significance level, are the regression coefficients significantly different from zero?</p>
<p>Does the model explain a significant fraction of the variability in completion times?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-54" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-54&#39;, &#39;sol-start-54&#39;)"></span>
</div>
<div id="sol-body-54" class="solution-body" style="display: none;">
<p>At the 5% significance level, both the intercept (<span class="math inline">\(t(38) = 48.31, p &lt; .001\)</span>, two-sided) and the slope (<span class="math inline">\(t(38) = -2.29, p = 0.028\)</span>, two-sided) are significantly different from zero.</p>
<p>The F-statistic for model utility, in the case of simple linear regression, is simply the square t-statistic for the slope.
The model involving game type as a predictor explains a significant amount of the variability in the response (<span class="math inline">\(F(1,38) = 5.23, p = 0.028\)</span>).
That is, type of game played is a significant predictor of game completion time.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Do you notice any similarities between the results of the two-sample t-test (performed via <code>t.test()</code>) and those of the linear model fitted via <code>lm()</code>?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-55" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-55&#39;, &#39;sol-start-55&#39;)"></span>
</div>
<div id="sol-body-55" class="solution-body" style="display: none;">
<p>Consider the again the <code>t.test()</code> output and the <code>lm()</code> output:</p>
<pre class="r"><code>t_res</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  time by type
## t = 2.2862, df = 38, p-value = 0.02791
## alternative hypothesis: true difference in means between group Colour and group Standard is not equal to 0
## 95 percent confidence interval:
##  0.2920254 4.8079746
## sample estimates:
##   mean in group Colour mean in group Standard 
##                  38.10                  35.55</code></pre>
<pre class="r"><code>summary(mdl_perf)</code></pre>
<pre><code>## 
## Call:
## lm(formula = time ~ 1 + type, data = perfection)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.100 -2.550  0.175  2.038  7.900 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   38.1000     0.7887  48.308   &lt;2e-16 ***
## typeStandard  -2.5500     1.1154  -2.286   0.0279 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.527 on 38 degrees of freedom
## Multiple R-squared:  0.1209, Adjusted R-squared:  0.09778 
## F-statistic: 5.227 on 1 and 38 DF,  p-value: 0.02791</code></pre>
<p>In the t-test, <code>mean in group Colour</code> = 38.10 corresponds to the estimated intercept of the linear model, <span class="math inline">\(\hat \beta_0 = 38.10\)</span>. That is, <span class="math display">\[\bar y_C = \hat \beta_0\]</span></p>
<p>In the t-test, <code>mean in group Standard</code> = 35.55 corresponds to the estimated intercept plus slope in the linear model:
<span class="math display">\[
\begin{matrix}
35.55 &amp;=&amp; 38.10 &amp;+&amp; (-2.55) \\
\bar y_S &amp;=&amp; \hat \beta_0 &amp;+&amp; \hat \beta_1 \\
\bar y_S &amp;=&amp; \bar y_C &amp;+&amp; (\bar y_S - \bar y_C)
\end{matrix}
\]</span></p>
<p>This means that, in the fitted model <span class="math inline">\(\hat y = \hat \beta_0 + \hat \beta_1 x\)</span>, the predictor <span class="math inline">\(x = 1\)</span> denotes the standard group and <span class="math inline">\(x = 0\)</span> denotes the colour distracter group:
<span class="math display">\[
\begin{aligned}
x = 0: \qquad &amp;\hat y = \hat \beta_0 + \hat \beta_1 \times 0 = \hat \beta_0\\
x = 1: \qquad &amp;\hat y = \hat \beta_0 + \hat \beta_1 \times 1 = \hat \beta_0 + \hat \beta_1 
\end{aligned}
\]</span></p>
<div class="yellow">
<p>When dealing with a factor, R selects <strong>the first level in alphabetical order</strong> to be the <strong>reference level</strong> and <span class="math inline">\(\hat \beta_0\)</span> predicts the group mean of the reference level.</p>
<p>To do so, R internally denotes the two groups by a binary indicator variable <span class="math inline">\(x\)</span>. It can take only two possible values: zero or one. When <span class="math inline">\(x=0\)</span>, we are dealing with the reference group, while when <span class="math inline">\(x = 1\)</span> we are dealing with the other group.</p>
<p>The estimated slope <span class="math inline">\(\hat \beta_1\)</span> represents the predicted difference in means between the other group and the reference group.</p>
<p>Hence, testing if <span class="math inline">\(\mu_S - \mu_C = 0\)</span> is equivalent to testing if <span class="math inline">\(\beta_1 = 0\)</span>.</p>
</div>
<p>The <code>t-test</code> statistic, and the <code>lm()</code> t-statistic are equivalent in absolute value.
The p-value is identical.
Furthermore, the <code>lm()</code> F-statistic, 5.227, is the square of t-statistic, and the p-value is also identical.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Interpret the intercept and slope of the fitted regression model.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-56" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-56&#39;, &#39;sol-start-56&#39;)"></span>
</div>
<div id="sol-body-56" class="solution-body" style="display: none;">
<p>Intercept</p>
<div class="int">
<p>The estimated average completion time for those playing the colour distracter game is 38.10 seconds.</p>
</div>
<p>Slope</p>
<div class="int">
<p>The estimated difference in average completion times between those playing the standard game and the colour distracter one is -2.55 seconds. As the difference is negative, the colour distracter game has a higher estimated average completion time.</p>
<p>Equivalently, those playing the standard game will take on average 2.55 seconds less than those playing the colour distracter game.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="assumptions-check" class="section level1">
<h1>Assumptions check</h1>
<p>The test statistics reported in the model results are based on a series of assumptions. If these assumptions are not satisfied, the results will not hold.</p>
<p>You can remember the four assumptions by memorising the acronym LINE:</p>
<ul>
<li>L - Linearity</li>
<li>I - Independence</li>
<li>N - Normality</li>
<li>E - Equal variance</li>
</ul>
<p>If at least one of these assumptions does not hold, say N - Normality, you might be reporting a LIE.</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the linearity assumption.</p>
<p><em><strong>Hint:</strong> An equivalent way to assess this is to check that the errors have a mean of zero. That is, there is no pattern left in the residuals as the systematic trend has entirely been captured by the linear model.</em></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-57" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-57&#39;, &#39;sol-start-57&#39;)"></span>
</div>
<div id="sol-body-57" class="solution-body" style="display: none;">
<p>As usual, there are multiple equivalent ways to check this. Below are a couple of possibilities.</p>
<p>Some useful quantities:</p>
<pre class="r"><code>perfection_check &lt;- perfection %&gt;%
  mutate(
    time_hat = predict(mdl_perf),
    resid = time - time_hat,
  )</code></pre>
<p>Residuals vs fitted values:</p>
<pre class="r"><code>plot(mdl_perf, 1)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-13-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>or:</p>
<pre class="r"><code>ggplot(perfection_check, aes(x = time_hat, group = type, y = resid)) +
  geom_point(alpha = 0.5)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Residuals vs explanatory variable:</p>
<pre class="r"><code>ggplot(perfection_check, aes(x = type, y = resid)) +
  geom_point(alpha = 0.5)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-15-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Boxplot of residuals vs fitted values:</p>
<pre class="r"><code>ggplot(perfection_check, aes(x = time_hat, group = type, y = resid)) +
  geom_boxplot()</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-16-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Boxplot of residuals vs explanatory variables:</p>
<pre class="r"><code>ggplot(perfection_check, aes(x = type, y = resid)) +
  geom_boxplot()</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-17-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p><br>
Any of the above plots can be used to say:</p>
<div class="int">
<p>The residuals appear to be randomly scattered around zero in both groups, without showing any pattern with respect to the fitted values. Hence, there is no sign of violation of the zero-mean assumption.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the independent errors assumption.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-58" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-58&#39;, &#39;sol-start-58&#39;)"></span>
</div>
<div id="sol-body-58" class="solution-body" style="display: none;">
<p>A plot of the residuals against the fitted values should not show any patterns or clumps. The values should appear as being randomly scattered.</p>
<p>If there was a clear pattern, for example many consecutive points going upwards or downwards, we might have dependence of one observation from the previous ones.
In the case of a categorical predictor, we do not want one group systematically lower or higher than the other.</p>
<p>Let’s inspect the plot created in the previous question:</p>
<pre class="r"><code>plot(mdl_perf, which = 1)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-18-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>We might say:</p>
<div class="int">
<p>The diagnostic plots of the residuals against the fitted values does not highlight any sign of violation of the independence of errors assumption.</p>
<p>The residuals appear to be randomly scattered with no clumps or patterns.</p>
</div>
<div class="optional-begin">
Observations over time. Click the plus to expand →<span id="opt-start-59" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-59&#39;, &#39;opt-start-59&#39;)"></span>
</div>
<div id="opt-body-59" class="optional-body" style="display: none;">
<p>The most common violation of this assumption happens when we have data collected over time.</p>
<p>In this case a plot of the residuals against time should show no pattern, otherwise we would be in the presence of correlated errors.
That is, knowing the value at time <span class="math inline">\(t\)</span> will let you predict the value at time <span class="math inline">\(t+1\)</span>.</p>
<pre class="r"><code>ggplot(perfection_check, aes(x = seq_along(resid), y = resid)) +
  geom_line() +
  geom_point() +
  labs(x = &#39;Index&#39;, y = &#39;Residuals&#39;)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-19-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Where the function <code>seq_along()</code> returns, for each element its index:</p>
<pre class="r"><code>y &lt;- c(10, 6, 12, 5)
seq_along(y)</code></pre>
<pre><code>## [1] 1 2 3 4</code></pre>
<p>The plot above does not highlight any signs of correlations among the residuals.</p>
<p><br>
Another possible check is to plot the residuals against those same residuals but offset by one time position.</p>
<p>Depending on the data, violation of this assumption might need more advanced tools that not covered in this course.</p>
<p><br>
We can also test for autocorrelation using the Durbin-Watson test from the <code>car</code> library:</p>
<pre class="r"><code>library(car)
durbinWatsonTest(mdl_perf)</code></pre>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1      0.05821787      1.805711   0.534
##  Alternative hypothesis: rho != 0</code></pre>
<div class="int">
<p>We performed a Durbin-Watson test against the null hypothesis of no correlation (<span class="math inline">\(DQ = 1.80\)</span>, <span class="math inline">\(p = 0.522\)</span>, two-sided).
The sample results do not provide sufficient evidence to reject the null hypothesis of no autocorrelation</p>
</div>
</div>
<p class="optional-end">
</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the normality of the errors assumption.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-60" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-60&#39;, &#39;sol-start-60&#39;)"></span>
</div>
<div id="sol-body-60" class="solution-body" style="display: none;">
<p>Let’s create a histogram of the residuals, using 15 breaks of the x-axis:</p>
<pre class="r"><code>hist(residuals(mdl_perf), breaks = 15)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-22-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Note that the distribution of the residuals has zero mean. We don’t see any significant departure from normality by inspecting the histogram. However, it is difficult to judge normality from histograms with so few observations.</p>
<p>Normal quantile plots are a more informative technique for assessing normality. Departures from a linear trend in such plots indicate a lack of normality.</p>
<pre class="r"><code>plot(mdl_perf, which = 2)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-23-1.png" width="60%" style="display: block; margin: auto;" />
The plot above does not highlight any substantial departure from normality.</p>
<p>A more formal test for normality is the Shapiro-Wilk test against the null hypothesis that the sample comes from a normal distribution:</p>
<pre class="r"><code>shapiro.test(residuals(mdl_perf))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(mdl_perf)
## W = 0.98958, p-value = 0.9691</code></pre>
<p>We could write up the results as follows,</p>
<div class="int">
<p>The distribution of the residuals appears reasonably symmetric and bell-shaped. The normal quantile plot follows a linear pattern and does not highlight any substantial skew or departure from normality.</p>
<p>Furthermore, we performed a Shapiro-Wilks test against the null hypothesis that the residuals come from a normal population.
The test-statistic <span class="math inline">\(W = 0.99\)</span> leads to a p-value of 0.97. The large p-value means that we do not have sufficient evidence to reject the null hypothesis that the residuals came from a normal population.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 15
</div>
<div class="question-body">
<p>Check if the fitted model satisfies the equal variance assumption.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-61" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-61&#39;, &#39;sol-start-61&#39;)"></span>
</div>
<div id="sol-body-61" class="solution-body" style="display: none;">
<p>The vertical spread of the residuals should roughly be the same everywhere.</p>
<p>We can visually assess it by plotting the Pearson residuals against the fitted values:</p>
<pre class="r"><code>residualPlot(mdl_perf)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-25-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>As the residuals can be positive or negative, we can make it easier to assess equal spread by improving the “resolution” of the points.
We can make all residuals positive by discarding the sign (take the absolute value), and then take the square root to make them closer to each other.
A plot of <span class="math inline">\(\sqrt{|\text{Standardized residuals}|}\)</span> against the fitted values is shown below:</p>
<pre class="r"><code>plot(mdl_perf, which = 3)</code></pre>
<p><img src="04_slr_assumptions_files/figure-html/unnamed-chunk-26-1.png" width="60%" style="display: block; margin: auto;" />
The plot above has the points much closer to each other, and all above 0. The spread of the two groups appears pretty similar, and the line connecting the two point clouds seems to be flat (as it should be if the spread was constant).</p>
<p>We can also resort to a more formal statistical test against the null hypothesis of equal variance (homoscedasticity).
The Breusch-Pagan test is implemented via the <code>ncvTest</code> (non constant variance) function from the <code>car</code> package:</p>
<pre class="r"><code>ncvTest(mdl_perf)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.1086857, Df = 1, p = 0.74165</code></pre>
<div class="int">
<p>The spread of the standardized residuals appears to be constant as the fitted values vary.</p>
<p>We performed a Breusch-Pagan test against the null hypothesis of constant variance (<span class="math inline">\(\chi^2(1) = 0.11, p = 0.74\)</span>).
At the 5% significance level, the large p-value (0.74) indicates that the sample results do not provide sufficient evidence to reject the null hypothesis that the errors have constant variance.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Kuiper2012" class="csl-entry">
Kuiper, Shonda, and Jeff Sklar. 2012. <em>Practicing Statistics: Guided Investigations for the Second Course</em>. Pearson Higher Ed.
</div>
<div id="ref-Stroop1935" class="csl-entry">
Stroop, J Ridley. 1935. <span>“Studies of Interference in Serial Verbal Reactions.”</span> <em>Journal of Experimental Psychology</em> 18 (6): 643–62.
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>
Perfection is a popular game in which a person is expected to place an assortment of shaped pegs into the matching spaces.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
