<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Writing-up</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">1/2: Simple linear regression</a>
    </li>
    <li>
      <a href="03_slr_model_fit.html">1/3: Model Fit, Standardized Coefficients</a>
    </li>
    <li>
      <a href="04_slr_assumptions.html">1/4: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="05_slr_writeup.html">1/5: Writing-up</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">1/7: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">1/8: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">1/10: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="11_anova.html">2/1: ANOVA</a>
    </li>
    <li>
      <a href="11_anova.html">2/2: ANOVA (again)</a>
    </li>
    <li>
      <a href="12_factorial_anova.html">2/3: 2x2 ANOVA</a>
    </li>
    <li>
      <a href="13_multiplecomp.html">2/4: Multiple Comparisons</a>
    </li>
    <li class="dropdown-header">2/5: No exercises</li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="14_bootstrap_reg.html">2/7: Bootstrap</a>
    </li>
    <li>
      <a href="15_binary_logistic.html">2/8: Binary Logistic Regression</a>
    </li>
    <li>
      <a href="16_more_about_logistic.html">2/9: More About Logistic Regression</a>
    </li>
    <li>
      <a href="17_power_regression.html">2/10: Sample Size and Power Analysis</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Writing-up</h1>

</div>


<div class="green">
<p>Be sure to check the <a href="04_slr_assumptions.html"><strong>solutions to last week’s exercises</strong></a>.<br>You can still ask any questions about previous weeks’ materials if things aren’t clear!</p>
</div>
<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Understand the difference between outliers and influential points.</li>
<li>Understand and apply methods to detect outliers and influential points.</li>
<li>Comment on the issues of correlation vs causation and generalisability of the sample results.</li>
<li>Run a full simple regression analysis from start to finish and to correctly interpret the results.</li>
</ol>
</div>
<div id="research-question" class="section level1">
<h1>Research question</h1>
<p>A group of researchers is interested in the relationship between the reaction time taken by people to identify whether two 3D images display the same object or not, and the rotation angle at which one of the two objects is presented.</p>
<p>Consider the following data containing the reaction times (in milliseconds) it took a sample of 100 people to identify whether two 3D objects were the same or not, for different rotation angles between 0 and 200 degrees.</p>
<div class="optional-begin">
Data: mental_rotation.csv. Click the plus to expand →<span id="opt-start-62" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-62&#39;, &#39;opt-start-62&#39;)"></span>
</div>
<div id="opt-body-62" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/mental_rotation.csv">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>Each person in the sample was asked to look at two 3D images presented next to each other. The second image was simply a rotated version of the first, and the participants were asked to identify if the two images showed the same object or not. The reaction time (in milliseconds) was recorded for each participant.</p>
<p>The measured variables were:</p>
<ul>
<li><code>angle_degrees</code>: The rotation angle, between 0 and 200 degrees, of the second image.</li>
<li><code>rt_ms</code>: Reaction time (in milliseconds).</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-1"></span>
<img src="images/mental_rotation.gif" alt="Example of target object (left) and rotated version of it (right). Source: https://plato.stanford.edu/entries/mental-imagery/mental-rotation.html" width="60%" />
<p class="caption">
Figure 1: Example of target object (left) and rotated version of it (right). Source: <a href="https://plato.stanford.edu/entries/mental-imagery/mental-rotation.html" class="uri">https://plato.stanford.edu/entries/mental-imagery/mental-rotation.html</a>
</p>
</div>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
angle_degrees
</th>
<th style="text-align:center;">
rt_ms
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 10em; ">
69.23
</td>
<td style="text-align:center;width: 10em; ">
882.99
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
3.08
</td>
<td style="text-align:center;width: 10em; ">
541.60
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
164.62
</td>
<td style="text-align:center;width: 10em; ">
1618.78
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
153.85
</td>
<td style="text-align:center;width: 10em; ">
1458.74
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
63.08
</td>
<td style="text-align:center;width: 10em; ">
973.34
</td>
</tr>
<tr>
<td style="text-align:center;width: 10em; ">
21.54
</td>
<td style="text-align:center;width: 10em; ">
627.80
</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
</div>
<div id="analysis" class="section level1">
<h1>Analysis</h1>
<div class="yellow">
<p><strong>IMPORTANT</strong></p>
<p>In today’s lab the analysis is provided, and the task for you will be to correctly report what has been done and why.</p>
</div>
<p>Read the data into R:</p>
<pre class="r"><code>library(tidyverse)
library(car)

mr &lt;- read_csv(file = &#39;https://uoepsy.github.io/data/mental_rotation.csv&#39;)
head(mr)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   angle_degrees rt_ms
##           &lt;dbl&gt; &lt;dbl&gt;
## 1         69.2   883.
## 2          3.08  542.
## 3        165.   1619.
## 4        154.   1459.
## 5         63.1   973.
## 6         21.5   628.</code></pre>
<p>Rename variables:</p>
<pre class="r"><code>mr &lt;- mr %&gt;%
  rename(
    angle = angle_degrees,
    rt = rt_ms
  )
head(mr)</code></pre>
<pre><code>## # A tibble: 6 x 2
##    angle    rt
##    &lt;dbl&gt; &lt;dbl&gt;
## 1  69.2   883.
## 2   3.08  542.
## 3 165.   1619.
## 4 154.   1459.
## 5  63.1   973.
## 6  21.5   628.</code></pre>
<div class="green">
<p><strong>TIP</strong></p>
<p>The <code>patchwork</code> library is used to combine ggplots into a single figure made up of multiple panels. You can add individual ggplots using <code>+</code> or <code>|</code>, and put plots underneath with the <code>/</code> operator.</p>
</div>
<p>Investigate the marginal distribution of each variable and the relationship between the two variables.</p>
<pre class="r"><code>library(patchwork)

plt_angle &lt;- ggplot(mr, aes(x = angle)) +
  geom_density() +
  geom_boxplot(width = 0.001) +
  labs(x = &#39;Angle (degrees)&#39;)

plt_rt &lt;- ggplot(mr, aes(x = rt)) +
  geom_density() +
  geom_boxplot(width = 0.0001) +
  labs(x = &#39;RT (ms)&#39;)

plt_joint &lt;- ggplot(mr, aes(x = angle, y = rt)) +
  geom_point() +
  labs(x = &#39;Angle (degrees)&#39;, y = &#39;RT (ms)&#39;)

plt_angle | plt_rt | plt_joint</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-5-1.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mr %&gt;%
  summarise(M_angle = mean(angle), 
            SD_angle = sd(angle),
            MED_angle = median(angle), 
            IQR_angle = IQR(angle),
            M_rt = mean(rt), 
            SD_rt = sd(rt),
            MED_rt = median(rt), 
            IQR_rt = IQR(rt))</code></pre>
<pre><code>## # A tibble: 1 x 8
##   M_angle SD_angle MED_angle IQR_angle  M_rt SD_rt MED_rt IQR_rt
##     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1    103.     54.3      96.2      91.9 1243.  505.  1157.   695.</code></pre>
<p>Correlation between the variables:</p>
<pre class="r"><code>cor(mr)</code></pre>
<pre><code>##           angle        rt
## angle 1.0000000 0.8540206
## rt    0.8540206 1.0000000</code></pre>
<p>Linear model:</p>
<pre class="r"><code>mdl1 &lt;- lm(rt ~ 1 + angle, data = mr)
summary(mdl1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rt ~ 1 + angle, data = mr)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1503.24  -126.76   -26.26    84.89   774.49 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 422.9043    56.9626   7.424  4.2e-11 ***
## angle         7.9417     0.4887  16.251  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 264 on 98 degrees of freedom
## Multiple R-squared:  0.7294, Adjusted R-squared:  0.7266 
## F-statistic: 264.1 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="green">
<p><strong>TIP</strong></p>
<p>When you call <code>plot()</code> on a fitted model to show the diagnostic plots, you can display all four plots at once by telling R:</p>
<pre class="r"><code>par(mfrow = c(2,2))</code></pre>
<p>This means that each figure should be made of 2 by 2 plots, filled row-wise. The first plot will appear in panel (1,1), the second plot in panel (1,2), the third in panel (2,1) and the last in panel (2,2).</p>
<p>To go back to one figure made of a single plot, you type:</p>
<pre class="r"><code>par(mfrow = c(1,1))</code></pre>
<p><strong>IMPORTANT</strong></p>
<p><code>par(mfrow = ...)</code> will not work with ggplot.</p>
</div>
<p>Diagnostics:</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl1)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-11-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>im &lt;- influence.measures(mdl1)
summary(im)</code></pre>
<pre><code>## Potentially influential observations of
##   lm(formula = rt ~ 1 + angle, data = mr) :
## 
##    dfb.1_ dfb.angl dffit   cov.r   cook.d  hat  
## 2   0.08  -0.07     0.08    1.07_*  0.00    0.04
## 8  -0.25   0.45     0.55_*  0.87_*  0.14    0.03
## 19 -0.10   0.24     0.34    0.92_*  0.06    0.02
## 41  0.82  -1.31_*  -1.50_*  0.46_*  0.74_*  0.04
## 52  0.02  -0.02     0.02    1.07_*  0.00    0.04
## 63  0.35  -0.26     0.37    0.90_*  0.07    0.02
## 87 -0.34   0.55     0.63_*  0.88_*  0.19    0.04</code></pre>
<p>For now, we will focus on Cook’s distance only:</p>
<pre class="r"><code>mr &lt;- mr[-41, ]</code></pre>
<p>Re-fit the model using the new dataset and check the assumptions:</p>
<pre class="r"><code>mdl2 &lt;- lm(rt ~ 1 + angle, data = mr)
summary(mdl2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rt ~ 1 + angle, data = mr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -440.29 -132.78  -27.69   64.74  718.91 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  384.897     46.632   8.254 7.72e-13 ***
## angle          8.462      0.404  20.942  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 214.7 on 97 degrees of freedom
## Multiple R-squared:  0.8189, Adjusted R-squared:  0.817 
## F-statistic: 438.6 on 1 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl2)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-15-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ncvTest(mdl2)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 11.15201, Df = 1, p = 0.00083941</code></pre>
<p>Try transforming the response:</p>
<pre class="r"><code>mr &lt;- mr %&gt;%
    mutate(log_rt = log(rt))</code></pre>
<p>Fit a linear model using the transformed response:</p>
<pre class="r"><code>mdl3 &lt;- lm(log_rt ~ 1 + angle, data = mr)
summary(mdl3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_rt ~ 1 + angle, data = mr)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28639 -0.09377 -0.01471  0.07431  0.63128 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6.3291728  0.0330909   191.3   &lt;2e-16 ***
## angle       0.0070543  0.0002867    24.6   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1524 on 97 degrees of freedom
## Multiple R-squared:  0.8619, Adjusted R-squared:  0.8605 
## F-statistic: 605.3 on 1 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl3)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-19-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(mdl3$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  mdl3$residuals
## W = 0.95174, p-value = 0.001159</code></pre>
<p>Try removing the outlier from the dataset:</p>
<pre class="r"><code>mr &lt;- mr[-62, ]</code></pre>
<p>Re-fit the model and check assumptions:</p>
<pre class="r"><code>mdl4 &lt;- lm(log_rt ~ 1 + angle, data = mr)
summary(mdl4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_rt ~ 1 + angle, data = mr)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28447 -0.08552 -0.01535  0.07567  0.37662 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6.3111856  0.0303685  207.82   &lt;2e-16 ***
## angle       0.0071666  0.0002621   27.34   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1387 on 96 degrees of freedom
## Multiple R-squared:  0.8862, Adjusted R-squared:  0.885 
## F-statistic: 747.8 on 1 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mdl4)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-21-1.png" width="90%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(mdl4$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  mdl4$residuals
## W = 0.97986, p-value = 0.138</code></pre>
<pre class="r"><code>ncvTest(mdl4)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.2260013, Df = 1, p = 0.6345</code></pre>
<p>Go back to figures with only one plot:</p>
<pre class="r"><code>par(mfrow = c(1,1))</code></pre>
<p>Create a table for reporting the results:</p>
<pre class="r"><code>library(sjPlot)
tab_model(mdl4)</code></pre>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
log rt
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.31
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.25 – 6.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
angle
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
98
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.886 / 0.885
</td>
</tr>
</table>
<p><br>
Plot the final model:</p>
<pre class="r"><code>betas &lt;- coef(mdl4)

ggplot(mr, aes(x = angle, y = log_rt)) +
  geom_point() +
  geom_abline(intercept = betas[1], slope = betas[2], color = &#39;blue&#39;) +
  labs(x = &#39;Angle (degrees)&#39;, y = &#39;Log RT (ms)&#39;)</code></pre>
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-24-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<div id="reporting" class="section level1">
<h1>Reporting</h1>
<p>A good data analysis report should follow three steps: <em>Think, Show, and Tell.</em></p>
<p>For a detailed explanation of each step, check this <a href="https://uoepsy.github.io/files/writeup_guide.pdf" target="_blank">document.</a></p>
<div id="think" class="section level2">
<h2>Think</h2>
<div class="yellow">
<p>What do you know? What do you hope to learn? What did you learn during the exploratory analysis?</p>
</div>
<div class="question-begin">
1: Describe design
</div>
<div class="question-body">
<p>Describe the study design, the data collection strategy, etc.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-63" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-63&#39;, &#39;sol-start-63&#39;)"></span>
</div>
<div id="sol-body-63" class="solution-body" style="display: none;">
<p>A random sample of 100 participants was invited to take part into a mental rotation task. Each participant was shown two images and was asked to identify whether or not the objects displayed in the two images were the same.
The second image was displayed with a rotation of a certain angle.
For each participant, reaction time (in milliseconds) and rotation angle (in degrees) were recorded.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
2: Describe the data
</div>
<div class="question-body">
<ul>
<li>How many observational units? (If not mentioned above.)</li>
<li>Are there any observations that have been excluded based on pre-defined criteria? How/why, and how many?</li>
<li>Describe and visualise the variables of interest. How are they scored? have they been transformed at all?</li>
<li>Describe and visualise relationships between variables. Report covariances/correlations.</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-64" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-64&#39;, &#39;sol-start-64&#39;)"></span>
</div>
<div id="sol-body-64" class="solution-body" style="display: none;">
<div class="figure" style="text-align: center"><span id="fig:marg-distrib"></span>
<img src="05_slr_writeup_files/figure-html/marg-distrib-1.png" alt="Marginal and joint distributions." width="100%" />
<p class="caption">
Figure 2: Marginal and joint distributions.
</p>
</div>
<p>The distribution of rotation angles appears to be roughly symmetric around the mean angle of 103 degrees, with standard deviation 54.3 degrees.
The boxplot in Figure <a href="#fig:marg-distrib">2</a>(a) does not highlight any evident outliers.</p>
<p>The distribution of reaction times appears to be right skewed, with a median reaction time of 1157 ms, and interquartile range of 695 ms.
A boxplot of the distribution, Figure <a href="#fig:marg-distrib">2</a>(b), flags two potential outliers which are worth keeping an eye on, but have not been removed from the dataset.</p>
<p>Finally, the scatterplot in Figure <a href="#fig:marg-distrib">2</a>(c) displays the relationship between rotation angle and reaction time. There appears to be a strong (<span class="math inline">\(r_{Angle, RT} = 0.81\)</span>), positive linear relationship between the two variables.
The scatterplot also highlights a couple of points which do not fit with the rest of the data. One has a high rotation angle but an unusually low reaction time, and another point having an angle of approximately 50 degrees and a reaction time of 1500 ms approximately, which is roughly 700 ms above the rest of the points.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
3: Describe the analytical approach
</div>
<div class="question-body">
<ul>
<li>What type of statistical analysis do you use to answer the research question? (e.g., t-test, simple linear regression,
multiple linear regression)</li>
<li>Describe the model/analysis structure</li>
<li>What is your outcome variable? What is its type?</li>
<li>What are your predictors? What are their types?</li>
<li>Any other specifics?</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-65" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-65&#39;, &#39;sol-start-65&#39;)"></span>
</div>
<div id="sol-body-65" class="solution-body" style="display: none;">
<p>We want to investigate whether reaction time is affected by the object’s rotation angle and what is the intensity of that relationship.</p>
<p>To do so, we will use a simple linear regression model involving two numeric variables: angle (the predictor) and reaction time (the response).
In the dataset, angle is measured in degrees and reaction time in milliseconds.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
4: Planned analysis vs actual analysis
</div>
<div class="question-body">
<ul>
<li>Was there anything you had to do differently than planned during the analysis? Did the modelling highlight issues in your data?</li>
<li>Did you have to do anything (e.g., transform any variables, exclude any observations) in order to meet assumptions?</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-66" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-66&#39;, &#39;sol-start-66&#39;)"></span>
</div>
<div id="sol-body-66" class="solution-body" style="display: none;">
<p>The linear model <span class="math inline">\(\widehat{RT} = \hat \beta_0 + \hat \beta_1 Angle\)</span>, however, highlighted one influential observation (namely, case 41) having a Cook’s distance of 0.74.
Careful inspection of case 41 showed a large rotation angle (200 degrees), far from the average angle (103 degrees) — hence, the point has high leverage. Furthermore, the point was an outlier as the actual reaction time was 508 ms, which was roughly 1503 ms lower than the model-predicted value.</p>
<p>After removing such observation from the dataframe and re-fitting the linear model, the diagnostic plots raised concerns about the normality and equal variance assumptions not being satisfied.</p>
<p>The Normal quantile plot showed that the distribution of the residuals was skewed to the right, and the Scale-Location plot displayed a thickening pattern (that is, a fan-shape) rather than a roughly constant vertical spread. Similarly, the Residuals vs Fitted values plot also showed a thickening pattern with a fan-like shape, suggesting a violation of the constant variance assumption.</p>
<p>To mitigate the violation of the equal variance assumption, we log transformed the response variable.</p>
<p>After refitting the model, the diagnostic plots only raised concern about a single point (case 62) not fitting the linear pattern in the Normal quantile plot, and also being particularly unusual in the Residuals vs Fitted values plot.</p>
<p>At the 5% significance level, a Shapiro-Wilk test for normality of the errors showed a significant p-value, indicating violation of the normality assumption.</p>
<p>After careful inspection, we decided to remove case 62 from the dataset and re-fit the linear model.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="show" class="section level2">
<h2>Show</h2>
<div class="yellow">
<p>Show the mechanics and visualisations which will support your conclusions</p>
</div>
<div class="question-begin">
5: Present and describe the final model
</div>
<div class="question-body">
<p>Present and describe the model or test which you deemed best to answer your question.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-67" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-67&#39;, &#39;sol-start-67&#39;)"></span>
</div>
<div id="sol-body-67" class="solution-body" style="display: none;">
<p>The final model which was chosen to answer the research question of interest was:
<span class="math display">\[
\widehat{\log (RT)} = 6.31 + 0.00717 \ Angle
\]</span></p>
<p>and was fitted excluding case 41, and then case 62.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
The former was found to be an influential point, while the latter an outlier affecting normality.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
6: Are the assumptions and conditions of your final test or model satisfied?
</div>
<div class="question-body">
<p>Are the assumptions and conditions of your final test or model satisfied?
<em>For the final model (the one you report results from), were all assumptions met? (Hopefully yes, or there is more work to do…). Include evidence (tests or plots).</em></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-68" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-68&#39;, &#39;sol-start-68&#39;)"></span>
</div>
<div id="sol-body-68" class="solution-body" style="display: none;">
<p><img src="05_slr_writeup_files/figure-html/unnamed-chunk-25-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>The final model was found to not violate the regression assumptions. A plot of the residuals vs fitted values shows randomly scattered points with no pattern and a horizontal direction.</p>
<p>The Normal quantile plot (qq-plot) shows a roughly linear trend in the standardized residuals vs the normal quantiles.
We performed a Shapiro-Wilk test, at the 5% significance level, against the null hypothesis that the residuals came from a normal distribution (<span class="math inline">\(W = 0.98\)</span>, <span class="math inline">\(p = 0.138\)</span>).
The large <span class="math inline">\(W\)</span>-statistic leads to a p-value (0.138) larger than the 0.05 threshold.
Hence, the sample results do not provide sufficient evidence to reject the null hypothesis that the errors follow a normal distribution.</p>
<p>The Residuals vs Fitted plot and the Scale-Location plot show that the vertical spread of the residuals is roughly the same everywhere.
Hence, we see no violation of the constant variance assumption.
At the 5% significance level, we also performed a Breusch-Pagan test against the null hypothesis of homoscedasticity (<span class="math inline">\(\chi^2(1) = 0.226, p = 0.634\)</span>). The large p-value indicates that the sample results do not provide sufficient evidence to reject the null hypothesis of equal variance.</p>
<p>Finally, a plot of residuals vs leverage does not highlight any influential observations.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
7: Report your test or model results
</div>
<div class="question-body">
<ul>
<li>Provide a table of results if applicable (for regression tables, try <code>tab_model()</code> from the <strong>sjPlot</strong> package).</li>
<li>Provide plots if applicable.</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-69" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-69&#39;, &#39;sol-start-69&#39;)"></span>
</div>
<div id="sol-body-69" class="solution-body" style="display: none;">
The table below displays the estimated regression coefficients along with the corresponding test of significance:
<center>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
log rt
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.31
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
6.25 – 6.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
angle
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
98
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.886 / 0.885
</td>
</tr>
</table>
</center>
<p><br>
The fitted model is displayed below:
<img src="05_slr_writeup_files/figure-html/unnamed-chunk-27-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="tell" class="section level2">
<h2>Tell</h2>
<div class="yellow">
<p>Communicate your findings</p>
</div>
<div class="question-begin">
8: Interpret your results in the context of your research question.
</div>
<div class="question-body">
<ul>
<li>What do your results suggest about your research question?</li>
<li>Make direct links from hypotheses to models (which bit is testing hypothesis)</li>
<li>Be specific - which statistic did you use/what did the statistical test say? Comment on effect sizes.</li>
<li>Make sure to include measurement units where applicable.</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-70" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-70&#39;, &#39;sol-start-70&#39;)"></span>
</div>
<div id="sol-body-70" class="solution-body" style="display: none;">
<p>The fitted model predicts log reaction time for a given rotation angle.
Both intercept (<span class="math inline">\(t(96) = 6.31, p &lt; .001\)</span>, two-sided) and slope (<span class="math inline">\(t(96) = 0.00717, p &lt; .001\)</span>, two-sided) are significantly different from zero.</p>
<p>The estimated intercept <span class="math inline">\(\hat \beta_0 = 6.31\)</span> represents the predicted log reaction time (in milliseconds) when the object is not rotated (zero degrees angle).</p>
<p>The estimated slope, <span class="math inline">\(\hat \beta_1 = 0.00717\)</span>, indicates that, each one-degree increase in the object rotation angle is associated, on average, to a 0.00717 ms increase in log reaction time.</p>
<p>That is, there is a positive/increasing linear relationship between rotation angle and log reaction time.
However, the magnitude of the rate of increase, even if significant, is small and in the order of 0.01.</p>
<p>The F-test for model utility is also significant (<span class="math inline">\(F(1,96) = 747.8, p &lt; .001\)</span>). At the 5% significance level, rotation angle is a significant predictor of log reaction time.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<p>Approximately 88.6% of the variability in log reaction times is explained by the linear association with the objects’ rotation angle.</p>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="put-everything-together" class="section level1">
<h1>Put everything together</h1>
<p>If you followed the steps above, it is just a matter of taking all answers to the above questions and combining them, in order to have a reasonable draft of a statistical report.</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Footnote: in the original dataset, these would be cases 41 and 63.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>
In simple linear regression, this information is equivalent to the t-test for the significance of the slope as the F-statistic is the square t-statistic.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
