<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Assumptions &amp; Diagnostics</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">1/2: Simple linear regression</a>
    </li>
    <li>
      <a href="03_slr_model_fit.html">1/3: Model Fit, Standardized Coefficients</a>
    </li>
    <li>
      <a href="04_slr_assumptions.html">1/4: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="05_slr_writeup.html">1/5: Writing-up</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">1/7: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">1/8: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">1/10: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="11_anova.html">2/1: ANOVA</a>
    </li>
    <li>
      <a href="11_anova.html">2/2: ANOVA (again)</a>
    </li>
    <li>
      <a href="12_factorial_anova.html">2/3: 2x2 ANOVA</a>
    </li>
    <li>
      <a href="13_multiplecomp.html">2/4: Multiple Comparisons</a>
    </li>
    <li class="dropdown-header">2/5: No exercises</li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="14_bootstrap_reg.html">2/7: Bootstrap</a>
    </li>
    <li>
      <a href="15_binary_logistic.html">2/8: Binary Logistic Regression</a>
    </li>
    <li>
      <a href="16_more_about_logistic.html">2/9: More About Logistic Regression</a>
    </li>
    <li>
      <a href="17_power_regression.html">2/10: Sample Size and Power Analysis</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Assumptions &amp; Diagnostics</h1>

</div>


<div class="green">
<p>Be sure to check the <a href="07_mlr_int.html"><strong>solutions to last week’s exercises</strong></a>.<br>You can still ask any questions about previous weeks’ materials if things aren’t clear!</p>
</div>
<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ol style="list-style-type: decimal">
<li>Specify the assumptions underlying a LM with multiple predictors.</li>
<li>Assess if a fitted model satisfies the assumptions.</li>
<li>Test and assess the effect of influential cases on LM coefficients and overall model evaluations.</li>
</ol>
</div>
<div id="refresher-lm-assumptions" class="section level1">
<h1>Refresher: LM assumptions</h1>
<div class="frame">
<p>In the previous labs, we have fitted a number of multiple regression models. In each case, we first specified the model, then visually explored the marginal distributions and relationships of variables which would be used in the analysis. Finally, we fit the model, and began to examine the fit by studying what the various parameter estimates represented, and the spread of the residuals (the parts of the output inside the red boxes in Figure <a href="#fig:mlroutput">1</a>)</p>
<div class="figure" style="text-align: center"><span id="fig:mlroutput"></span>
<img src="images/mlroutput.png" alt="Multiple regression output in R, summary.lm(). Residuals and Coefficients highlighted" width="60%" />
<p class="caption">
Figure 1: Multiple regression output in R, summary.lm(). Residuals and Coefficients highlighted
</p>
</div>
<p>You will recall that <strong>before</strong> we draw inferences using our model estimates or use our model to make predictions, we need to be satisfied that our model meets the set of assumptions.</p>
<div class="red">
All of the estimates, intervals and hypothesis tests (see Figure <a href="#fig:mlroutputhyp">2</a>) resulting from a regression analysis <em>assume</em> a certain set of conditions have been met. Meeting these conditions is what allows us to generalise our findings beyond our sample (i.e., to the population).<br />

<div class="figure" style="text-align: center"><span id="fig:mlroutputhyp"></span>
<img src="images/mlrhyp.png" alt="Multiple regression output in R, summary.lm(). Hypothesis tests highlighted" width="60%" />
<p class="caption">
Figure 2: Multiple regression output in R, summary.lm(). Hypothesis tests highlighted
</p>
</div>
</div>
<p>Recall the assumptions of the linear model:</p>
<ul>
<li><strong>L</strong>inearity: The relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> is linear.</li>
<li><strong>I</strong>ndependence of errors: The error terms should be independent from one another.</li>
<li><strong>N</strong>ormality: The errors <span class="math inline">\(\epsilon\)</span> are normally distributed</li>
<li><strong>E</strong>qual variances (“Homoscedasticity”): The scale of the variability of the errors <span class="math inline">\(\epsilon\)</span> is constant at all values of <span class="math inline">\(x\)</span>.</li>
</ul>
<p>When we fit a model, we evaluate many of these assumptions by looking at the residuals (the deviations from the observed values <span class="math inline">\(y_i\)</span> and the model estimated value <span class="math inline">\(\hat y_i\)</span>). The residuals, <span class="math inline">\(\hat \epsilon\)</span> are our estimates of the actual unknown true error term <span class="math inline">\(\epsilon\)</span>.<br />
Because these same assumptions hold for a regression model with multiple predictors, we can assess them in a similar way. However, there are a number of important considerations.</p>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Open a new RMarkdown document. Copy the code below to load in the tidyverse packages, read in the wellbeing.csv data and fit the following model:</p>
<p><span class="math display">\[ 
\text{Wellbeing} = \beta_0 + \beta_1 \cdot \text{Outdoor Time} + \beta_2 \cdot \text{Social Interactions} + \epsilon
\]</span></p>
<pre class="r"><code>library(tidyverse) 

# read in the wellbeing data
mwdata = read_csv(file = &quot;https://uoepsy.github.io/data/wellbeing.csv&quot;)
# fit the linear model: 
wb_mdl1 &lt;- lm(wellbeing ~ outdoor_time + social_int, data = mwdata)</code></pre>
<p><strong>Note:</strong> We have have forgone writing the <code>1</code> in <code>lm(y ~ 1 + x...</code>. The 1 just tells R that we want to estimate the Intercept, and it will do this by default even if we leave it out.</p>
<p class="question-end">
</p>
</div>
</div>
<div id="guided-exercises" class="section level1">
<h1>Guided exercises</h1>
<div id="linearity" class="section level2">
<h2>Linearity</h2>
<div class="frame">
<p>In simple linear regression (SLR) with only one explanatory variable, we could assess linearity through a simple scatterplot of the outcome variable against the explanatory. In multiple regression, however, it becomes more necessary to rely on diagnostic plots of the model residuals. This is because we need to know whether the relations are linear between the outcome and each predictor <em>after accounting for the other predictors in the model.</em></p>
<p>In order to assess this, we use <strong>partial-residual plots</strong> (also known as ‘component-residual plots’). This is a plot with each explanatory variable <span class="math inline">\(x_j\)</span> on the x-axis, and <strong>partial residuals</strong> on the y-axis.</p>
<p>Partial residuals for a predictor <span class="math inline">\(x_j\)</span> are calculated as:
<span class="math display">\[
\hat \epsilon + \hat \beta_j x_j
\]</span></p>
<p><strong>In R</strong> we can easily create these plots for all predictors in the model by using the <code>crPlots()</code> function from the <strong>car</strong> package.</p>
</div>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Create partial-residual plots for the <code>wb_mdl1</code> model.<br />
Remember to load the <strong>car</strong> package first. If it does not load correctly, it might mean that you have need to install it.</p>
<p>Write a sentence summarising whether or not you consider the assumption to have been met. Justify your answer with reference to the plots.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-104" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-104&#39;, &#39;sol-start-104&#39;)"></span>
</div>
<div id="sol-body-104" class="solution-body" style="display: none;">
<pre class="r"><code>library(car)
crPlots(wb_mdl1)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-2-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="int">
<p>The smoother (the pink line) follows quite closely to a linear relationship (the dashed blue line), suggesting that the linearity assumption is met.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="equal-variances-homoscedasticity" class="section level2">
<h2>Equal variances (Homoscedasticity)</h2>
<div class="frame">
<p>The equal variances assumption is that the error variance <span class="math inline">\(\sigma^2\)</span> is constant across values of the predictors <span class="math inline">\(x_1\)</span>, … <span class="math inline">\(x_k\)</span>, and across values of the fitted values <span class="math inline">\(\hat y\)</span>. This sometimes gets termed “Constant” vs “Non-constant” variance. Figures <a href="#fig:ncv1">3</a> &amp; <a href="#fig:ncv2">4</a> shows what these look like visually.</p>
<div class="figure" style="text-align: center"><span id="fig:ncv1"></span>
<img src="08_mlr_assumpt_files/figure-html/ncv1-1.png" alt="Non-constant variance for numeric and categorical x" width="60%" />
<p class="caption">
Figure 3: Non-constant variance for numeric and categorical x
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:ncv2"></span>
<img src="08_mlr_assumpt_files/figure-html/ncv2-1.png" alt="Constant variance for numeric and categorical x" width="60%" />
<p class="caption">
Figure 4: Constant variance for numeric and categorical x
</p>
</div>
<p><strong>In R</strong> we can create plots of the <em>Pearson residuals</em> against the predicted values <span class="math inline">\(\hat y\)</span> and against the predictors <span class="math inline">\(x_1\)</span>, … <span class="math inline">\(x_k\)</span> by using the <code>residualPlots()</code> function from the <strong>car</strong> package. This function also provides the results of a lack-of-fit test for each of these relationships (note when it is the fitted values <span class="math inline">\(\hat y\)</span> it gets called “Tukey’s test”).</p>
<p><code>ncvTest(model)</code> (also from the <strong>car</strong> package) performs a test against the alternative hypothesis that the error variance changes with the level of the fitted value (also known as the “Breusch-Pagan test”). <span class="math inline">\(p &gt;.05\)</span> indicates that we do <em>not</em> have evidence that the assumption has been violated.</p>
</div>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Use <code>residualPlots()</code> to plot residuals against each predictor, and use <code>ncvTest()</code> to perform a test against the alternative hypothesis that the error variance changes with the level of the fitted value.</p>
<p>Write a sentence summarising whether or not you consider the assumption to have been met. Justify your answer with reference to plots and/or formal tests where available.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-105" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-105&#39;, &#39;sol-start-105&#39;)"></span>
</div>
<div id="sol-body-105" class="solution-body" style="display: none;">
<pre class="r"><code>residualPlots(wb_mdl1)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-3-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre><code>##              Test stat Pr(&gt;|Test stat|)
## outdoor_time   -0.3478           0.7306
## social_int     -0.1068           0.9157
## Tukey test     -0.4189           0.6753</code></pre>
<pre class="r"><code>#test against the alternative hypothesis that error variance changes with level of fitted value
ncvTest(wb_mdl1)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.001925809, Df = 1, p = 0.965</code></pre>
<div class="int">
<p>Partial residual plots show no clear non-linear trends between residuals and predictors.
Visual inspection of suggested little sign of non-constant variance, with the Breusch-Pagan test failing to reject the null that error varance does not change across the fitted values (<span class="math inline">\(\chi^2(1)=0.002\)</span>, <span class="math inline">\(p = .965\)</span>).</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Create the “residuals vs. fitted plot” - a scatterplot with the residuals <span class="math inline">\(\hat \epsilon\)</span> on the y-axis and the fitted values <span class="math inline">\(\hat y\)</span> on the x-axis.<br />
<br>
You can either do this:</p>
<ol style="list-style-type: lower-alpha">
<li>manually, using the functions <code>residuals()</code> and <code>fitted()</code>, or</li>
<li>quickly by giving the <code>plot()</code> function your model. Be sure to specify which plot you want to return - e.g., <code>plot(wb_mdl1, which = ???)</code></li>
</ol>
<p>You can use this plot to visually assess:</p>
<ul>
<li><strong>L</strong>inearity: Does the average of the residuals <span class="math inline">\(\hat \epsilon\)</span> remain close to 0 across the plot?<br />
</li>
<li><strong>E</strong>qual Variance: does the spread of the residuals <span class="math inline">\(\hat \epsilon\)</span> remain constant across the predicted values <span class="math inline">\(\hat y\)</span>?</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-106" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-106&#39;, &#39;sol-start-106&#39;)"></span>
</div>
<div id="sol-body-106" class="solution-body" style="display: none;">
<p>The long way:</p>
<pre class="r"><code># Notice that we create a tibble and pass it directly to ggplot()
# using the %&gt;%.
# This means we don&#39;t have to store it as an object in the environment,
# it is just being used to create the plot
tibble(
  residuals = residuals(wb_mdl1),
  fitted = fitted(wb_mdl1)
) %&gt;% 
  ggplot(aes(x = fitted, y = residuals)) + 
  geom_point() + 
  geom_smooth(color=&quot;red&quot;,se=FALSE)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-4-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>The quick way:</p>
<pre class="r"><code>plot(wb_mdl1, which=1)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-5-1.png" width="60%" style="display: block; margin: auto;" /></p>
<div class="int">
<p>The horizontal red line shows that the average of the residual remains close to zero across the fitted values.<br />
The spread of the residuals remains reasonably constant across the fitted values.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="independence" class="section level2">
<h2>Independence</h2>
<div class="frame">
<p>The “independence of errors” assumption is the condition that the errors do not have some underlying relationship which is causing them to influence one another.
<br>
There are many sources of possible dependence, and often these are issues of study design. For example, we may have groups of observations in our data which we would expect to be related (e.g., multiple trials from the same participant). Our modelling strategy would need to take this into account.
<br>
One form of dependence is <strong>autocorrelation</strong> - this is when observations influence those adjacent to them. It is common in data for which <em>time</em> is a variable of interest (e.g, the humidity today is dependent upon the rainfall yesterday).<br />
<br>
<strong>In R</strong> we can test against the alternative hypothesis that there is autocorrelation in our errors using the <code>durbinWatsonTest()</code> (an abbreviated function <code>dwt()</code> is also available) in the <strong>car</strong> package.</p>
</div>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Perform a test against the alternative hypothesis that there is autocorrelation in the error terms.</p>
<p>Write a sentence summarising whether or not you consider the assumption of independence to have been met (you may have to assume certain aspects of the study design).</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-107" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-107&#39;, &#39;sol-start-107&#39;)"></span>
</div>
<div id="sol-body-107" class="solution-body" style="display: none;">
<pre class="r"><code>dwt(wb_mdl1)</code></pre>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1       -0.318249      2.600574   0.146
##  Alternative hypothesis: rho != 0</code></pre>
<div class="int">
<p>A Durbin-Watson test of autocorrelation failed to reject the null hypothesis that there was no serial dependence in the error (<span class="math inline">\(DW = 2.6\)</span>, <span class="math inline">\(p = .138\)</span>). We will also assume that observations to be randomly sampled during study recruitment.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="normality-of-errors" class="section level2">
<h2>Normality of errors</h2>
<div class="frame">
<p>The normality assumption is the condition that the errors <span class="math inline">\(\epsilon\)</span> are normally distributed.</p>
<p>We can visually assess this condition through histograms, density plots, and quantile-quantile plots (QQplots) of our residuals <span class="math inline">\(\hat \epsilon\)</span>.<br />
We can also perform a Shapiro-Wilk test against the alternative hypothesis that the residuals were not sampled from a normally distributed population. The <code>shapiro.test()</code> function in R.</p>
</div>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Assess the normality assumption by producing a qqplot of the residuals (either manually or using <code>plot(model, which = ???)</code>), and conducting a Shapiro-Wilk test.</p>
<p>Write a sentence summarising whether or not you consider the assumption to have been met. Justify your answer with reference to plots and/or formal tests where available.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-108" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-108&#39;, &#39;sol-start-108&#39;)"></span>
</div>
<div id="sol-body-108" class="solution-body" style="display: none;">
<p>We can get the QQplot from one of the <code>plot(model)</code> plots:</p>
<pre class="r"><code>plot(wb_mdl1, which = 2)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-7-1.png" width="60%" style="display: block; margin: auto;" />
Or we can make our own:</p>
<pre class="r"><code>tibble(
  resids = residuals(wb_mdl1)
) %&gt;% ggplot(aes(sample=resids))+
  geom_qq()+
  geom_qq_line()</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-8-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(residuals(wb_mdl1))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(wb_mdl1)
## W = 0.94831, p-value = 0.129</code></pre>
<div class="int">
<p>The QQplot indicates that the residuals follow close to a normal distribution, although with evidence of heavier tails. A Shapiro-Wilk test failed to reject the null hypothesis that the residuals were drawn from a normally distributed population (<span class="math inline">\(W = 0.95\)</span>, <span class="math inline">\(p = .129\)</span>)</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="multicollinearity" class="section level2">
<h2>Multicollinearity</h2>
<div class="frame">
For the linear model with multiple explanatory variables, we need to also think about <strong>multicollinearity</strong> - this is when two (or more) of the predictors in our regression model are moderately or highly correlated.<br />
Recall our interpretation of multiple regression coefficients as<br />

<center>
“the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> when <em>holding the values of <span class="math inline">\(x_2\)</span>, <span class="math inline">\(x_3\)</span>, … <span class="math inline">\(x_k\)</span> constant</em>”
</center>
<p>This interpretation falls down if predictors are highly correlated because if, e.g., predictors <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> are highly correlated, then changing the value of <span class="math inline">\(x_1\)</span> necessarily entails a change the value of <span class="math inline">\(x_2\)</span> meaning that it no longer makes sense to talk about <em>holding <span class="math inline">\(x_2\)</span> constant.</em><br />
<br>
We can assess multicollinearity using the <strong>variance inflation factor (VIF)</strong>, which for a given predictor <span class="math inline">\(x_j\)</span> is calculated as:<br />
<span class="math display">\[
VIF_j = \frac{1}{1-R_j^2} \\
\]</span>
Where <span class="math inline">\(R_j^2\)</span> is the coefficient of determination (the R-squared) resulting from a regression of <span class="math inline">\(x_j\)</span> on to all the other predictors in the model (<span class="math inline">\(x_j = x_1 + ... x_k + \epsilon\)</span>).<br />
The more highly correlated <span class="math inline">\(x_j\)</span> is with other predictors, the bigger <span class="math inline">\(R_j^2\)</span> becomes, and thus the bigger <span class="math inline">\(VIF_j\)</span> becomes.<br />
<br>
The square root of VIF indicates how much the SE of the coefficient has been inflated due to multicollinearity. For example, if the VIF of a predictor variable were 4.6 (<span class="math inline">\(\sqrt{4.6} = 2.1\)</span>), then the standard error of the coefficient of that predictor is 2.1 times larger than if the predictor had zero correlation with the other predictor variables. Suggested cut-offs for VIF are varied. Some suggest 10, others 5. Define what you will consider an acceptable value <em>prior</em> to calculating it.<br />
<br>
<strong>In R</strong>, the <code>vif()</code> function from the <strong>car</strong> package will provide VIF values for each predictor in your model.</p>
</div>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Calculate the variance inflation factor (VIF) for the predictors in the model.</p>
<p>Write a sentence summarising whether or not you consider multicollinearity to be a problem here.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-109" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-109&#39;, &#39;sol-start-109&#39;)"></span>
</div>
<div id="sol-body-109" class="solution-body" style="display: none;">
<pre class="r"><code>vif(wb_mdl1)</code></pre>
<pre><code>## outdoor_time   social_int 
##      1.13023      1.13023</code></pre>
<div class="int">
<p>VIF values &lt;5 indicate that multicollinearity is not adversely affecting model estimates.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="individual-cases" class="section level2">
<h2>Individual cases</h2>
<div class="frame">
<p>We have seen in the case of the simple linear regression that individual cases in our data can influence our model more than others. We know about:</p>
<ul>
<li><strong>Regression outliers:</strong> A large residual <span class="math inline">\(\hat \epsilon_i\)</span> - i.e., a big discrepancy between their predicted y-value and their observed y-value.
<ul>
<li><strong>Standardised residuals:</strong> For residual <span class="math inline">\(\hat \epsilon_i\)</span>, divide by the estimate of the standard deviation of the residuals. In R, the <code>rstandard()</code> function will give you these</li>
<li><strong>Studentised residuals:</strong> For residual <span class="math inline">\(\hat \epsilon_i\)</span>, divide by the estimate of the standard deviation of the residuals excluding case <span class="math inline">\(i\)</span>. In R, the <code>rstudent()</code> function will give you these.</li>
</ul></li>
<li><strong>High leverage cases:</strong> These are cases which have considerable <em>potential</em> to influence the regression model (e.g., cases with an unusual combination of predictor values).
<ul>
<li><strong>Hat values:</strong> are used to assess leverage. In R, The <code>hatvalues()</code> function will retrieve these.</li>
</ul></li>
<li><strong>High influence cases:</strong> When a case has high leverage <em>and</em> is an outlier, it will have a large influence on the regression model.
<ul>
<li><strong>Cook’s Distance:</strong> combines <em>leverage</em> (hatvalues) with <em>outlying-ness</em> to capture influence. In R, the <code>cooks.distance()</code> function will provide these.</li>
</ul></li>
</ul>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Create a new tibble which contains:</p>
<ol style="list-style-type: decimal">
<li>The original variables from the model (Hint, what does <code>wb_mdl1$model</code> give you?)</li>
<li>The fitted values from the model <span class="math inline">\(\hat y\)</span><br />
</li>
<li>The residuals <span class="math inline">\(\hat epsilon\)</span></li>
<li>The studentised residuals</li>
<li>The hat values</li>
<li>The Cook’s Distance values.</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-110" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-110&#39;, &#39;sol-start-110&#39;)"></span>
</div>
<div id="sol-body-110" class="solution-body" style="display: none;">
<pre class="r"><code>mdl_diagnost &lt;- 
  tibble(
  wb_mdl1$model,
  fitted = fitted(wb_mdl1),
  resid = residuals(wb_mdl1),
  studres = rstudent(wb_mdl1),
  hats = hatvalues(wb_mdl1),
  cooksd = cooks.distance(wb_mdl1)
)</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Looking at the studentised residuals, are there any outliers?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-111" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-111&#39;, &#39;sol-start-111&#39;)"></span>
</div>
<div id="sol-body-111" class="solution-body" style="display: none;">
<p>Recall from the lectures, studentised residuals of <span class="math inline">\(&gt;2\)</span> or <span class="math inline">\(&lt; -2\)</span> indicate potential outlyingness.</p>
<p>We can ask R whether the <em>absolute</em> values are <span class="math inline">\(&gt;2\)</span>:</p>
<pre class="r"><code>abs(mdl_diagnost$studres) &gt; 2</code></pre>
<pre><code>##     1     2     3     4     5     6     7     8     9    10    11    12    13 
## FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE 
##    14    15    16    17    18    19    20    21    22    23    24    25    26 
## FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE 
##    27    28    29    30    31    32 
## FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>We could <em>filter</em> our newly created tibble to these observations:</p>
<pre class="r"><code>mdl_diagnost %&gt;% 
  filter(abs(studres)&gt;2)</code></pre>
<pre><code>## # A tibble: 0 x 8
## # … with 8 variables: wellbeing &lt;dbl&gt;, outdoor_time &lt;dbl&gt;, social_int &lt;dbl&gt;,
## #   fitted &lt;dbl&gt;, resid &lt;dbl&gt;, studres &lt;dbl&gt;, hats &lt;dbl&gt;, cooksd &lt;dbl&gt;</code></pre>
<p>There are zero rows.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Looking at the hat values, are there any observations with high leverage?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-112" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-112&#39;, &#39;sol-start-112&#39;)"></span>
</div>
<div id="sol-body-112" class="solution-body" style="display: none;">
<p>Recall from the lectures, hat values of more than <span class="math inline">\(2 \bar{h}\)</span> (2 times the average hat value) are considered high leverage.</p>
<p>The average hat value, <span class="math inline">\(\bar{h}\)</span> is calculated as <span class="math inline">\(\frac{k + 1}{n}\)</span>, where <span class="math inline">\(k\)</span> is the number of predictors, and <span class="math inline">\(n\)</span> is the sample size.
For our model:
<span class="math display">\[
\bar h = \frac{k+1}{n} = \frac{2+1}{32} = \frac{3}{32} = 0.094
\]</span></p>
<p>We can ask whether any of observations have hat values which are greater than <span class="math inline">\(2 \bar h\)</span>:</p>
<pre class="r"><code>mdl_diagnost %&gt;%
  filter(hats &gt; (2*0.094))</code></pre>
<pre><code>## # A tibble: 0 x 8
## # … with 8 variables: wellbeing &lt;dbl&gt;, outdoor_time &lt;dbl&gt;, social_int &lt;dbl&gt;,
## #   fitted &lt;dbl&gt;, resid &lt;dbl&gt;, studres &lt;dbl&gt;, hats &lt;dbl&gt;, cooksd &lt;dbl&gt;</code></pre>
<p>Note that 0 observations have high leverage.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Looking at the Cook’s Distance values, are there any highly influential points?<br />
You can also display these graphically using <code>plot(model, which = 4)</code> and <code>plot(model, which = 5)</code>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-113" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-113&#39;, &#39;sol-start-113&#39;)"></span>
</div>
<div id="sol-body-113" class="solution-body" style="display: none;">
<p>Recall from the lectures that we have a Cook’s Distance cut-off of <span class="math inline">\(\frac{4}{n-k-1}\)</span>, where <span class="math inline">\(k\)</span> is the number of predictors, and <span class="math inline">\(n\)</span> is the sample size.<br />
For our model:
<span class="math display">\[
D_{cutoff} = \frac{4}{n-k-1} = \frac{4}{32 - 2 - 1} = \frac{4}{29} = 0.138
\]</span></p>
<p>There are no observations which have a high influence on our model estimates:</p>
<pre class="r"><code>mdl_diagnost %&gt;%
  filter(cooksd &gt; 0.138)</code></pre>
<pre><code>## # A tibble: 0 x 8
## # … with 8 variables: wellbeing &lt;dbl&gt;, outdoor_time &lt;dbl&gt;, social_int &lt;dbl&gt;,
## #   fitted &lt;dbl&gt;, resid &lt;dbl&gt;, studres &lt;dbl&gt;, hats &lt;dbl&gt;, cooksd &lt;dbl&gt;</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="other-influence.measures" class="section level2">
<h2>Other influence.measures()</h2>
<div class="frame">
<p>Alongside Cook’s Distance, we can examine the extent to which model estimates and predictions are affected when an entire case is dropped from the dataset and the model is refitted.</p>
<ul>
<li><strong>DFFit:</strong> the change in the predicted value at the <span class="math inline">\(i^{th}\)</span> observation with and without the <span class="math inline">\(i^{th}\)</span> observation is included in the regression.<br />
</li>
<li><strong>DFbeta:</strong> the change in a specific coefficient with and without the <span class="math inline">\(i^{th}\)</span> observation is included in the regression.<br />
</li>
<li><strong>DFbetas:</strong> the change in a specific coefficient divided by the standard error, with and without the <span class="math inline">\(i^{th}\)</span> observation is included in the regression.<br />
</li>
<li><strong>COVRATIO:</strong> measures the effect of an observation on the covariance matrix of the parameter estimates. In simpler terms, it captures an observation’s influence on standard errors.</li>
</ul>
</div>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>Use the function <code>influence.measures()</code> to extract these delete-1 measures of influence.</p>
<p>Try plotting the distributions of some of these measures.</p>
<p><strong>Tip:</strong> the function <code>influence.measures()</code> returns an <code>infl</code>-type object. To plot this, we need to find a way to extract the actual numbers from it.<br />
What do you think <code>names(influence.measures(wb_mdl1))</code> shows you? How can we use <code>influence.measures(wb_mdl1)$&lt;insert name here&gt;</code> to extract the matrix of numbers?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-114" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-114&#39;, &#39;sol-start-114&#39;)"></span>
</div>
<div id="sol-body-114" class="solution-body" style="display: none;">
<pre class="r"><code>influence.measures(wb_mdl1)</code></pre>
<pre><code>## Influence measures of
##   lm(formula = wellbeing ~ outdoor_time + social_int, data = mwdata) :
## 
##      dfb.1_ dfb.otd_ dfb.scl_   dffit cov.r   cook.d    hat inf
## 1   0.43653 -0.11116 -0.32167  0.4477 1.157 0.066470 0.1489    
## 2  -0.28160  0.03170  0.22954 -0.2917 1.225 0.028838 0.1414    
## 3   0.29581  0.07604 -0.29025  0.3540 1.088 0.041520 0.0967    
## 4  -0.26445 -0.13055  0.29341 -0.3508 1.117 0.040991 0.1071    
## 5  -0.27084  0.22733  0.10472 -0.3290 1.279 0.036700 0.1766    
## 6   0.12462 -0.02693 -0.08288  0.1460 1.141 0.007277 0.0604    
## 7  -0.17361 -0.03392  0.15313 -0.2235 1.087 0.016770 0.0597    
## 8  -0.02879 -0.07259  0.06069 -0.0918 1.309 0.002906 0.1556    
## 9   0.16925  0.08820 -0.17834  0.2477 1.088 0.020553 0.0668    
## 10 -0.24768  0.33112 -0.00551 -0.4267 1.027 0.059217 0.0956    
## 11 -0.02018 -0.02535  0.02534 -0.0492 1.166 0.000834 0.0518    
## 12  0.04644  0.38731 -0.22045  0.4474 1.164 0.066462 0.1517    
## 13 -0.15606  0.21587 -0.02477 -0.3135 1.017 0.032241 0.0626    
## 14  0.13390 -0.31537  0.10705  0.3905 1.039 0.049887 0.0899    
## 15  0.14774 -0.25595  0.08688  0.4273 0.815 0.055918 0.0487    
## 16 -0.11881  0.17855 -0.06061 -0.3502 0.873 0.038519 0.0422    
## 17  0.00121 -0.07684  0.02608 -0.1031 1.177 0.003653 0.0703    
## 18  0.00329  0.04637 -0.01574  0.0739 1.159 0.001877 0.0516    
## 19  0.04301 -0.15310  0.09227  0.2432 1.055 0.019693 0.0546    
## 20  0.05819 -0.10961 -0.03803 -0.2189 1.065 0.016025 0.0508    
## 21 -0.01498  0.00131  0.03428  0.0875 1.131 0.002622 0.0380    
## 22  0.12553 -0.15510 -0.09098 -0.3084 1.020 0.031247 0.0622    
## 23 -0.03324 -0.00580  0.05840  0.1049 1.138 0.003770 0.0466    
## 24  0.24606 -0.23731 -0.18568 -0.4783 0.911 0.071967 0.0774    
## 25  0.06123  0.10878 -0.16017 -0.2209 1.131 0.016498 0.0771    
## 26 -0.02732 -0.29363  0.23790  0.3643 1.243 0.044752 0.1666    
## 27 -0.30514  0.33726  0.20108  0.5966 0.830 0.108234 0.0858    
## 28  0.06176 -0.07036 -0.03455 -0.1080 1.263 0.004013 0.1280    
## 29 -0.15327 -0.04611  0.23001  0.3039 1.067 0.030646 0.0754    
## 30  0.11226  0.25745 -0.30386 -0.3826 1.238 0.049262 0.1686    
## 31 -0.07637 -0.05313  0.12879  0.1542 1.214 0.008153 0.1047    
## 32  0.10249 -0.07000 -0.07662 -0.1399 1.353 0.006736 0.1864   *</code></pre>
<p>Let’s plot the distribution of COVRATIO statistics.<br />
Recall that values which are <span class="math inline">\(&gt;1+\frac{3(k+1)}{n}\)</span> or <span class="math inline">\(&lt;1-\frac{3(k+1)}{n}\)</span> are considered as having strong influence.<br />
For our model:
<span class="math display">\[
1 \pm \frac{3(k+1)}{n} \quad = \quad 1 \pm\frac{3(2+1)}{32} \quad = \quad 1\pm \frac{9}{32} \quad = \quad 1\pm0.28
\]</span></p>
<p>The “infmat” bit of an <code>infl</code>-type object contains the numbers. To use it with ggplot, we will need to turn it into a dataframe (<code>as.data.frame()</code>), or a tibble (<code>as_tibble()</code>):</p>
<pre class="r"><code>infdata &lt;- influence.measures(wb_mdl1)$infmat %&gt;%
  as_tibble()

ggplot(data = infdata, aes(x = cov.r)) + 
  geom_histogram() +
  geom_vline(aes(xintercept = c(1-0.28)))+
  geom_vline(aes(xintercept = c(1+0.28)))</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-17-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>It looks like a few observations may be having quite a high influence here. This is perhaps not that surprising as we only have 32 datapoints.</p>
</div>
<p class="solution-end">
</p>
<hr />
<hr />
</div>
</div>
<div id="less-guided-exercises" class="section level1">
<h1>Less guided exercises</h1>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Create a new section header in your Rmarkdown document, as we are moving onto a different dataset.</p>
<p>The code below loads the dataset of 656 participants’ scores on Big 5 Personality traits, perceptions of social ranks, and scores on a depression and anxiety scale.<br />
<br></p>
<pre class="r"><code>scs_study &lt;- read_csv(&quot;https://uoepsy.github.io/data/scs_study.csv&quot;)</code></pre>
<p><br></p>
<ol style="list-style-type: decimal">
<li>Fit the following interaction model:
<ul>
<li><span class="math inline">\(\text{DASS-21 Score} = \beta_0 + \beta_1 \cdot \text{SCS Score} + \beta_2 \cdot \text{Neuroticism} + \beta_3 \cdot \text{SCS score} \cdot \text{Neuroticism} + \epsilon\)</span></li>
</ul></li>
<li>Check that the model meets the assumptions of the linear model (<strong>Tip:</strong> to get a broad overview you can pass your model to the <code>plot()</code> function to get a series of plots).</li>
<li>If you notice any violated assumptions:
<ul>
<li>address the issues by, e.g., excluding observations from the analysis, or replacing outliers with the next most extreme value (<em>Winsorisation</em>).</li>
<li>after fitting a new model which you hope addresses violations, you need to check <strong>all</strong> of your assumptions again. It can be an iterative process, and the most important thing is that your <em>final</em> model (the one you plan to <strong>use</strong>) meets all the assumptions.</li>
</ul></li>
</ol>
<hr />
<p><strong>Tips:</strong></p>
<ul>
<li>When there is an interaction in the model, assessing linearity becomes difficult. In fact, <code>crPlots()</code> will not work. To assess, you can create a residuals-vs-fitted plot like we saw in the guided exercises above.<br />
</li>
<li>Interaction terms often result in multicollinearity, because these terms are made up of the product of some ‘main effects.’ Mean-centering the variables like we have here will reduce this source of structural multicollinearity (“structural” here refers to the fact that multicollinearity is due to our model specification, rather than the data itself)<br />
</li>
<li>You can fit a model and exclude specific observations. For instance, to remove the 3rd and 5th rows of the dataset: <code>lm(y ~ x1 + x2, data = dataset[-c(3,5),])</code>. Be careful to remember that these values remain in the dataset, they have simply been excluded from the model fit.</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-115" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-115&#39;, &#39;sol-start-115&#39;)"></span>
</div>
<div id="sol-body-115" class="solution-body" style="display: none;">
<p>We’re going to mean-center the <code>scs</code> variable from the outset.</p>
<pre class="r"><code>scs_study &lt;- read_csv(&quot;https://uoepsy.github.io/data/scs_study.csv&quot;)  

scs_study &lt;-
  scs_study %&gt;%
  mutate(
    scs_mc = scs - mean(scs)
  )

dass_mdl2 &lt;- lm(dass ~ 1 + scs_mc * zn, data = scs_study)</code></pre>
<pre class="r"><code>plot(dass_mdl2)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-21-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>From quick visual inspection, it looks like there is at least one very influential point, which has been labelled for us as case number 35.</p>
<pre class="r"><code>scs_study[35,]</code></pre>
<pre><code>## # A tibble: 1 x 8
##      zo    zc    ze     za    zn   scs  dass scs_mc
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 0.645 -1.49 0.970 -0.121  2.24    54    65   18.2</code></pre>
<p>The code below fits a new model and assigns it the name <code>dass_mdl3</code>. How is it different from the previous model?</p>
<pre class="r"><code>dass_mdl3 &lt;- lm(dass ~ 1 + scs_mc * zn, data = scs_study[-35, ])</code></pre>
<p>Does this new model meet the assumptions of multiple regression?</p>
<p><strong>Linearity</strong></p>
<pre class="r"><code>plot(dass_mdl3, which = 1)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-24-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p><strong>Equal variances (Homoscedasticity)</strong></p>
<pre class="r"><code>residualPlots(dass_mdl3)</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-25-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)
## scs_mc        1.6260           0.1044
## zn           -0.5074           0.6121
## Tukey test   -1.3170           0.1878</code></pre>
<pre class="r"><code>ncvTest(dass_mdl3)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.3706851, Df = 1, p = 0.54263</code></pre>
<p><strong>Independence of errors</strong></p>
<pre class="r"><code># we assume independence of observations was considered during study design (e.g., participants are not related, or influence one another in some way). We can test for autocorrelation:
durbinWatsonTest(dass_mdl3)</code></pre>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1     -0.04018765      2.079286    0.34
##  Alternative hypothesis: rho != 0</code></pre>
<p><strong>Normality</strong></p>
<pre class="r"><code>hist(residuals(dass_mdl3))</code></pre>
<p><img src="08_mlr_assumpt_files/figure-html/unnamed-chunk-27-1.png" width="60%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(residuals(dass_mdl3))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(dass_mdl3)
## W = 0.99762, p-value = 0.4801</code></pre>
<p><strong>Check for multicollinearity</strong></p>
<pre class="r"><code>vif(dass_mdl3)</code></pre>
<pre><code>##    scs_mc        zn scs_mc:zn 
##  1.010026  1.010174  1.000240</code></pre>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
