<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>One-way ANOVA</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>




<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">1/2: Simple linear regression</a>
    </li>
    <li>
      <a href="03_slr_model_fit.html">1/3: Model Fit, Standardized Coefficients</a>
    </li>
    <li>
      <a href="04_slr_assumptions.html">1/4: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="05_slr_writeup.html">1/5: Writing-up</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">1/7: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">1/8: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">1/10: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="11_anova.html">2/1: ANOVA</a>
    </li>
    <li>
      <a href="11_anova.html">2/2: ANOVA (again)</a>
    </li>
    <li>
      <a href="12_factorial_anova.html">2/3: 2x2 ANOVA</a>
    </li>
    <li>
      <a href="13_multiplecomp.html">2/4: Multiple Comparisons</a>
    </li>
    <li class="dropdown-header">2/5: No exercises</li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="14_bootstrap_reg.html">2/7: Bootstrap</a>
    </li>
    <li>
      <a href="15_binary_logistic.html">2/8: Binary Logistic Regression</a>
    </li>
    <li>
      <a href="16_more_about_logistic.html">2/9: More About Logistic Regression</a>
    </li>
    <li>
      <a href="17_power_regression.html">2/10: Sample Size and Power Analysis</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">One-way ANOVA</h1>

</div>


<div class="red">
<p>These exercises cover the lecture materials from weeks 1 and 2 of semester 2. So take this lab slowly, try to understand it and don’t rush through it as it is important material.</p>
<p>You will have those two weeks to work through these exercises.</p>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>You might remember that we use a t-test to test whether two population
means are equal. But what if we want to compare more than two groups?</p>
<p>ANOVA, which stands for <em>ANalysis Of VAriance</em>, is a method to assess
whether the observed differences among sample means are statistically
significant. For example, could a variation among three sample means this large be plausibly due to chance, or is it good evidence for a difference among the population means?</p>
<p>In this week’s exercises you will be asked to use one-way ANOVA to test for a difference in means among several groups specified by the levels of a single factor.</p>
<p>The null and alternative hypotheses used for comparing <span class="math inline">\(g\)</span> population
means can be written as follows:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_1 = \mu_2 = \cdots = \mu_g\)</span></li>
<li><span class="math inline">\(H_1 : \text{the means are not all equal}\)</span><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></li>
</ul>
<p>Although the name “analysis of variance” may seem odd to compare group means, we will actually establish if there is a significant different among the means by comparing the variability between the group means to the variability within each group.</p>
</div>
<div id="motivation" class="section level1">
<h1>Motivation</h1>
<p>Consider the two figures below, each corresponding to a different dataset. Each dataset comprises three samples. The sample observations are shown as black dots. Furthermore, each sample mean is displayed as a red diamond.</p>
<p><img src="11_anova_files/figure-html/unnamed-chunk-2-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Even if the null hypothesis were true, and the means of the populations underlying the groups were equal, we would still expect the sample means to vary a bit.</p>
<p>For each dataset, we wish to decide whether the sample means are different enough for us to reject the null hypothesis of equal population means.
On the contrary, if they are sufficiently close, we will just attribute the observed differences to the natural variability from sample to sample.</p>
<div class="yellow">
<p><strong>What do you think?</strong></p>
<ul>
<li>Do the data in plot (A) provide sufficient evidence that the population means are not all equal?</li>
<li>Do the data in plot (B) provide sufficient evidence that the population means are not all equal?</li>
</ul>
</div>
<p>It is fairly easy to see that the means in dataset (B) differ. It’s hard to imagine that those means could be that far apart just from natural sampling variability alone.</p>
<p>How about dataset (A)? It looks like these observations <em>could</em> have occurred from three populations having the same mean.
The variation among the group means (red diamonds) in the left plot does seem consistent with the null hypothesis of equal population means.</p>
<p>Believe it or not, both plots have the same means! The group means in both plots are 11.7, 26, and 17.4, respectively.</p>
<p>So what is making the figures look so different???</p>
<p>In plot (B), the variation within each group is so small that the differences between the means stand out.
In plot (A), instead, the variation within each group is much larger compared to the variation of the group means. This, in turn, increases the range of the y-axis, making it difficult to spot any differences between the means.</p>
<p>To verify our intuition, we will compute the residuals. These correspond to each observation minus the mean of the group it belongs to.</p>
<p>We might now compare the variability among the group means with the variability of the residuals (observation minus group mean). The following table reports the relevant variances:<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<table>
<thead>
<tr class="header">
<th align="center">Variability</th>
<th align="center">Dataset A</th>
<th align="center">Dataset B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Means</td>
<td align="center">35.74</td>
<td align="center">35.74</td>
</tr>
<tr class="even">
<td align="center">Residuals</td>
<td align="center">591.2</td>
<td align="center">1.005</td>
</tr>
</tbody>
</table>
<p>For dataset (A), the variability among the group means is smaller than the variability of the residuals.</p>
<p>For dataset (B), the variability among the group means is larger than the variability of the residuals.</p>
<p>This might prompt us to consider the following ratio,
<span class="math display">\[
\frac{\text{variability among means}}{\text{variability of residuals}}
\]</span>
also called the F-statistic, and we typically reject the null hypothesis for large values of the ratio (meaning that the variability among the means is larger than the variability of the residuals).</p>
<p>This is the central idea of the F-test used in ANOVA. If the variation of the group means is much larger than the variation of the data within each group, we reject the null hypothesis and conclude that at least two of the population means are different.
On the contrary, if the variation of the data within each group is much larger than the variation between the group means, we do not have sufficient evidence to reject the null hypothesis of equal population means.</p>
<p>How do we compute the variation among the residuals (or the group means)? Do you remember the formula of the variance? We will use the quantity at the numerator of the variance, which is called <em>sum of squares</em>. This is why the method is called analysis of variance.</p>
<!-- New lab -->
</div>
<div id="research-question" class="section level1">
<h1>Research question</h1>
<blockquote>
<p><em>Do you think the type of background music playing in a restaurant affects the amount of money that diners spend on their meal?</em></p>
</blockquote>
<div class="optional-begin">
Data: RestaurantSpending.csv<span id="opt-start-134" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-134&#39;, &#39;opt-start-134&#39;)"></span>
</div>
<div id="opt-body-134" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/RestaurantSpending.csv">Download the data
here</a></p>
<p><strong>Description</strong></p>
<p>A group of researchers wanted to verify the claims reported in <span class="citation">(<a href="#ref-North2003" role="doc-biblioref">North, Shilcock, and Hargreaves 2003</a>)</span> on whether the type of background music playing in a restaurant affects the average amount of money spent by diners on their meal.</p>
<p>The new group researchers got in touch with a restaurant and asked to alternate silence, popular music, and classical music on successive nights over 18 days.
On those nights they recorded the mean spend per head for each table.</p>
<p>The following variables were collected:</p>
<ul>
<li><code>id</code>: Identifier for each diner</li>
<li><code>type</code>: type of music played (“Classical Music,” “Pop Music,” “No Music”)</li>
<li><code>amount</code>: restaurant spending per person (in pounds)</li>
</ul>
<p><strong>Preview</strong></p>
<p>The top six rows of the data are as follows:</p>
<center>
<table style="width:44%;">
<colgroup>
<col width="6%" />
<col width="25%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">id</th>
<th align="center">type</th>
<th align="center">amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">No Music</td>
<td align="center">23.15</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">Pop Music</td>
<td align="center">20.59</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">Pop Music</td>
<td align="center">19.18</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">Pop Music</td>
<td align="center">16.7</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">Classical Music</td>
<td align="center">25.91</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">Pop Music</td>
<td align="center">19.28</td>
</tr>
</tbody>
</table>
</center>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Load the tidyverse library.</p>
<p>Read the restaurant spending data into R using the function <code>read_csv()</code> and name the data <code>rest_spend</code>.</p>
<p>Check for the correct encoding of all variables — that is, categorical
variables should be factors and numeric variables should be numeric.</p>
<p><strong>Hint</strong>: Transform a variable to a factor by using the functions <code>factor()</code> or <code>as.factor()</code>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-135" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-135&#39;, &#39;sol-start-135&#39;)"></span>
</div>
<div id="sol-body-135" class="solution-body" style="display: none;">
<p>Load the tidyverse library:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<p>Read the data into R:</p>
<pre class="r"><code>rest_spend &lt;- read_csv(&#39;https://uoepsy.github.io/data/RestaurantSpending.csv&#39;)</code></pre>
<p>Check if the data were read into R correctly by examining the top six rows:</p>
<pre class="r"><code>head(rest_spend)</code></pre>
<pre><code>## # A tibble: 6 x 3
##      id type            amount
##   &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
## 1     1 No Music          23.1
## 2     2 Pop Music         20.6
## 3     3 Pop Music         19.2
## 4     4 Pop Music         16.7
## 5     5 Classical Music   25.9
## 6     6 Pop Music         19.3</code></pre>
<p>Alternatively, you could use the <code>glimpse()</code> function:</p>
<pre class="r"><code>glimpse(rest_spend)</code></pre>
<pre><code>## Rows: 360
## Columns: 3
## $ id     &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, …
## $ type   &lt;chr&gt; &quot;No Music&quot;, &quot;Pop Music&quot;, &quot;Pop Music&quot;, &quot;Pop Music&quot;, &quot;Classical M…
## $ amount &lt;dbl&gt; 23.14891, 20.59492, 19.18172, 16.70237, 25.91041, 19.27888, 22.…</code></pre>
<p>Music type is a categorical variable but it is encoded as a character (<code>&lt;chr&gt;</code>) variable rather than a factor (<code>&lt;fctr&gt;</code>). Let’s fix this:</p>
<pre class="r"><code># We could do this the standard way
rest_spend$type &lt;- as.factor(rest_spend$type)</code></pre>
<pre class="r"><code># Or the tidyverse way
rest_spend &lt;- rest_spend %&gt;%
  mutate(type = as.factor(type))</code></pre>
<p>And check again:</p>
<pre class="r"><code>head(rest_spend)</code></pre>
<pre><code>## # A tibble: 6 x 3
##      id type            amount
##   &lt;dbl&gt; &lt;fct&gt;            &lt;dbl&gt;
## 1     1 No Music          23.1
## 2     2 Pop Music         20.6
## 3     3 Pop Music         19.2
## 4     4 Pop Music         16.7
## 5     5 Classical Music   25.9
## 6     6 Pop Music         19.3</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Create a table of summary statistics showing the number of people in each type of background music, along with their average spending and standard deviation.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-136" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-136&#39;, &#39;sol-start-136&#39;)"></span>
</div>
<div id="sol-body-136" class="solution-body" style="display: none;">
<p>The question asks us to summarise the data by creating a frequency distribution of the different music types:</p>
<pre class="r"><code>rest_spend %&gt;%
  group_by(type) %&gt;%
  summarise(n = n(),
            M = mean(amount), 
            SD = sd(amount))</code></pre>
<pre><code>## # A tibble: 3 x 4
##   type                n     M    SD
##   &lt;fct&gt;           &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Classical Music   120  24.2  1.89
## 2 No Music          120  22.1  3.44
## 3 Pop Music         120  21.9  2.97</code></pre>
<p>The same number of customers were assigned to each type of music: 120 had a silent background, 120 had classical music, and 120 pop music.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Produce a boxplot displaying the relationship between restaurant spending and music type.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-137" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-137&#39;, &#39;sol-start-137&#39;)"></span>
</div>
<div id="sol-body-137" class="solution-body" style="display: none;">
<p>A good plot to visualise the relationship between a continuous variable and a categorical one is a boxplot.</p>
<pre class="r"><code>ggplot(data = rest_spend, aes(x = type, y = amount)) +
  geom_boxplot() +
  labs(x = &#39;Background music type&#39;, y = &#39;Restaurant spending (in GBP)&#39;)</code></pre>
<p><img src="11_anova_files/figure-html/unnamed-chunk-15-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Using the boxplot, comment on any observed differences among the sample means of the three background music types.</p>
<p>Please note that this question just asks you to comment on any visible differences among the groups, not to run any formal test or analysis.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-138" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-138&#39;, &#39;sol-start-138&#39;)"></span>
</div>
<div id="sol-body-138" class="solution-body" style="display: none;">
<p>From the boxplots, it seems that customers without background music or pop music had a similar average restaurant spending.</p>
<p>Furthermore, the average restaurant spending seems to be higher for those who had a classical music background compared to the customers either without music or with a pop music background.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-specification" class="section level1">
<h1>Model specification</h1>
<p>Each music type is considered as a different population with its own mean spending.
However, the three populations (there is one for each music type) are assumed to have the same variance.</p>
<p>R by default orders the levels of a categorical variable in alphabetical order:</p>
<pre class="r"><code>levels(rest_spend$type)</code></pre>
<pre><code>## [1] &quot;Classical Music&quot; &quot;No Music&quot;        &quot;Pop Music&quot;</code></pre>
<p>If we follow the same approach and order the groups by alphabetical ordering, we can represent the data as follows:</p>
<table>
<thead>
<tr class="header">
<th align="center">Population Name</th>
<th align="center">Population ID</th>
<th align="center">Sample observations</th>
<th align="center">Population mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Classical Music</td>
<td align="center">1</td>
<td align="center"><span class="math inline">\(y_{1,1}, y_{1,2}, ..., y_{1,n}\)</span></td>
<td align="center"><span class="math inline">\(\mu_{1}\)</span></td>
</tr>
<tr class="even">
<td align="center">No Music</td>
<td align="center">2</td>
<td align="center"><span class="math inline">\(y_{2,1}, y_{2,2}, ..., y_{2,n}\)</span></td>
<td align="center"><span class="math inline">\(\mu_{2}\)</span></td>
</tr>
<tr class="odd">
<td align="center">Pop Music</td>
<td align="center">3</td>
<td align="center"><span class="math inline">\(y_{3,1}, y_{3,2}, ..., y_{3,n}\)</span></td>
<td align="center"><span class="math inline">\(\mu_{3}\)</span></td>
</tr>
</tbody>
</table>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>For the restaurant spending data, what is the number of groups (<span class="math inline">\(g\)</span>) and the numbers of observations per group (<span class="math inline">\(n\)</span>)?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-139" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-139&#39;, &#39;sol-start-139&#39;)"></span>
</div>
<div id="sol-body-139" class="solution-body" style="display: none;">
<p>There are three groups, one for each music type: “Classical Music,” “No Music,” “Pop Music.” Hence, <span class="math inline">\(g = 3\)</span>.</p>
<p>There are 120 observations for each group, i.e. <span class="math inline">\(n = 120\)</span>.</p>
</div>
<p class="solution-end">
</p>
<div id="cell-means-model" class="section level2">
<h2>Cell means model</h2>
<p>The data are assumed to follow the model:
<span class="math display">\[
y_{i,j} = \mu_{i} + \epsilon_{i,j} \qquad \begin{cases}
i = 1, 2, 3 \\
j = 1, 2, ..., 120
\end{cases}
\]</span></p>
<p>where the <span class="math inline">\(\epsilon_{i,j}\)</span>s are assumed to be independent and follow a <span class="math inline">\(N(0, \sigma)\)</span> distribution.</p>
<p>In the model above,</p>
<ul>
<li><span class="math inline">\(i = 1, 2, 3\)</span> indicates the type of music played - i.e. the group</li>
<li><span class="math inline">\(j = 1, 2, ..., 120\)</span> indicates the observation within a group</li>
<li><span class="math inline">\(y_{i,j}\)</span> is the observed spending of subject <span class="math inline">\(j\)</span> from group <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\mu_{i}\)</span> is the population mean spending of group <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\epsilon_{i,j}\)</span> is the deviation between the individual observation and the group mean</li>
</ul>
<p>The model <strong>parameters</strong> are <span class="math inline">\(\mu_1, \mu_2, \mu_3\)</span> and <span class="math inline">\(\sigma\)</span>.</p>
</div>
<div id="effects-model" class="section level2">
<h2>Effects model</h2>
<p>There is another common rewriting of the above model which is widely used in practice.</p>
<p>To get there, we first need to define:
<span class="math display">\[
\mu_i = \beta_0 + \underbrace{(\mu_{i} - \beta_0)}_{\beta_i} = \beta_0 + \beta_i
\]</span></p>
<p>That is, each group mean is:</p>
<ul>
<li><span class="math inline">\(\mu_1 = \beta_0 + \beta_1\)</span></li>
<li><span class="math inline">\(\mu_2 = \beta_0 + \beta_2\)</span></li>
<li><span class="math inline">\(\mu_3 = \beta_0 + \beta_3\)</span></li>
</ul>
<p>We have silently introduced one additional parameter (<span class="math inline">\(\beta_0\)</span>), and now we have 4 parameters (<span class="math inline">\(\beta_0, \beta_1, \beta_2, \beta_3\)</span>) to model only 3 group means (<span class="math inline">\(\mu_1, \mu_2, \mu_3\)</span>).</p>
<p>You can think of <span class="math inline">\(\beta_0\)</span> as the baseline value, and the <span class="math inline">\(\beta_1, \beta_2, \beta_3\)</span> as group effects.</p>
<p>This might seem like we are overcomplicating the model but, instead, it will make interpretation much easier in the context of multiple factors (to be discussed in the next weeks).</p>
<p>The <strong>effects model</strong> is:
<span class="math display">\[
y_{i,j} = \beta_0 + \beta_i + \epsilon_{i,j}\qquad \begin{cases}
i = 1, 2, ..., g \\
j = 1, 2, ..., n
\end{cases}
\]</span></p>
<p>with the <span class="math inline">\(\epsilon_{i,j}\)</span>s independently following a <span class="math inline">\(N(0, \sigma)\)</span> distribution as usual.</p>
<div class="red">
<p><strong>PROBLEM</strong></p>
<p>As we have four <span class="math inline">\(\beta\)</span>s to model 3 group means (<span class="math inline">\(\mu\)</span>s), the model is said to be <em>not identifiable.</em> We cannot distinguish any more whether the group mean is due to a group effect or not.</p>
<p>For example, we can get the same group mean <span class="math inline">\(\mu_i = 10\)</span>, say, either by setting:</p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> and <span class="math inline">\(\beta_i = 10\)</span>, which interprets as “there is an effect due to group <span class="math inline">\(i\)</span>”</li>
<li><span class="math inline">\(\beta_0 = 10\)</span> and <span class="math inline">\(\beta_i = 0\)</span>, which interprets as “there is no effect of group <span class="math inline">\(i\)</span>”</li>
</ul>
</div>
<p>To make the model identifiable again, we need to introduce a constraint on the parameters, effectively reducing the degrees of freedom to three, which is also the number of group means.</p>
<p>Before continuing, however, let us define the overall mean as
<span class="math display">\[
\mu = \frac{\mu_1 + \mu_2 + \mu_3}{3}
\]</span></p>
</div>
<div id="side-constraints" class="section level2">
<h2>Side-constraints</h2>
<p>Possible side-constraints on the parameters are:</p>
<table>
<thead>
<tr class="header">
<th align="center">Name</th>
<th align="center">Constraint</th>
<th align="center">Meaning of <span class="math inline">\(\beta_0\)</span></th>
<th align="center">R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Sum to zero</td>
<td align="center"><span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = 0\)</span></td>
<td align="center"><span class="math inline">\(\beta_0 = \mu\)</span></td>
<td align="center"><code>contr.sum</code></td>
</tr>
<tr class="even">
<td align="center">Reference group</td>
<td align="center"><span class="math inline">\(\beta_1 = 0\)</span></td>
<td align="center"><span class="math inline">\(\beta_0 = \mu_1\)</span></td>
<td align="center"><code>contr.treatment</code></td>
</tr>
</tbody>
</table>
<div id="sum-to-zero-constraint" class="section level3">
<h3>Sum to zero constraint</h3>
<p>Under the constraint <span class="math inline">\(\beta_1 + \beta_2 + \beta_3 = 0\)</span>, the model coefficients are interpreted as follows:</p>
<ul>
<li><span class="math inline">\(\beta_0 = \mu\)</span> is interpreted as the overall or global mean — that is, the population mean when all the groups are combined;</li>
<li><span class="math inline">\(\beta_i = \mu_i - \mu\)</span> is interpreted as the effect of group <span class="math inline">\(i\)</span> — that is, the difference between the population mean for group <span class="math inline">\(i\)</span>, <span class="math inline">\(\mu_i\)</span>, and the global population mean, <span class="math inline">\(\mu\)</span>.</li>
</ul>
<p>The interpretation of <span class="math inline">\(\beta_0\)</span> follows from the constraint:
<span class="math display">\[
\begin{aligned}
\beta_1 + \beta_2 + \beta_3 &amp;= 0 \\
(\mu_1 - \beta_0) + (\mu_2 - \beta_0) + (\mu_3 - \beta_0) &amp;= 0 \\
\mu_1 + \mu_2 + \mu_3 &amp;= 3 \beta_0 \\
\beta_0 &amp;= \frac{\mu_1 + \mu_2 + \mu_3}{3} = \mu
\end{aligned}
\]</span>
which shows that <span class="math inline">\(\beta_0\)</span> corresponds to the global mean, i.e. the average of the three group means.</p>
<p>The treatment effect represents the deviation between the mean response produced by treatment <span class="math inline">\(i\)</span> and the global mean:
<span class="math display">\[
\beta_i = \mu_i - \beta_0 = \mu_i - \mu
\]</span>
If the treatment effect is positive (negative), the <span class="math inline">\(i\)</span>th treatment produces an increase (decrease) in the mean response.</p>
<p>Typically, software doesn’t return the last <span class="math inline">\(\beta_3\)</span> as this can be found using the side constraint
<span class="math display">\[
\begin{aligned}
\beta_1 + \beta_2 + \beta_3 &amp;= 0 \\
\beta_3 = - (\beta_1 + \beta_2 )
\end{aligned}
\]</span>
Each group mean is found as:</p>
<ul>
<li><span class="math inline">\(\mu_1 = \beta_0 + \beta_1\)</span></li>
<li><span class="math inline">\(\mu_2 = \beta_0 + \beta_2\)</span></li>
<li><span class="math inline">\(\mu_3 = \beta_0 + \beta_3 = \beta_0 - (\beta_1 + \beta_2) = \beta_0 - \beta_1 - \beta_2\)</span></li>
</ul>
<p><br></p>
<p>In practice, this is done by fitting the linear regression model</p>
<p><span class="math display">\[
y 
= b_0 
+ b_1 \ \text{EffectLevel1} 
+ b_2 \ \text{EffectLevel2} 
+ \epsilon
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\text{EffectLevel1} = \begin{cases}
1  &amp; \text{if observation is from category 1} \\
0  &amp; \text{if observation is from category 2} \\
-1 &amp; \text{otherwise}
\end{cases}
\\
\text{EffectLevel2} = \begin{cases}
1  &amp; \text{if observation is from category 2} \\
0  &amp; \text{if observation is from category 1} \\
-1 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>Schematically,</p>
<p><span class="math display">\[
\begin{matrix}
\textbf{Level}  &amp; \textbf{EffectLevel1} &amp; \textbf{EffectLevel2} \\
\hline
\text{Classical Music} &amp; 1   &amp; 0    \\
\text{No Music}        &amp; 0   &amp; 1    \\
\text{Pop Music}       &amp; -1  &amp; -1
\end{matrix}
\]</span></p>
<p>In R this is simply done by saying:</p>
<pre class="r"><code>contrasts(rest_spend$type) &lt;- &quot;contr.sum&quot;
mdl_sum &lt;- lm(amount ~ 1 + type, data = rest_spend) # or: lm(amount ~ type, data = rest_spend)
coef(mdl_sum)</code></pre>
<pre><code>## (Intercept)       type1       type2 
##  22.7381560   1.4359846  -0.5967688</code></pre>
<p>where <code>type</code> is a factor. In such case R will automatically create the two variables <code>EffectLevel1</code> and <code>EffectLevel2</code> for you!</p>
<p>The <code>summary(mdl)</code> will return 3 estimated coefficients:</p>
<ul>
<li><span class="math inline">\(b_0 = 22.74\)</span> is estimated overall mean</li>
<li><span class="math inline">\(b_1 = 1.44\)</span> is the effect of Classical Music</li>
<li><span class="math inline">\(b_2 = -0.6\)</span> is the effect of No Music</li>
<li><strong>NOTE</strong>: The effect of Pop Music is not shown by <code>summary</code> as it is found via the side-constraint as <span class="math inline">\(b_3 = -(b_1 + b_2) = -0.84\)</span>!</li>
</ul>
</div>
<div id="reference-group-constraint" class="section level3">
<h3>Reference group constraint</h3>
<p>Under the constraint <span class="math inline">\(\beta_1 = 0\)</span>, meaning that the first factor level is the reference group,</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is interpreted as <span class="math inline">\(\mu_1\)</span>, the mean response for the reference group (group 1);</li>
<li><span class="math inline">\(\beta_i\)</span> is interpreted as the difference between the mean response for group <span class="math inline">\(i\)</span> and the reference group.</li>
</ul>
<p>Roughly speaking, <span class="math inline">\(\beta_i\)</span> can still be interpreted as the “treatment effect,” but compared to a reference category: typically a control group or placebo.</p>
<p>The interpretation of <span class="math inline">\(\beta_0\)</span> follows from:
<span class="math display">\[
\begin{aligned}
\beta_1 &amp;= 0 \\
\mu_1 - \beta_0 &amp;= 0 \\
\beta_0 &amp;= \mu_1
\end{aligned}
\]</span></p>
<p>The interpretation of the <span class="math inline">\(\beta_i\)</span>s follows from:
<span class="math display">\[
\begin{aligned}
\beta_i = \mu_i - \beta_0 = \mu_i - \mu_1
\end{aligned}
\]</span>
showing that it is the deviation between the mean response in group <span class="math inline">\(i\)</span> and the mean response in the reference group.</p>
<p>As <span class="math inline">\(\beta_1 = 0\)</span>, each group mean is found as:</p>
<ul>
<li><span class="math inline">\(\mu_1 = \beta_0\)</span></li>
<li><span class="math inline">\(\mu_2 = \beta_0 + \beta_2\)</span></li>
<li><span class="math inline">\(\mu_3 = \beta_0 + \beta_3\)</span></li>
</ul>
<p><br></p>
<p>In practice, this is done by fitting the linear regression model</p>
<p><span class="math display">\[
y 
= b_0 
+ b_1 \ \text{IsTypeNoMusic} 
+ b_2 \ \text{IsTypePopMusic} 
+\epsilon
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\text{IsTypeNoMusic} = \begin{cases}
1 &amp; \text{if observation is from the No Music category} \\
0 &amp; \text{otherwise}
\end{cases}
\\
\text{IsTypePopMusic} = \begin{cases}
1 &amp; \text{if observation is from the Pop Music category} \\
0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>Schematically,</p>
<p><span class="math display">\[
\begin{matrix}
\textbf{Level}  &amp; \textbf{IsTypeNoMusic} &amp; \textbf{IsTypePopMusic} \\
\hline
\text{Classical Music} &amp; 0   &amp; 0   \\
\text{No Music}        &amp; 1   &amp; 0   \\
\text{Pop Music}       &amp; 0   &amp; 1
\end{matrix}
\]</span></p>
<p>In R this is simply done by saying:</p>
<pre class="r"><code>contrasts(rest_spend$type) &lt;- &quot;contr.treatment&quot;
mdl_trt &lt;- lm(amount ~ 1 + type, data = rest_spend) # or: lm(amount ~ type, data = rest_spend)
coef(mdl_trt)</code></pre>
<pre><code>##   (Intercept)  typeNo Music typePop Music 
##     24.174141     -2.032753     -2.275200</code></pre>
<p>where <code>type</code> is a factor. In such case R will automatically create the two dummy variables <code>IsTypeNoMusic</code> and <code>IsTypePopMusic</code> for you!</p>
<p>The <code>summary(mdl)</code> will return 3 estimated coefficients:</p>
<ul>
<li><span class="math inline">\(b_0 = 24.17\)</span> is the mean of the base level (level 1)</li>
<li><span class="math inline">\(b_1 = -2.03\)</span> is the effect of No Music</li>
<li><span class="math inline">\(b_2 = -2.28\)</span> is the effect of Pop Music</li>
<li><strong>NOTE</strong>: The effect of Classical Music is not shown as it is equal to zero by the constraint!</li>
</ul>
<p><br></p>
<div class="yellow">
<p><strong>IMPORTANT</strong></p>
<ul>
<li><p>By default R uses the reference group constraint</p></li>
<li><p>If your factor has <span class="math inline">\(g\)</span> levels, your regression model will have <span class="math inline">\(g-1\)</span> dummy variables (R creates them for you)</p></li>
</ul>
</div>
</div>
</div>
</div>
<div id="anova-f-test" class="section level1">
<h1>ANOVA F-test</h1>
<p>By default, R uses the reference group constraint. In this section and the next one, we will not specify any side-constraints, meaning that <span class="math inline">\(\beta_1 = 0\)</span>.</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Under the <strong>reference group constraint</strong>, the interpretation of the model coefficients is as follows:
<span class="math display">\[
\mu_1 = \beta_0, \qquad
\mu_2 = \beta_0 + \beta_2, \qquad
\mu_3 = \beta_0 + \beta_3
\]</span></p>
<p>Show that under the reference group constraint, the null hypothesis of the F-test for model utility is equivalent to the ANOVA null hypothesis. In other words, demonstrate that
<span class="math display">\[
H_0: \beta_2 = \beta_3 = 0
\]</span>
is equivalent to
<span class="math display">\[
H_0 : \mu_1 = \mu_2 = \mu_3
\]</span></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-140" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-140&#39;, &#39;sol-start-140&#39;)"></span>
</div>
<div id="sol-body-140" class="solution-body" style="display: none;">
<p>This requires substituting the definition of the <span class="math inline">\(\beta_i\)</span>s:
<span class="math display">\[
\begin{aligned}
H_0 &amp;: \beta_2 = \beta_3 = 0 \\
H_0 &amp;: \mu_2 - \beta_0 = \mu_3 - \beta_0 = 0 \\
H_0 &amp;: \mu_2 - \mu_1 = \mu_3 - \mu_1 = 0  \qquad &amp;\text{Next, we add } \mu_1 \text{ everywhere}\\
H_0 &amp;: \mu_2 = \mu_3 = \mu_1 \qquad &amp;\text{Next, we reorder}\\
H_0 &amp;: \mu_1 = \mu_2 = \mu_3
\end{aligned}
\]</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Fit a linear model to the data, having <code>amount</code> as response variable and the factor <code>type</code> as predictor. Call the fitted model <code>mdl_rg</code> (for reference group constraint, which R uses by default!)</p>
<p>Identify the relevant pieces of information from the commands <code>anova(mdl_rg)</code> and <code>summary(mdl_rg)</code> that can be used to conduct an ANOVA F-test against the null hypothesis that all population means are equal.</p>
<p>Interpret the F-test results in the context of the ANOVA null hypothesis.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-141" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-141&#39;, &#39;sol-start-141&#39;)"></span>
</div>
<div id="sol-body-141" class="solution-body" style="display: none;">
<pre class="r"><code>mdl_rg &lt;- lm(amount ~ type, data = rest_spend)
mdl_rg</code></pre>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Coefficients:
##   (Intercept)   typeNo Music  typePop Music  
##        24.174         -2.033         -2.275</code></pre>
<pre class="r"><code>summary(mdl_rg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    24.1741     0.2593  93.211  &lt; 2e-16 ***
## typeNo Music   -2.0328     0.3668  -5.542 5.81e-08 ***
## typePop Music  -2.2752     0.3668  -6.203 1.53e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<pre class="r"><code>anova(mdl_rg)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: amount
##            Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## type        2  374.7 187.348  23.211 3.335e-10 ***
## Residuals 357 2881.5   8.071                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The model summary returns the F-test of model utility which, in this case, corresponds to the ANOVA F-test against the null hypothesis of equal population means.</p>
<p>The relevant line from <code>summary()</code> is:</p>
<pre><code>F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The relevant parts from <code>anova()</code> are:</p>
<ul>
<li><code>F value</code> of <code>23.211</code></li>
<li>The <code>Df</code> column giving <code>2</code> and <code>357</code> degrees of freedom</li>
<li>The p-value of the test, reported under <code>Pr(&gt;F)</code> as <code>3.335e-10 ***</code>.</li>
</ul>
<p>Recall that 3.335e-10 simply means <span class="math inline">\(3.335 \times 10^{-10}\)</span>. That is, “e” means 10 to the power of…</p>
<p>We can write this up as follows:</p>
<div class="int">
<p>We performed an analysis of variance against the null hypothesis of equal population mean spending across three types of background music, <span class="math inline">\(F(2, 357) = 23.21\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
<p>The large observed F statistic leads to a very small p-value, meaning that such a large observed variability among the mean restaurant spending across the different music types, compared to the variability in the residuals, is very unlikely to happen by chance alone if the population means where all the same.</p>
<p>For this reason, at the 5% significance level we reject the null hypothesis as there is very strong evidence that at least two population means differ.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="reference-group-constraint-1" class="section level1">
<h1>Reference group constraint</h1>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Examine and investigate the meaning of the coefficients in the output of <code>summary(mdl_rg)</code></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-142" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-142&#39;, &#39;sol-start-142&#39;)"></span>
</div>
<div id="sol-body-142" class="solution-body" style="display: none;">
<p>Let’s recall the model summary:</p>
<pre class="r"><code>summary(mdl_rg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    24.1741     0.2593  93.211  &lt; 2e-16 ***
## typeNo Music   -2.0328     0.3668  -5.542 5.81e-08 ***
## typePop Music  -2.2752     0.3668  -6.203 1.53e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The interpretation is as follows</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Coefficient</th>
<th align="center">Estimate</th>
<th align="center">Corresponds to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">24.1741</td>
<td align="center"><span class="math inline">\(\hat \beta_0 = \hat \mu_1\)</span></td>
</tr>
<tr class="even">
<td align="center">typeNo Music</td>
<td align="center">-2.0328</td>
<td align="center"><span class="math inline">\(\hat \beta_2 = \hat \mu_2 - \hat \beta_0 = \hat \mu_2 - \hat \mu_1\)</span></td>
</tr>
<tr class="odd">
<td align="center">typePop Music</td>
<td align="center">-2.2752</td>
<td align="center"><span class="math inline">\(\hat \beta_3 = \hat \mu_3 - \hat \beta_0 = \hat \mu_3 - \hat \mu_1\)</span></td>
</tr>
</tbody>
</table>
<p>The estimate corresponding to (Intercept) contains <span class="math inline">\(\hat \beta_0 = \hat \mu_1 = 24.17\)</span>. The estimated average spending for those having a classical music background is approximately £24.2.</p>
<p>This is because by default R uses <code>contr.treatment</code> and the first level of the factor is the reference group.
R always orders factor levels alphabetically unless you specifically change them.
To check the levels of a factor, we use the <code>levels()</code> function. As you can see below, <code>Classical Music</code> appears first and hence is used by R as reference group.</p>
<pre class="r"><code>levels(rest_spend$type)</code></pre>
<pre><code>## [1] &quot;Classical Music&quot; &quot;No Music&quot;        &quot;Pop Music&quot;</code></pre>
<p>The next estimate corresponds to <code>typeNo Music</code> and is <span class="math inline">\(\hat \beta_2 = -2.033\)</span>. The difference in mean spending between <code>No Music</code> and <code>Classical Music</code> is estimated to be <span class="math inline">\(-2.033\)</span>. In other words, people with a silent background seem to spend approximately £2 less than those having a classical music background.</p>
<p>The estimate corresponding to <code>typePop Music</code> is <span class="math inline">\(\hat \beta_3 = -2.275\)</span>. This is the estimated difference in mean spending between <code>Pop Music</code> and <code>Classical Music</code>. People with a pop music background seem to spend approximately £2.3 less than those with a classical music background.</p>
<p>Hence, for all levels except the reference group we see differences to the reference group while the estimate of the reference level can be found next to <code>(Intercept)</code>.</p>
<p>It is also important to notice how the coefficients names are written. They are a combination of <code>factor name</code> and <code>level name</code>, such as <code>typeNo Music</code>.
The only coefficient that is missing is <code>typeClassical Music</code>, the one corresponding to the reference category <code>Classical Music</code>.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>The function <code>dummy.coef()</code> returns the coefficients for <strong>all groups</strong>, including the reference category.</p>
<p>Run the <code>dummy.coef()</code> function on the fitted model, and examine the output.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-143" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-143&#39;, &#39;sol-start-143&#39;)"></span>
</div>
<div id="sol-body-143" class="solution-body" style="display: none;">
<pre class="r"><code>dummy.coef(mdl_rg)</code></pre>
<pre><code>## Full coefficients are 
##                                                    
## (Intercept):           24.17414                    
## type:           Classical Music  No Music Pop Music
##                        0.000000 -2.032753 -2.275200</code></pre>
<p>The output of <code>dummy.coef()</code> is written in terms of the reference group mean and the additive effect of each group.</p>
<ul>
<li>We obtain the predicted mean of for “Classical Music” by adding 24.17414 and 0. The result, 24.17414, can be written as <span class="math inline">\(\hat \mu_\text{Classical Music} = \hat \mu_1 = 24.17\)</span></li>
<li>We obtain the predicted mean of for “No Music” by adding 24.17414 and -2.032753. The result, 22.14139, can be written as <span class="math inline">\(\hat \mu_\text{No Music} = \hat \mu_2 = 22.14\)</span></li>
<li>We obtain the predicted mean of for “Pop Music” by adding 24.17414 and -2.275200. The result, 21.89894, can be written as <span class="math inline">\(\hat \mu_\text{Pop Music} = \hat \mu_3 = 21.90\)</span></li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Obtain the estimated (or predicted) group means for the “Classical Music,” “No Music,” and “Pop Music” groups by using the <code>predict(mdl_rg, newdata = ...)</code> function.</p>
<p>Compare the output of the <code>predict()</code> function with that from <code>dummy.coef()</code>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-144" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-144&#39;, &#39;sol-start-144&#39;)"></span>
</div>
<div id="sol-body-144" class="solution-body" style="display: none;">
<p>Define a data frame with a column having the same name as the factor in the fitted model.
Then, specify all the groups (= levels) for which you would like the predicted mean.</p>
<pre class="r"><code>query_groups &lt;- tibble(type = c(&quot;Classical Music&quot;, &quot;No Music&quot;, &quot;Pop Music&quot;))
query_groups</code></pre>
<pre><code>## # A tibble: 3 x 1
##   type           
##   &lt;chr&gt;          
## 1 Classical Music
## 2 No Music       
## 3 Pop Music</code></pre>
<p>Pass the data frame to the predict function using the <code>newdata =</code> argument. The predict function will match the column named <code>type</code> with the predictor called <code>type</code> in the fitted model <code>mdl_rg</code>.</p>
<pre class="r"><code>predict(mdl_rg, newdata = query_groups)</code></pre>
<pre><code>##        1        2        3 
## 24.17414 22.14139 21.89894</code></pre>
<p>Or:</p>
<pre class="r"><code>query_groups %&gt;%
  mutate(pred = predict(mdl_rg, newdata = .))</code></pre>
<pre><code>## # A tibble: 3 x 2
##   type             pred
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 Classical Music  24.2
## 2 No Music         22.1
## 3 Pop Music        21.9</code></pre>
<p>Hence,</p>
<ul>
<li><span class="math inline">\(\hat \mu_\text{Classical Music} = \hat \mu_1 = 24.17\)</span></li>
<li><span class="math inline">\(\hat \mu_\text{No Music} = \hat \mu_2 = 22.14\)</span></li>
<li><span class="math inline">\(\hat \mu_\text{Pop Music} = \hat \mu_3 = 21.90\)</span></li>
</ul>
<p>While <code>predict()</code> directly returns the group means, the <code>dummy.coef()</code> function returns the estimates for each model coefficient.
Hence we have the estimated mean for the reference group, and the additive effects for each group. The additive effect for the reference category is shown as 0 (as the side-constraint is <span class="math inline">\(\beta_1 = 0\)</span>).</p>
<p>However, by adding the mean of the reference category and each group effect, we obtain the same means as those returned by <code>predict()</code>.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>It actually makes more sense to have “No Music” as reference group.</p>
<p>Open the help page of the function <code>fct_relevel()</code>, and look at the examples.</p>
<p>Within the <code>rest_sped</code> data, reorder the levels of the factor <code>type</code> so that your reference group is “No Music.”</p>
<div class="yellow">
<p><strong>NOTE</strong></p>
<p>Because you reordered the levels, now</p>
<ul>
<li><span class="math inline">\(\mu_1\)</span> = mean of no music group</li>
<li><span class="math inline">\(\mu_2\)</span> = mean of classical music group</li>
<li><span class="math inline">\(\mu_3\)</span> = mean of pop music group</li>
</ul>
</div>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-145" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-145&#39;, &#39;sol-start-145&#39;)"></span>
</div>
<div id="sol-body-145" class="solution-body" style="display: none;">
<p>Check the help page:</p>
<pre class="r"><code>?fct_relevel</code></pre>
<p>Select “No Music” to be the first level:</p>
<pre class="r"><code>rest_spend$type &lt;- fct_relevel(rest_spend$type, &quot;No Music&quot;)</code></pre>
<p>Check that the factor levels are now in the correct order:</p>
<pre class="r"><code>levels(rest_spend$type)</code></pre>
<pre><code>## [1] &quot;No Music&quot;        &quot;Classical Music&quot; &quot;Pop Music&quot;</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>Refit the linear model, and inspect the model summary once more.</p>
<p>Do you notice any change in the estimated coefficients?</p>
<p>Do you notice any change in the F-test for model utility?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-146" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-146&#39;, &#39;sol-start-146&#39;)"></span>
</div>
<div id="sol-body-146" class="solution-body" style="display: none;">
<pre class="r"><code>mdl_rg &lt;- lm(amount ~ type, data = rest_spend)
summary(mdl_rg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          22.1414     0.2593  85.373  &lt; 2e-16 ***
## typeClassical Music   2.0328     0.3668   5.542 5.81e-08 ***
## typePop Music        -0.2424     0.3668  -0.661    0.509    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The displayed coefficients have changed as now the (Intercept) represents the new reference group, which is “No Music.”</p>
<p>However, by doing the calculations, this model is equivalent to the previous one as the predicted group means are the same.</p>
<ul>
<li>Predicted mean of “No Music” <span class="math inline">\(\hat \mu_\text{No Music}\)</span> = 22.1414</li>
<li>Predicted mean of “Classical Music” <span class="math inline">\(\hat \mu_\text{Classical Music}\)</span> = 22.1414 + 2.0328 = 24.1742</li>
<li>Predicted mean of “Pop Music” = <span class="math inline">\(\hat \mu_\text{Pop Music}\)</span> = 22.1414 - 0.2424 = 21.899</li>
</ul>
<p>In fact, the <code>predict</code> function returns the same output:</p>
<pre class="r"><code>query_groups &lt;- tibble(type = levels(rest_spend$type))
query_groups</code></pre>
<pre><code>## # A tibble: 3 x 1
##   type           
##   &lt;chr&gt;          
## 1 No Music       
## 2 Classical Music
## 3 Pop Music</code></pre>
<pre class="r"><code>query_groups %&gt;% 
  mutate(pred = predict(mdl_rg, newdata = .))</code></pre>
<pre><code>## # A tibble: 3 x 2
##   type             pred
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 No Music         22.1
## 2 Classical Music  24.2
## 3 Pop Music        21.9</code></pre>
<p>Also the <code>dummy.coef()</code> function leads to the same predictions, however, the displayed coefficients vary slightly as the reference group is now “No Music.”</p>
<p>In fact, its coefficient is now 0, which is the reference group constraint (<span class="math inline">\(\beta_1 = 0\)</span>):</p>
<pre class="r"><code>dummy.coef(mdl_rg)</code></pre>
<pre><code>## Full coefficients are 
##                                                      
## (Intercept):      22.14139                           
## type:             No Music Classical Music  Pop Music
##                  0.0000000       2.0327533 -0.2424471</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Let’s compare some population means…</p>
<p>Interpret the results of the t-test for the significance of the model coefficients.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-147" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-147&#39;, &#39;sol-start-147&#39;)"></span>
</div>
<div id="sol-body-147" class="solution-body" style="display: none;">
<pre class="r"><code>summary(mdl_rg)</code></pre>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          22.1414     0.2593  85.373  &lt; 2e-16 ***
## typeClassical Music   2.0328     0.3668   5.542 5.81e-08 ***
## typePop Music        -0.2424     0.3668  -0.661    0.509    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The first row reports the t-value and p-value to test:
<span class="math display">\[
H_0: \mu_1 = 0 \quad vs \quad H_1 : \mu_1 \neq 0
\]</span></p>
<div class="int">
<p>We performed a t-test against <span class="math inline">\(H_0: \mu_1 = 0\)</span>, which resulted in <span class="math inline">\(t(357) = 85.373, p &lt; .001\)</span>, two-sided).
At the 5% significance level, there is very strong evidence that the population mean restaurant spending for those with a silent background is not zero.</p>
</div>
<p><br></p>
<p>The second row reports the t-value and p-value to test:
<span class="math display">\[
H_0: \mu_2 - \mu_1 = 0 \quad vs \quad H_1 : \mu_2 - \mu_1 \neq 0
\]</span>
or</p>
<p><span class="math display">\[
H_0: \mu_2 = \mu_1 \quad vs \quad H_1 : \mu_2 \neq \mu_1
\]</span></p>
<div class="int">
<p>We performed a t-test against <span class="math inline">\(H_0: \mu_2 = \mu_1\)</span>, which resulted in <span class="math inline">\(t(357) = 5.542, p &lt; .001\)</span>, two-sided.
At the 5% significance level, there is very strong evidence that the population mean restaurant spending for those with a classical music background is not equal to those with a silent background.</p>
</div>
<p><br></p>
<p>The third and last row reports the t-value and p-value to test:
<span class="math display">\[
H_0: \mu_3 - \mu_1 = 0 \quad vs \quad H_1 : \mu_3 - \mu_1 \neq 0
\]</span>
or</p>
<p><span class="math display">\[
H_0: \mu_3 = \mu_1 \quad vs \quad H_1 : \mu_3 \neq \mu_1
\]</span></p>
<div class="int">
<p>We performed a t-test against <span class="math inline">\(H_0: \mu_3 = \mu_1\)</span>, which resulted in <span class="math inline">\(t(357) = -0.661, p = 0.509\)</span>, two-sided.
At the 5% significance level, there is not sufficient evidence to reject the null hypothesis that the population mean restaurant spending for those with a pop music background is the same as those with a silent background.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="sum-to-zero-constraint-1" class="section level1">
<h1>Sum-to-zero Constraint</h1>
<p>Let’s now change the side-constraint from the R default, the reference group or <code>contr.treatment</code> constraint, to the sum-to-zero constraint.</p>
<p>Recall that under this constraint the interpretation of the coefficients becomes:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> represents the global mean</li>
<li><span class="math inline">\(\beta_i\)</span> the effect due to group <span class="math inline">\(i\)</span> — that is, the mean response in group <span class="math inline">\(i\)</span> minus the global mean</li>
</ul>
<div class="yellow">
<p><strong>We set the sum-to-zero side constraint by saying</strong></p>
<pre class="r"><code>contrasts(rest_spend$type) &lt;- &quot;contr.sum&quot;</code></pre>
</div>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>Set the sum to zero constraint for the factor <code>type</code> of background music.</p>
<p>Fit again the linear model using <code>amount</code> as response variable and <code>type</code> as predictor. Call the fitted model using the sum to zero constraint <code>mdl_stz</code>.</p>
<p>Examine the output of the <code>summary(mdl_stz)</code> function:</p>
<ul>
<li>Do the displayed coefficients change? What do they represent now?</li>
<li>Do the predicted group means change?</li>
<li>Is the model utility F-test still the same? Why do you think it’s the case?</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-148" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-148&#39;, &#39;sol-start-148&#39;)"></span>
</div>
<div id="sol-body-148" class="solution-body" style="display: none;">
<p>Set the sum to zero contrast to the <code>type</code> factor:</p>
<pre class="r"><code>contrasts(rest_spend$type) &lt;- &quot;contr.sum&quot;</code></pre>
<p>Re-fit the model and inspect the summary output:</p>
<pre class="r"><code>mdl_stz &lt;- lm(amount ~ type, data = rest_spend)
summary(mdl_stz)</code></pre>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  22.7382     0.1497 151.856  &lt; 2e-16 ***
## type1        -0.5968     0.2118  -2.818   0.0051 ** 
## type2         1.4360     0.2118   6.781 4.95e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>With the new side-constraint, we get different values for the model coefficients because the meaning of the parameters has changed.
If we closely inspect the output, we can also notice that a slightly different naming has been used.</p>
<p>Instead of <code>factor name</code> and <code>level name</code> (such as <code>typeNo Music</code>), we get <code>factor name</code> and <code>level number</code> (e.g. <code>type1</code>).
Here, <code>type1</code> simply means the first level of the factor <code>type</code>, while <code>type2</code> means the second level of the factor <code>type</code>.</p>
<pre class="r"><code>levels(rest_spend$type)</code></pre>
<pre><code>## [1] &quot;No Music&quot;        &quot;Classical Music&quot; &quot;Pop Music&quot;</code></pre>
<p>The first level is “No Music,” while the second level is “Classical Music.”</p>
<ul>
<li>The estimate for <code>(Intercept)</code> is now the global mean of the data.</li>
<li>The estimate for <code>type1</code> is now the difference of the first group (“No Music”) to the global mean</li>
<li>The estimate for <code>type2</code> is now the difference of the second group (“Classical Music”) to the global mean</li>
</ul>
<p>The estimate for <code>type3</code>, representing the difference of “Pop Music” to the global mean is not shown. Because of the side-constraint, we know it must be <span class="math inline">\(\beta_3 = - (\beta_1 + \beta_2) = - (-0.5968 + 1.4360) = -0.8392\)</span>.</p>
<p><br></p>
<p>As before, we can get all model coefficients calling <code>dummy.coef()</code>:</p>
<pre class="r"><code>dummy.coef(mdl_stz)</code></pre>
<pre><code>## Full coefficients are 
##                                                      
## (Intercept):      22.73816                           
## type:             No Music Classical Music  Pop Music
##                 -0.5967688       1.4359846 -0.8392158</code></pre>
<p>The <code>dummy.coef()</code> function shows that the (Intercept), that is <span class="math inline">\(\hat \beta_0\)</span>, represents the global mean.</p>
<p>Underneath we see the group effects that need to be added to the global mean to obtain the predicted group means.</p>
<p><br></p>
<p>Compute the predicted group means:</p>
<pre class="r"><code>query_groups %&gt;%
  mutate(pred = predict(mdl_stz, newdata = .))</code></pre>
<pre><code>## # A tibble: 3 x 2
##   type             pred
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 No Music         22.1
## 2 Classical Music  24.2
## 3 Pop Music        21.9</code></pre>
<p>We notice that we get the same predicted group means independently of the side-constraint.</p>
<p>The predicted means do <em>not</em> depend on the side-constraint that we employ. However, the side-constraint affects the meaning of the parameters in the model.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 15
</div>
<div class="question-body">
<p>Let’s do more hypothesis tests on the population means…</p>
<p>Interpret the results of the t-tests on the coefficients of the model fitted using the sum to zero side-constraint.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-149" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-149&#39;, &#39;sol-start-149&#39;)"></span>
</div>
<div id="sol-body-149" class="solution-body" style="display: none;">
<pre class="r"><code>summary(mdl_stz)</code></pre>
<pre><code>## 
## Call:
## lm(formula = amount ~ type, data = rest_spend)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.433 -1.886  0.127  1.755 11.285 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  22.7382     0.1497 151.856  &lt; 2e-16 ***
## type1        -0.5968     0.2118  -2.818   0.0051 ** 
## type2         1.4360     0.2118   6.781 4.95e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.841 on 357 degrees of freedom
## Multiple R-squared:  0.1151, Adjusted R-squared:  0.1101 
## F-statistic: 23.21 on 2 and 357 DF,  p-value: 3.335e-10</code></pre>
<p>The first row reports the t-value and p-value to test:
<span class="math display">\[
H_0: \beta_0 = 0 \quad vs \quad H_1 : \beta_0 \neq 0
\]</span></p>
<div class="int">
<p>We performed a t-test against <span class="math inline">\(H_0: \beta_0 = 0\)</span>, which resulted in <span class="math inline">\(t(357) = 151.856, p &lt; .001\)</span>, two-sided).
At the 5% significance level, there is very strong evidence that the overall mean restaurant spending across the three types of background music is not zero.</p>
</div>
<p><br></p>
<p>The second row reports the t-value and p-value to test:
<span class="math display">\[
H_0: \mu_1 - \beta_0 = 0 \quad vs \quad H_1 : \mu_1 - \beta_0 \neq 0
\]</span>
or</p>
<p><span class="math display">\[
H_0: \mu_1 = \beta_0 \quad vs \quad H_1 : \mu_1 \neq \beta_0
\]</span></p>
<div class="int">
<p>We performed a t-test against <span class="math inline">\(H_0: \mu_1 = \beta_0\)</span>, which resulted in <span class="math inline">\(t(357) = -2.818, p = .005\)</span>, two-sided.
At the 5% significance level, there is strong evidence that the population mean restaurant spending for those with a silent background is not equal to the global mean restaurant spending.</p>
</div>
<p><br></p>
<p>The third and last row reports the t-value and p-value to test:
<span class="math display">\[
H_0: \mu_2 - \beta_0 = 0 \quad vs \quad H_1 : \mu_2 - \beta_0 \neq 0
\]</span>
or</p>
<p><span class="math display">\[
H_0: \mu_2 = \beta_0 \quad vs \quad H_1 : \mu_2 \neq \beta_0
\]</span></p>
<div class="int">
<p>We performed a t-test against <span class="math inline">\(H_0: \mu_2 = \beta_0\)</span>, which resulted in <span class="math inline">\(t(357) = 6.781, p &lt; .001\)</span>, two-sided.
At the 5% significance level, there is very strong evidence that the population mean restaurant spending for those with a classical music background is different than the overall mean restaurant spending.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="yellow">
<p><strong>We can switch back to the default reference group constraint by either of these</strong></p>
<pre class="r"><code># Option 1
contrasts(rest_spend$type) &lt;- NULL
# Option 2
contrasts(rest_spend$type) &lt;- &quot;contr.treatment&quot;</code></pre>
</div>
</div>
<div id="contrasts" class="section level1">
<h1>Contrasts</h1>
<p>When the ANOVA F-test against the null hypothesis <span class="math inline">\(H_0: \mu_1 = \mu_2 = \cdots = \mu_g\)</span> is rejected, it tells us that there are significant differences between at least two of the group means.
However, it does not tells us which particular population means are different.
Further investigation should be conducted to find out exactly which population means differ. In some cases the investigator will have preplanned comparisons they would like to make; in other situations they may have no idea what differences to look for.</p>
<div class="yellow">
<p><strong>Contrasts</strong> represent a wide range of hypotheses about the population means that can be tested using the fitted model.</p>
<p>However, they need to match the following general form. A contrast only allows us to test hypotheses that can be written as a linear combination of the population means with coefficients summing to zero:
<span class="math display">\[
H_0 : c_1 \mu_1 + c_2 \mu_2 + c_3 \mu_3 = 0 \qquad \text{with} \qquad c_1 + c_2 + c_3 = 0
\]</span></p>
</div>
<p>We have already performed some simple contrasts by looking at the model coefficients under the reference group constraint.
Those represented pairwise comparisons between each group and the reference group.</p>
<p>However, say you wanted to test other hypotheses? Such as a combinations of two groups against a third group?</p>
<p>To do so, please install <strong>once for all</strong> the library <code>emmeans</code> via:</p>
<pre><code>install.packages(&quot;emmeans&quot;)</code></pre>
<p>Then, every time you want to use any of its functions, remember that you need to load it via</p>
<pre><code>library(emmeans)</code></pre>
<div class="question-begin">
Question 16
</div>
<div class="question-body">
<p>We were interested in the following comparisons:</p>
<ul>
<li>Whether having some kind of background music, rather than no music, makes a difference in mean restaurant spending</li>
<li>Whether there is any difference in mean restaurant spending between those with no background music and those with pop music</li>
</ul>
<p>These are planned comparisons and can be translated to the following research hypotheses:
<span class="math display">\[
\begin{aligned}
1. \quad H_0 &amp;: \mu_\text{No Music} = \frac{1}{2} (\mu_\text{Classical Music} + \mu_\text{Pop Music}) \\
2. \quad H_0 &amp;: \mu_\text{No Music} = \mu_\text{Pop Music}
\end{aligned}
\]</span></p>
<p>First of all check the levels of the factor <code>type</code>, as the contrast coefficients need to match the order of the levels:</p>
<pre class="r"><code>levels(rest_spend$type)</code></pre>
<pre><code>## [1] &quot;No Music&quot;        &quot;Classical Music&quot; &quot;Pop Music&quot;</code></pre>
<p>We specify the hypotheses by first giving each a name, and then specify the coefficients of the comparisons:</p>
<pre class="r"><code>comp &lt;- list(&quot;No Music - Some Music&quot; = c(1, -1/2, -1/2),
             &quot;No Music - Pop Music&quot; = c(1, 0, -1))</code></pre>
<p>Then, we load the <code>emmeans</code> package:</p>
<pre class="r"><code>library(emmeans)</code></pre>
<p>Use the <code>emmeans()</code> function to obtain the estimated treatment means and uncertainties for your factor:</p>
<pre class="r"><code>emm &lt;- emmeans(mdl_stz, ~ type)
emm</code></pre>
<pre><code>##  type            emmean    SE  df lower.CL upper.CL
##  No Music          22.1 0.259 357     21.6     22.7
##  Classical Music   24.2 0.259 357     23.7     24.7
##  Pop Music         21.9 0.259 357     21.4     22.4
## 
## Confidence level used: 0.95</code></pre>
<p>Next, we run the contrast analysis. To do so, we use the <code>contrast()</code> function:</p>
<pre class="r"><code>comp_res &lt;- contrast(emm, method = comp)
comp_res</code></pre>
<pre><code>##  contrast              estimate    SE  df t.ratio p.value
##  No Music - Some Music   -0.895 0.318 357 -2.818  0.0051 
##  No Music - Pop Music     0.242 0.367 357  0.661  0.5090</code></pre>
<p>Finally, we can ask for 95% confidence intervals:</p>
<pre class="r"><code>confint(comp_res)</code></pre>
<pre><code>##  contrast              estimate    SE  df lower.CL upper.CL
##  No Music - Some Music   -0.895 0.318 357   -1.520   -0.270
##  No Music - Pop Music     0.242 0.367 357   -0.479    0.964
## 
## Confidence level used: 0.95</code></pre>
<p>Interpret the result of the contrast analysis.</p>
<ul>
<li>What do the p-values tell us?</li>
<li>Interpret the confidence intervals in the context of the study.</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-150" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-150&#39;, &#39;sol-start-150&#39;)"></span>
</div>
<div id="sol-body-150" class="solution-body" style="display: none;">
<p>The hypothesis test for the first contrast could be reported as follows:</p>
<div class="int">
<p>We performed a test against <span class="math inline">\(H_0: \mu_1 - \frac{1}{2}(\mu_2 + \mu_3) = 0\)</span>, resulting in <span class="math inline">\(t(357) = -2.818, p = .005\)</span>, two-sided.
At the 5% significance level, there is strong evidence that the mean spending for those with no music is different than the mean spending for those with some of background music.</p>
</div>
<p>The 95% confidence interval for <span class="math inline">\(\mu_1 - \frac{1}{2}(\mu_2 + \mu_3)\)</span> is given by <span class="math inline">\([-1.520, -0.270]\)</span>.</p>
<p>The corresponding confidence interval could be written up as:</p>
<div class="int">
<p>We are 95% confident that diners with no background music will spend, on average, between £1.52 and £0.27 pounds less than those with some background music.</p>
</div>
<p><br></p>
<p>The hypothesis test for the second contrast could be reported as follows:</p>
<div class="int">
<p>We performed a test against <span class="math inline">\(H_0: \mu_1 - \mu_3 = 0\)</span>, resulting in <span class="math inline">\(t(357) = 0.661, p = .509\)</span>, two-sided.
At the 5% significance level, there is not sufficient evidence to reject the null hypothesis that the mean spending for those with no music is the same as the mean spending for those with pop music.</p>
</div>
<p>The 95% confidence interval for <span class="math inline">\(\mu_1 - \mu_3\)</span> is given by <span class="math inline">\([-0.479, 0.964]\)</span>.</p>
<p>Because we have established that there isn’t a significant difference between the mean spending for those with no music and those with pop music, we will not interpret the confidence interval.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-North2003" class="csl-entry">
North, A., A. Shilcock, and D. Hargreaves. 2003. <span>“The Effect of Musical Style on Restaurant Customers’ Spending.”</span> <em>Environment and Behavior</em> 35: 712–18.
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>The alternative hypothesis that “the means are not all
equal” should not be confused with “all the means are different.” With
10 groups we could have 9 means equal to each other and 1 different.
The null hypothesis would still be false.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Recall that the variance is the squared standard deviation.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
