<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Binary Logistic Regression</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Simple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_models.html">1/1: Functions and models</a>
    </li>
    <li>
      <a href="02_slr.html">1/2: Simple linear regression</a>
    </li>
    <li>
      <a href="03_slr_model_fit.html">1/3: Model Fit, Standardized Coefficients</a>
    </li>
    <li>
      <a href="04_slr_assumptions.html">1/4: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="05_slr_writeup.html">1/5: Writing-up</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multiple Linear Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="06_mlr.html">1/7: Basics</a>
    </li>
    <li>
      <a href="07_mlr_int.html">1/8: Interactions</a>
    </li>
    <li>
      <a href="08_mlr_assumpt.html">1/9: Assumptions &amp; Diagnostics</a>
    </li>
    <li>
      <a href="09_mlr_select.html">1/10: Model Fit, Model Comparison, Model Selection</a>
    </li>
    <li>
      <a href="10_mlr_report.html">1/11: Writing-up</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Experimental Data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="11_anova.html">2/1: ANOVA</a>
    </li>
    <li>
      <a href="11_anova.html">2/2: ANOVA (again)</a>
    </li>
    <li>
      <a href="12_factorial_anova.html">2/3: 2x2 ANOVA</a>
    </li>
    <li>
      <a href="13_multiplecomp.html">2/4: Multiple Comparisons</a>
    </li>
    <li class="dropdown-header">2/5: No exercises</li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced Topics for LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="14_bootstrap_reg.html">2/7: Bootstrap</a>
    </li>
    <li>
      <a href="15_binary_logistic.html">2/8: Binary Logistic Regression</a>
    </li>
    <li>
      <a href="16_more_about_logistic.html">2/9: More About Logistic Regression</a>
    </li>
    <li>
      <a href="17_power_regression.html">2/10: Sample Size and Power Analysis</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Help
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Binary Logistic Regression</h1>

</div>


<div id="flashcards" class="section level1">
<h1>Flashcards</h1>
<div class="optional-begin">
Simple linear regression<span id="opt-start-184" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-184&#39;, &#39;opt-start-184&#39;)"></span>
</div>
<div id="opt-body-184" class="optional-body" style="display: none;">
Consider again the wellbeing data:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
wellbeing
</th>
<th style="text-align:right;">
outdoor_time
</th>
<th style="text-align:right;">
social_int
</th>
<th style="text-align:left;">
location
</th>
<th style="text-align:left;">
routine
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
Suburb
</td>
<td style="text-align:left;">
Routine
</td>
</tr>
<tr>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
City
</td>
<td style="text-align:left;">
No Routine
</td>
</tr>
<tr>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
Suburb
</td>
<td style="text-align:left;">
Routine
</td>
</tr>
<tr>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
City
</td>
<td style="text-align:left;">
No Routine
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
Rural
</td>
<td style="text-align:left;">
No Routine
</td>
</tr>
<tr>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:left;">
Suburb
</td>
<td style="text-align:left;">
No Routine
</td>
</tr>
</tbody>
</table>
<p>Fitting the following regression model which predicts wellbeing from the time spent outdoors
<span class="math display">\[
\text{wellbeing}_i 
= \beta_0 
+ \beta_1 \ \text{outdoor_time}_i 
+ \epsilon_i
\]</span>
results in the following fitted line:
<img src="15_binary_logistic_files/figure-html/unnamed-chunk-2-1.png" width="85%" style="display: block; margin: auto;" /></p>
<p>In simple linear regression, we defined our model through a number of components:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> / <span class="math inline">\(b_0\)</span> / “the intercept.”
<ul>
<li>This is the predicted wellbeing when an individual spends 0 hours outdoors</li>
<li>It is where the regression line cuts the y-axis when x = 0.</li>
<li>It is the estimated expected value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>.</li>
</ul></li>
<li><span class="math inline">\(\beta_1\)</span> / <span class="math inline">\(b_1\)</span> / “the coefficient of <span class="math inline">\(\text{wellbeing}\)</span>.”
<ul>
<li>This is the predicted increase in the average wellbeing for every additional hour of outdoor time.<br />
</li>
<li>It is the estimated expected increase in <span class="math inline">\(y\)</span> for a one-unit increase in <span class="math inline">\(x\)</span>.</li>
</ul></li>
<li><span class="math inline">\(\epsilon\)</span> / <span class="math inline">\(e\)</span> / “the residuals” or “error term.”
<ul>
<li>Represents the deviations from the actual values to the model-predicted values. The standard deviation of all these gets denoted <span class="math inline">\(\sigma\)</span>.</li>
<li>In the plot above, these are the vertical distances from each red dot to the black line.</li>
</ul></li>
</ul>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
Multiple linear regression<span id="opt-start-185" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-185&#39;, &#39;opt-start-185&#39;)"></span>
</div>
<div id="opt-body-185" class="optional-body" style="display: none;">
<p>When we extended this to multiple regression, we essentially just added more explanatory variables, meaning we fitted more coefficients.</p>
<p>The values of <span class="math inline">\(y\)</span> are now modelled as some relationship of more than just one <span class="math inline">\(x\)</span> variable. In the case of two predictors, denote these by <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> respectively.</p>
<p>In the plot below with two predictors, we would have a slope for each predictor. Each coefficient represents the gradient of the regression surface along each dimension.</p>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-3-1.png" width="85%" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
Interactions<span id="opt-start-186" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-186&#39;, &#39;opt-start-186&#39;)"></span>
</div>
<div id="opt-body-186" class="optional-body" style="display: none;">
<p>We then saw how we can let the relationships between the outcome <span class="math inline">\(y\)</span> and an explanatory variable <span class="math inline">\(x_1\)</span> vary <em>as a function of</em> some other explanatory variable <span class="math inline">\(x_2\)</span>.</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1  \ x_{1i} + \beta_2 \ x_{2i} + \beta_3 \ (x_{1i} * x_{2i})+ \epsilon_i
\]</span></p>
<p>In the plot below, if someone asks you “what is the relationship between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x\)</span>, your reply should (hopefully) be”well, it depends on what the value of <span class="math inline">\(x_2\)</span> is"</p>
<p>This is captured in the curvature of the regression surface below, and we estimate it with a combination of 3 coefficients:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\beta_1\)</span>: the effect of <span class="math inline">\(x_1\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_2=0\)</span><br />
(this is the slope of the surface where it meets the <strong>front</strong> face of the cube)<br />
</li>
<li><span class="math inline">\(\beta_2\)</span>: the effect of <span class="math inline">\(x_2\)</span> on <span class="math inline">\(y\)</span> where <span class="math inline">\(x_1=0\)</span><br />
(this is the slope of the surface where it meets the <strong>left</strong> of face of the cube)<br />
</li>
<li><span class="math inline">\(\beta_3\)</span>: the amount to which (1) and (2) are adjusted when there is an increase in the other variable.</li>
</ol>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-4-1.png" width="85%" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
Categorical explanatory variables<span id="opt-start-187" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-187&#39;, &#39;opt-start-187&#39;)"></span>
</div>
<div id="opt-body-187" class="optional-body" style="display: none;">
<p>Throughout these, we also saw how this applied when we had explanatory variables that were <strong>categorical</strong>.</p>
<p>They were entered in to the model as a set of “dummy variables” (zeroes and ones), representing differences between groups. If we had a categorical variable which contained <span class="math inline">\(k\)</span> levels (or “groups,” or “categories”), then we R will put <span class="math inline">\(k-1\)</span> dummy variables into the model for us, and we will get out <span class="math inline">\(k-1\)</span> coefficients.</p>
<p>The default behaviour in R is that, depending on what we set as our <strong>reference level</strong>, the coefficients represent the difference from this group to each of the others.<br />
In the plots below, if “City” is the reference, then the coefficient <code>locationRural</code> would represent the vertical distance from the red line to the green line, and the coefficient <code>locationSuburb</code> would be the vertical distance from the red line to the blue line.</p>
<p><img src="images/glm/categ-vars.png" width="95%" style="display: block; margin: auto;" /></p>
<p><em>Note - because categorical predictors are coded as various dummy variables of zeroes and ones, the assumption of linearity is intrinsically there. The only possible way to get from the red line to the green line is via a straight line.</em></p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
ANOVA &amp; categorical interactions<span id="opt-start-188" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-188&#39;, &#39;opt-start-188&#39;)"></span>
</div>
<div id="opt-body-188" class="optional-body" style="display: none;">
<p>A linear model summary tells you whether <strong>each</strong> of the difference between the mean of the <span class="math inline">\(i\)</span>th group from the reference group mean is significant or not, e.g. <span class="math inline">\(\hat \beta_1 = \mu_2 - \mu_1\)</span>, <span class="math inline">\(\hat \beta_2 = \mu_3 - \mu_1\)</span>, <span class="math inline">\(\hat \beta_4 = \mu_3 - \mu_1\)</span>, and so on.
So, if you have <span class="math inline">\(k\)</span> groups, you will have <span class="math inline">\(k-1\)</span> such differences.</p>
<p>For the wellbeing example, we have 2 such differences (while the intercept is the mean for the reference group):</p>
<pre class="r"><code>wb_mdl &lt;- lm(wellbeing ~ location, data = mwdata)
summary(wb_mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = wellbeing ~ location, data = mwdata)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.571  -6.325   2.164   7.000  20.900 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      41.000      3.008  13.629 3.87e-14 ***
## locationRural     7.571      5.333   1.420    0.166    
## locationSuburb    1.100      4.756   0.231    0.819    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.65 on 29 degrees of freedom
## Multiple R-squared:  0.06759,    Adjusted R-squared:  0.003291 
## F-statistic: 1.051 on 2 and 29 DF,  p-value: 0.3625</code></pre>
<p>What if your question was not “Does the mean of group 3 differ from the mean of group 1?” which is answered by looking at the model <code>summary()</code>?</p>
<p>Say your question was “Does location impact wellbeing?” or “Is there a difference in wellbeing across the diffrent locations?”
This does not specify one specific location, but rather concerns checking whether there was a difference overall - that is, whether the mean wellbeing for city, rural and suburb are all equal or at least two differ.</p>
<p>This is where ANOVA comes in, which is run via <code>anova(&lt;fitted model&gt;)</code> and we have an F-test and the corresponding p-value.</p>
<pre class="r"><code>anova(wb_mdl)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: wellbeing
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## location   2  285.4  142.69  1.0512 0.3625
## Residuals 29 3936.6  135.75</code></pre>
<p>The first row tells us that the factor <code>outdoor_time</code> is not statistically significant, meaning that there is not enough evidence to reject the null hypothesis that the mean wellbeing is the same among the three different locations.</p>
<p><br></p>
<p>We just said that <code>anova()</code> returns a row for each predictor, testing whether the estimated mean response (wellbeing) differs among the three groups – that is, whether the mean response differs among the possible values of the predictor (location).</p>
<p>What if the predictor does not represent groups, but a continuous variable?
The idea is the same! Basically, we are testing whether at each <span class="math inline">\(x\)</span> value the estimated mean <span class="math inline">\(y\)</span> is the same. Imagine increasing the number of groups to really many… In other words, we are testing whether the line is flat, meaning that the predictor has no influence on the response.</p>
</div>
<p class="optional-end">
</p>
</div>
<div id="binary-data" class="section level1">
<h1>Binary data</h1>
<p>How do we proceed if we want to perform a similar analysis to linear regression but for a response variable which is not numeric?</p>
<p>Consider the following questions:</p>
<ul>
<li>What features of speech influence the likelihood of an utterance being perceived as true/false?<br />
</li>
<li>What lifestyle and demographic variables influence the chances that a person does/does not smoke?<br />
</li>
<li>Does preference for milk vs dark chocolate depend on personality traits?</li>
</ul>
<p>The common thread in the questions above is that they all contain a dichotomy: “hired/not hired,” “true/false,” “does/does not,” “milk vs dark.”<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>In practical research, many times we end up recording which category each unit belongs to, or whether an event or characteristic is either present (success) or not (failure).
We wish to examine factors associated with the event. Since we can rarely predict exactly whether an event will happen or not, what we in fact look for are factors associated with the <em>probability</em> of that event happening.</p>
<p>This is consistent with linear regression. In linear regression we model the mean of <span class="math inline">\(y\)</span> as a function of <span class="math inline">\(x\)</span>. Remember, for each value of <span class="math inline">\(x\)</span> we can have many possible values of <span class="math inline">\(y\)</span> see <a href="01_models.html">Week 1</a>.</p>
<p>However, the mean of a binary 0/1 variable is the probability of success, i.e. <span class="math inline">\(P(Y = 1)\)</span>. Consider 10 observations on a variable <span class="math inline">\(y\)</span> comprising 7 successes and 3 failures: 0,0,0,1,1,1,1,1,1,1
<span class="math display">\[
\text{average of }y = \frac{3*0 + 7*1}{10} = \frac{7}{10} = \frac{\text{num. successes}}{\text{num. trials}} = \text{prob. success} = P(Y = 1)
\]</span></p>
<p>So, when the response is binary, we are modelling the probability of success as a function of <span class="math inline">\(x\)</span>.</p>
<p>Consider this example showing whether or not a random sample of individuals have a given condition (0 = no, 1 = yes) at a given age.
The x-axis displays age in years after mean-centering, and the y-axis whether or not the subject has the condition.
<img src="15_binary_logistic_files/figure-html/unnamed-chunk-8-1.png" width="85%" style="display: block; margin: auto;" /></p>
<p>We notice a few things from the plot.</p>
<ol style="list-style-type: decimal">
<li><p>The linear regression model (red line) clearly extends beyond the possible range of values for a probability, which must be between 0 and 1. We can notice negative predictions for the probability associated to low ages, and even predicted probabilities greater than 1 for larger ages. This doesn’t make any sense!</p></li>
<li><p>It seems that higher ages are associated with more occurrences of the condition. Similarly, with lower ages we have less occurrences of the condition.</p></li>
<li><p>There must be an area in the middle where the probability of having the condition increases sharply, and then the probability is pretty stable in the two ends.</p></li>
<li><p>The logistic regression model (blue curve) captures this pattern. In the low ages, the probability of having the condition is very low. For high ages, the probability of having the condition is high (there are barely any people without the condition for mean-centred ages &gt; 5).
There clearly is a zone (ages 0-5) where people have or don’t have the condition. This is where the transition from low to high probability of success occurs.</p></li>
</ol>
<p>These exercises will show you how to fit a logistic regression model, and explain how to interpret the parameters.</p>
</div>
<div id="introducing-glm" class="section level1">
<h1>Introducing GLM</h1>
<blockquote>
<p><strong>Research Questions</strong></p>
<p>Is susceptibility to change blindness influenced by level of alcohol intoxication and perceptual load?</p>
</blockquote>
<p>Watch the following video:</p>
<p align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/FWSxSQsspiQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
<br>
<a href="https://www.cse.iitk.ac.in/users/se367/11/papers/simons-ambinder-05_change-blindness.pdf">Simons, D. J., &amp; Levin, D. T. (1997). Change blindness. Trends in cognitive sciences, 1(7), 261-267.</a>
</p>
<p>You may well have already heard of these series of experiments, or have seen similar things on <a href="https://www.netflix.com/gb/title/80190510">TV</a>.</p>
<div class="question-begin">
Question A1
</div>
<div class="question-body">
<p>For a given participant in the ‘Door Study,’ give a description of the outcome variable of interest, and ask yourself whether it is binary.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-189" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-189&#39;, &#39;sol-start-189&#39;)"></span>
</div>
<div id="sol-body-189" class="solution-body" style="display: none;">
<p>The outcome variable here is “Did the participant notice the person-swap?”<br />
The values of this are either “Yes” or “No” - they either do or don’t notice that the person they are talking to suddenly changes.</p>
<p><em>Be careful:</em> The video doesn’t actually state how they are measuring this - via post-experiment question of “did you notice?” or via what the experimenter perceives to be behaviour which indicates awareness of the swap. <em>Always think about what exactly you are measuring</em>.</p>
</div>
<p class="solution-end">
</p>
<div class="optional-begin">
drunkdoor.csv Dataset<span id="opt-start-190" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-190&#39;, &#39;opt-start-190&#39;)"></span>
</div>
<div id="opt-body-190" class="optional-body" style="display: none;">
<p><strong>Method</strong><br />
Researchers conducted a study in which they approached 120 people, recruited from within the vicinity of a number of establishments with licenses to sell alcohol to be consumed on-premises. Initially, experimenter A approached participants and asked if they were interested in participating in a short study, and obtained their written consent. While experimenter A subsequently talked each participant through a set of questions on multiple pieces of paper (with the pretense of explaining what the participant was required to do), experimenters B and C carrying a door passed between the participant and experimenter A, with experimenter C replacing A (as can be viewed in the video).</p>
<p>The perceptual load of the experiment was manipulated via a) the presentation of the door and b) the papers held by the experimenters. For 60 of these participants, the door was painted with some detailed graffiti and had a variety of pieces of paper and notices attached to the side facing the participants. Additionally, for these participants, the experimenters handled a disorganised pile of 30 papers, with the top pages covered in drawings around the printed text. For the remaining 60, the door was a standard MDF construction painted a neutral grey, and the experimenters handled only 2 sheets of paper which had minimal printed text on them and nothing else.</p>
<p><strong>Measures</strong><br />
After experimenters A and C had successfully swapped positions, the participant was asked (now by C) to complete small number of questions taking approximately 1 minute. Either after this set of questions, or if the participant made an indication that they had noticed the swap, the experimenters regrouped and the participant was explicitly asked whether they had noticed the swap.<br />
Immediately after this, participants were breathalysed, and their blood alcohol content was recorded.</p>
<p><strong>Data</strong></p>
<p>The data can be downloaded from <a href="https://uoepsy.github.io/data/drunkdoor.csv">https://uoepsy.github.io/data/drunkdoor.csv</a>.<br />
A description of the variables included is presented below.</p>
<div id="rfaxqekhph" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#rfaxqekhph .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rfaxqekhph .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rfaxqekhph .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rfaxqekhph .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rfaxqekhph .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rfaxqekhph .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rfaxqekhph .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rfaxqekhph .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rfaxqekhph .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rfaxqekhph .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#rfaxqekhph .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rfaxqekhph .gt_from_md > :first-child {
  margin-top: 0;
}

#rfaxqekhph .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rfaxqekhph .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rfaxqekhph .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#rfaxqekhph .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rfaxqekhph .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#rfaxqekhph .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rfaxqekhph .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rfaxqekhph .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rfaxqekhph .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rfaxqekhph .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#rfaxqekhph .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rfaxqekhph .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#rfaxqekhph .gt_left {
  text-align: left;
}

#rfaxqekhph .gt_center {
  text-align: center;
}

#rfaxqekhph .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rfaxqekhph .gt_font_normal {
  font-weight: normal;
}

#rfaxqekhph .gt_font_bold {
  font-weight: bold;
}

#rfaxqekhph .gt_font_italic {
  font-style: italic;
}

#rfaxqekhph .gt_super {
  font-size: 65%;
}

#rfaxqekhph .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">description</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">id</td>
<td class="gt_row gt_left">Unique ID number</td></tr>
    <tr><td class="gt_row gt_left">bac</td>
<td class="gt_row gt_left">Blood Alcohol Content (BAC), A BAC of 0.0 is sober, while in the United States 0.08 is legally intoxicated, and above that is very impaired. BAC levels above 0.40 are potentially fatal.</td></tr>
    <tr><td class="gt_row gt_left">age</td>
<td class="gt_row gt_left">Age (in years)</td></tr>
    <tr><td class="gt_row gt_left">condition</td>
<td class="gt_row gt_left">Condition - Perceptual load created by distracting oject (door) and details and amount of papers handled in front of participant (Low vs High)</td></tr>
    <tr><td class="gt_row gt_left">notice</td>
<td class="gt_row gt_left">Whether or not the participant noticed the swap (Yes = 1 vs No = 0)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question A2
</div>
<div class="question-body">
<p>Read in the data, and plot the relationship between the <code>age</code> variable and the <code>notice</code> variable.</p>
<p>In <code>ggplot</code>, make sure you use <code>geom_point()</code>. Then, add to the plot the following code, <code>geom_smooth(method = "lm", se = FALSE)</code>. This will plot a simple linear regression fit <code>lm(notice ~ age)</code>.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-191" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-191&#39;, &#39;sol-start-191&#39;)"></span>
</div>
<div id="sol-body-191" class="solution-body" style="display: none;">
<p>Read in the data:</p>
<pre class="r"><code>drunkdoor &lt;- read_csv(&quot;https://uoepsy.github.io/data/drunkdoor.csv&quot;)
head(drunkdoor)</code></pre>
<pre><code>## # A tibble: 6 x 5
##   id        bac   age condition notice
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
## 1 ID1   0.0674     43 Low            1
## 2 ID2   0.00331    64 Low            0
## 3 ID3   0.00323    44 Low            1
## 4 ID4   0.0798     67 High           0
## 5 ID5   0.0668     62 High           0
## 6 ID6   0.0155     45 Low            1</code></pre>
<p>Plot whether or not the swap was noticed vs the age. Also add a simple linear model fit, and we use the <code>fullrange = TRUE</code> argument so that the line spans the entire plot (rather than just the range of the data):</p>
<pre class="r"><code>ggplot(drunkdoor, aes(x=age, y=notice)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = FALSE, fullrange = TRUE) +
  xlim(30, 80)</code></pre>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-12-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A3
</div>
<div class="question-body">
<p>Just visually following the line from the plot produced in the previous question, what do you think the predicted model value would be for someone who is aged 30?<br />
What does this value <em>mean</em>?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-192" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-192&#39;, &#39;sol-start-192&#39;)"></span>
</div>
<div id="sol-body-192" class="solution-body" style="display: none;">
<p>This plot will make it easier to see that the model predicted value for someone aged 30 is approximately 1.15.
<img src="15_binary_logistic_files/figure-html/unnamed-chunk-13-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>But what does <strong>1.15</strong> really mean here? Does it mean that the 30 year old participant will notice 1.15 experimenter-swaps? That doesn’t make sense, there is only one swap. Does it mean that they have a 115% probability of noticing the swap? That is closer, but again it doesn’t make much sense - how can we have a 115% probability?</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<p>What we are really interested in here is looking at how specific factors influence the <strong>probability</strong> of noticing the experimenter-swap.</p>
<p>We also recall that:</p>
<ul>
<li>a probability must be greater than or equal 0</li>
<li>a probability cannot be larger than 1</li>
</ul>
<p>Recall that in linear regression we have a term of the following form on the right-hand side of the equal sign
<span class="math display">\[
\beta_0 + \beta_1 x_{i1} + \dots + \beta_k x_{ik}
\]</span>
Such term is called a <em>linear predictor</em> because is a linear combination of the predictors.</p>
<p>The possible values of the linear predictor range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>. On the contrary, a probability ranges from 0 to 1.</p>
<p>Clearly, we cannot directly model the probability of success as the linear predictor. We need to first transform the probability to range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span> and then it is this transformation of the probability that is related to the linear predictor.</p>
<p>This is where the <strong>Generalised Linear Model (GLM)</strong> comes in. With a little bit of trickery, we can translate probability (restricted to between 0 and 1, and not represented by a straight line), into “log-odds,” which is both linear <em>and</em> unbounded (see Figure <a href="#fig:plodd">1</a>).</p>
<p><br></p>
<div class="yellow">
<p><strong>Probability, odds, log-odds</strong></p>
<p>If we let <span class="math inline">\(p\)</span> denote the probability of a given event, then:</p>
<ul>
<li><p>The <strong>probability</strong> <span class="math inline">\(p\)</span> ranges from 0 to 1.</p></li>
<li><p>The <strong>odds</strong> <span class="math inline">\(\frac{p}{1-p}\)</span> ranges from 0 to <span class="math inline">\(\infty\)</span>.</p>
<p>To see this, consider what happens in the extremes.</p>
<ul>
<li><p>When <span class="math inline">\(p=0\)</span>, <span class="math inline">\(p / (1-p) = 0 / (1-0) = 0/1 = 0\)</span>.</p></li>
<li><p>When <span class="math inline">\(p = 1\)</span>, <span class="math inline">\(p / (1-p) = 1 / (1-1) = 1/0 = \infty\)</span>.</p></li>
</ul></li>
<li><p>The <strong>log-odds</strong> <span class="math inline">\(\log \left( \frac{p}{1-p} \right)\)</span> ranges from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>.</p>
<p>To see this, consider again what happens in the extremes.</p>
<ul>
<li><p>When <span class="math inline">\(\frac{p}{1-p} = 0\)</span>, we have <span class="math inline">\(\log(0) = -\infty\)</span>.</p></li>
<li><p>When <span class="math inline">\(\frac{p}{1-p} = \infty\)</span> we have <span class="math inline">\(\log(\infty) = \infty\)</span>.</p></li>
</ul></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:plodd"></span>
<img src="images/glm/plo.png" alt="Probability, Odds and Log-odds" width="95%" />
<p class="caption">
Figure 1: Probability, Odds and Log-odds
</p>
</div>
</div>
<div class="question-begin">
Question A4
</div>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>The probability of a coin landing on heads if 0.5, or 50%. What are the odds, and what are the log-odds?<br />
</li>
<li>The 2020 Tour de France winner, Tadej Pogacar, was given odds of 11 to 4 by a popular gambling site (i.e., if we could run the race over and over again, for every 4 he won he would lose 11). Translate this into the implied probability of him winning.</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-193" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-193&#39;, &#39;sol-start-193&#39;)"></span>
</div>
<div id="sol-body-193" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>A 50% chance of landing on heads is equivalent to the odds of <span class="math inline">\(\frac{0.5}{1-0.5} = \frac{0.5}{0.5} = \frac{1}{1}\)</span> (odds of 1 to 1, i.e., “equal odds”).<br />
The log-odds can be calculated using <code>log(1)</code> in R, which returns 0.<br />
</li>
<li>If Pogacar is predicted to win 4 for every 11 he loses, then this is means he is predicted to win 4 in every 15 races, so the implied probability of him winning is <span class="math inline">\(\frac{4}{15}\)</span> = 0.267.</li>
</ol>
</div>
<p class="solution-end">
</p>
<p>How is this useful?</p>
<p>Recall the linear model formula we have seen a lot of over DAPR2 so far.
For simplicity, focus on a single predictor <span class="math inline">\(x_{i1}\)</span> but this can be easily generalised to the case of <span class="math inline">\(k\)</span> predictors <span class="math inline">\(x_{i1}, ..., x_{ik}\)</span>.</p>
<p><span class="math display">\[
\color{red}{Y_i} = \color{blue}{\beta_0 + \beta_1 \ x_{i1}} + \epsilon_i
\]</span></p>
<p>Because we are defining a <em>linear</em> relationship here, we can’t directly model the probabilities (because they are bounded by 0 and 1, and they are not linear). But we <em>can</em> model the log-odds of the event happening.</p>
<p>The logistic regression model requires two components:</p>
<ul>
<li><p>One linking the transformed probability (log-odds) to the linear predictor:
<span class="math display">\[
\color{red}{\log \left(\frac{p_i}{1-p_i} \right)} 
= \color{blue}{\beta_0 + \beta_1 \ x_{i1} }
\]</span></p></li>
<li><p>The second liking the response variable with the probability:
<span class="math display">\[
Y_i \sim \text{Binomial}(n, p_i)
\]</span></p></li>
</ul>
<p>For binary responses, <span class="math inline">\(n = 1\)</span>.</p>
<p>The following plot displays the effect of varying the intercept and slope (specified respectively as <span class="math inline">\((a,b)\)</span>) on the predicted probability of success.</p>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-14-1.png" width="85%" style="display: block; margin: auto;" /></p>
<p>In the above plot it seems like the best curve to fit the probability of success is the one obtained with <span class="math inline">\(\beta_0 = 2\)</span> and <span class="math inline">\(\beta_1 = 3\)</span> (dashed line). The dotted line is the worst fit as it gives a high probability of success in an area of no observed success and a low probability of success in an area of high observed successes.</p>
<div class="optional-begin">
A bit of a tangent - How does the model get estimated?<span id="opt-start-194" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-194&#39;, &#39;opt-start-194&#39;)"></span>
</div>
<div id="opt-body-194" class="optional-body" style="display: none;">
<p><strong>Maximum Likelihood Estimation</strong></p>
For a linear regression, we heard about how the regression line can be found by “minimising the residual sums of squares” (i.e., we rotate the line to find the point at which <span class="math inline">\(\sum{(y - \hat{y})^2}\)</span> is smallest. This gave us the “best fitting line” (Figure <a href="#fig:resslineplot">2</a>).<br />

<div class="figure" style="text-align: center"><span id="fig:resslineplot"></span>
<img src="images/glm/ssdapr2.png" alt="https://uoepsy.github.io/dapr2/lectures/dapR2_lec03_LMintro.html#24" width="85%" />
<p class="caption">
Figure 2: <a href="https://uoepsy.github.io/dapr2/lectures/dapR2_lec03_LMintro.html#24" class="uri">https://uoepsy.github.io/dapr2/lectures/dapR2_lec03_LMintro.html#24</a>
</p>
</div>
For the logistic regression model, what we’re really wanting is the “best fitting <em>squiggle</em>” (Figure <a href="#fig:loglineplot">3</a>), and to get to this we must do something else.
<div class="figure" style="text-align: center"><span id="fig:loglineplot"></span>
<img src="15_binary_logistic_files/figure-html/loglineplot-1.png" alt="The sigmoid curve" width="60%" />
<p class="caption">
Figure 3: The sigmoid curve
</p>
</div>
<p>The reason we have to do something different is because for our actual observations, the event has either happened or it hasn’t. So we can’t take the raw data as “probabilities” which we can translate into log-odds. We can try, but it doesn’t make sense, and we would just be trying to fit some line between infinity and negative infinity. This would mean the residuals would also all be infinity, and so it becomes impossible to work out anything!</p>
<pre class="r"><code>drunkdoor %&gt;% 
  mutate(
    notice_odds = notice/(1-notice),
    notice_logodds = log(notice_odds)
  )</code></pre>
<pre><code>## # A tibble: 120 x 7
##    id        bac   age condition notice notice_odds notice_logodds
##    &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;
##  1 ID1   0.0674     43 Low            1         Inf            Inf
##  2 ID2   0.00331    64 Low            0           0           -Inf
##  3 ID3   0.00323    44 Low            1         Inf            Inf
##  4 ID4   0.0798     67 High           0           0           -Inf
##  5 ID5   0.0668     62 High           0           0           -Inf
##  6 ID6   0.0155     45 Low            1         Inf            Inf
##  7 ID7   0.00113    50 High           0           0           -Inf
##  8 ID8   0.0511     45 High           0           0           -Inf
##  9 ID9   0.00314    48 High           0           0           -Inf
## 10 ID10  0.0416     61 Low            0           0           -Inf
## # … with 110 more rows</code></pre>
<p>Instead, <em>maximum likelihood estimation</em> is used to find the set of coefficients which best reproduce the observed data.</p>
<p>For a given line on the plot where y = log-odds, and x = predictor variable, we can project our points on to it to find some candidate log-odd values for each observation, which we can then compare to the observed data (the 0s and 1s, or -Inf and Inf on the log-odds scale).</p>
Consider three possible lines we might fit below. You can see the observations at the <code>Inf</code> and <code>-Inf</code> points of the y-axis, and they are coloured by whether the event was observed or not. These are then projected down on to the possible lines. Recall that a log-odds of 0 is 50/50, or an odds of 1.<br />
In the left hand plot, all of the observations where the event <em>was</em> observed to happen (red dots at log-odds of +Inf), are modelled as having a log-odds of &gt; 0 (red dots on the line). However, so are a lot of the observations where the event was <em>not</em> observed (blue dots at log-odds of -Inf).<br />
In the middle plot, some red dots get incorrectly given log-odds &lt; 0, and a lot of blue dots get incorrectly given log-odds &gt; 0.
The right hand plot seems to fit a little better - there are only a few points which get given log-odds the wrong way from what we would expect.<br />

<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-16"></span>
<img src="15_binary_logistic_files/figure-html/unnamed-chunk-16-1.png" alt="Note: the dotted lines are not residuals, but just to show the projections of observations down to the line" width="100%" />
<p class="caption">
Figure 4: Note: the dotted lines are not residuals, but just to show the projections of observations down to the line
</p>
</div>
<p><br></p>
<p>If we take that right-hand plot above, and translate the log-odds back into probabilities, we see the squiggle!</p>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-17-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>What we can then ask for each of our candidate lines “what is the likelihood of the data, given this line?” To get this, we sum up the probabilities that observed 1s are predicted as 1s and that observed 0s predicted as 0s, at some given threshold which defines what we count as “predicted as 1” (e.g., is the predicted prob &lt; or &gt; 0.5?).<br />
For instance, the furthest right point is an observed 0, and so the likelihood of this data given the predicted probability is 1-0.04, or 0.96.<br />
<img src="15_binary_logistic_files/figure-html/unnamed-chunk-18-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>The cool thing is that computers do all this for us. <em>Maximum likelihood estimation</em> is just a method to find out which parameters maximise the likelihood of the data. In our context, it tells us what values of coefficients in <span class="math inline">\(\color{red}{\log \left(\frac{p_i}{1-p_i} \right)} = \color{blue}{\beta_0 + \beta_1 x_{i1} }\)</span> maximise the likelihood of reproducing the data we observed.</p>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question A5
</div>
<div class="question-body">
<p>To fit a logistic regression model, we need to use<code>glm()</code>, a slightly more general form of <code>lm()</code>.<br />
The syntax is pretty much the same, but we need to add in a <code>family</code> at the end, to tell it that we are doing a <em>binomial logistic</em> regression.<br />
(Note, we’ve been calling our outcome variable “binary,” but now we use “binomial?” Why? Well in the situation that we have a binary outcome consisting of 2 categories represented by 1s and 0s, we actually have a special case of a binomial (“the number of successes in n trials”) where <span class="math inline">\(n=1\)</span>, which is why it often gets referred to as ‘binary logistic regression’)</p>
<p>Using the <code>drunkdoor.csv</code> data, fit a model investigating whether participants’ age predicts the log-odds of noticing the person they are talking to be switched out mid-conversation. Look at the <code>summary()</code> output of your model.</p>
<div class="green">
<ul>
<li><code>lm(y ~ x1 + x2, data = data)</code><br />
</li>
<li>is the same as:<br />
</li>
<li><code>glm(y ~ x1 + x2, data = data, family = "gaussian")</code></li>
</ul>
<p>(<a href="https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss">Gaussian</a> is another name for the normal distribution)</p>
</div>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-195" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-195&#39;, &#39;sol-start-195&#39;)"></span>
</div>
<div id="sol-body-195" class="solution-body" style="display: none;">
<pre class="r"><code>model1 &lt;- glm(notice ~ age, data = drunkdoor, family=&quot;binomial&quot;)
summary(model1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = notice ~ age, family = &quot;binomial&quot;, data = drunkdoor)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3142  -0.9686  -0.3496   0.9635   1.7526  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  7.15625    1.57163   4.553 5.28e-06 ***
## age         -0.12999    0.02819  -4.612 4.00e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 166.32  on 119  degrees of freedom
## Residual deviance: 136.84  on 118  degrees of freedom
## AIC: 140.84
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A6
</div>
<div class="question-body">
<p>Interpreting coefficients from a logistic regression can be difficult at first.<br />
Recall what we are modelling - we are no longer modelling <span class="math inline">\(y\)</span>, but the log-odds of <span class="math inline">\(y\)</span>.<br />
Based on your model output, complete the following sentence:</p>
<p>“Being 1 year older decreases _________ by 0.13.”</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-196" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-196&#39;, &#39;sol-start-196&#39;)"></span>
</div>
<div id="sol-body-196" class="solution-body" style="display: none;">
<p>“Being 1 year older decreases <strong>the log-odds of noticing a mid-conversation person switch</strong> by 0.13.”</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A7
</div>
<div class="question-body">
<p>Unfortunately, if we talk about increases/decreases in log-odds, it’s not that intuitive.<br />
What we often do is translate this back into odds.<br />
The opposite of the natural logarithm is the exponential (see <a href="http://mathonweb.com/help_ebook/html/functions_3.htm">here</a> for more details if you are interested), and in R these functions are <code>log()</code> and <code>exp()</code>:</p>
<pre class="r"><code>log(2)</code></pre>
<pre><code>## [1] 0.6931472</code></pre>
<pre class="r"><code>exp(log(2))</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>log(exp(0.6931472))</code></pre>
<pre><code>## [1] 0.6931472</code></pre>
<p>Exponentiate the coefficients from your model in order to translate them back from log-odds, and provide an interpretation of what the resulting numbers mean.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-197" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-197&#39;, &#39;sol-start-197&#39;)"></span>
</div>
<div id="sol-body-197" class="solution-body" style="display: none;">
<pre class="r"><code>exp(coef(model1))</code></pre>
<pre><code>##  (Intercept)          age 
## 1282.0913563    0.8781015</code></pre>
<div class="int">
<p>The odds of noticing a mid-conversation person-switch for someone age 0 is 1282:1.<br />
For every year older someone is, the odds of noticing reduces by a factor of 0.88.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A8
</div>
<div class="question-body">
<p>Based on your answer to the previous question, calculate the odds of noticing the swap for a one year-old (for now, forget about the fact that this experiment wouldn’t work on a 1 year old!)<br />
And what about for a 40 year old?</p>
<p>Can you translate the odds back to probabilities?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-198" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-198&#39;, &#39;sol-start-198&#39;)"></span>
</div>
<div id="sol-body-198" class="solution-body" style="display: none;">
<pre class="r"><code>exp(coef(model1))</code></pre>
<pre><code>##  (Intercept)          age 
## 1282.0913563    0.8781015</code></pre>
<blockquote>
<p>The odds of noticing a mid-conversation person-switch for someone age 0 is 1282:1.<br />
For every year older someone is, the odds of noticing reduces by a factor of 0.88.</p>
</blockquote>
<p>This means that for a one year old, the odds of noticing are <span class="math inline">\(1282*0.88\)</span>, or 1129:1.<br />
The odds for a 40 year old are <span class="math inline">\(1282*0.88^{40}\)</span>, or 7.71:1</p>
<p>And we can always then turn these back into probabilities.</p>
<p>From probabilities to log-odds (or logit):<br />
<span class="math display">\[
logit_i=\log \left(\frac{p_i}{1-p_i}\right)
\]</span>
From log-odds to probability:<br />
<span class="math display">\[
p_i=\frac{e^{logit_i}}{(1+e^{logit_i})}
\]</span></p>
<p>Predicted probability of noticing for a one year old = <span class="math inline">\(\frac{1129}{1 + 1129} = 0.99\)</span>
Predicted probability of noticing for a 40 year old = <span class="math inline">\(\frac{7.71}{1 + 7.71} = 0.89\)</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A9
</div>
<div class="question-body">
<p>We can easily get R to extract these predicted probabilities for us.</p>
<ul>
<li>Calculate the predicted log-odds (probabilities on the logit scale): <code>predict(model, type="link")</code><br />
</li>
<li>Calculate the predicted probabilities: <code>predict(model, type="response")</code></li>
</ul>
<p>The code below creates a dataframe with the variable <code>age</code> in it, which has the values 1 to 100. Can you use this object in the <code>predict()</code> function, along with your model, to calculate the predicted probabilities of the outcome (noticing the swap) for each value of age? How about then plotting them?</p>
<pre class="r"><code>ages100 &lt;- tibble(age = 1:100)</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-199" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-199&#39;, &#39;sol-start-199&#39;)"></span>
</div>
<div id="sol-body-199" class="solution-body" style="display: none;">
<p>This will spit out 100 predicted probabilities..</p>
<pre class="r"><code>predict(model1, newdata = ages100, type = &quot;response&quot;)</code></pre>
<p>Let’s add them to the <code>ages100</code> tibble</p>
<pre class="r"><code>ages100 &lt;- 
  ages100 %&gt;%
  mutate(
    predprobs = predict(model1, newdata = ages100, type = &quot;response&quot;)
  )</code></pre>
<p>and plot them against age!</p>
<pre class="r"><code>ggplot(data = ages100, aes(x = age, y = predprobs)) +
  geom_line()+
  labs(y=&quot;predicted probability of noticing the swap&quot;)</code></pre>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-26-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A9
</div>
<div class="question-body">
<p>Shortcut!</p>
<p>We can do this really easily with the <strong>sjPlot</strong> package!
Try running this code (replace <code>model1</code> with the name of your model):</p>
<pre class="r"><code>library(sjPlot)
plot_model(model1, type=&quot;pred&quot;)</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-200" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-200&#39;, &#39;sol-start-200&#39;)"></span>
</div>
<div id="sol-body-200" class="solution-body" style="display: none;">
<pre class="r"><code>library(sjPlot)
plot_model(model1, type=&quot;pred&quot;)</code></pre>
<pre><code>## $age</code></pre>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-28-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A10
</div>
<div class="question-body">
<p>We have the following model coefficients, in terms of log-odds:</p>
<pre class="r"><code>summary(model1)$coefficients</code></pre>
<pre><code>##               Estimate Std. Error   z value     Pr(&gt;|z|)
## (Intercept)  7.1562479 1.57163317  4.553383 5.279002e-06
## age         -0.1299931 0.02818848 -4.611569 3.996402e-06</code></pre>
<p>We can convert these to odds by using <code>exp()</code>:</p>
<pre class="r"><code>exp(coef(model1))</code></pre>
<pre><code>##  (Intercept)          age 
## 1282.0913563    0.8781015</code></pre>
<p>In order to say something along the lines of “For every year older someone is, the odds of noticing the mid-conversation swap (the outcome event happening) reduces by a factor of 0.88.”</p>
<p>Why can we <strong>not</strong> translate this into a straightforward statement about the change in <em>probability</em> of the outcome for every year older someone is?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-201" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-201&#39;, &#39;sol-start-201&#39;)"></span>
</div>
<div id="sol-body-201" class="solution-body" style="display: none;">
<p>We have to be careful - we are talking about an odds <em>ratio</em>.</p>
<p>Our model holds that a 21 year old has 0.88 the odds that a 20 year old has, and that a 51 year old has 0.88 the odds of a 50 year old.
But these are not the same in terms of probability. The probability between age and the probability isn’t linear, it is sigmoidal.</p>
<pre class="r"><code>example &lt;- tibble(
  age = c(20,21,50,51)
)

example &lt;- 
  example %&gt;% mutate(
    logodds = predict(model1, newdata = example, type = &quot;link&quot;),
    odds = exp(logodds),
    probs = predict(model1, newdata = example, type = &quot;response&quot;),
  )

example</code></pre>
<pre><code>## # A tibble: 4 x 4
##     age logodds  odds probs
##   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1    20   4.56  95.2  0.990
## 2    21   4.43  83.6  0.988
## 3    50   0.657  1.93 0.658
## 4    51   0.527  1.69 0.629</code></pre>
<ul>
<li><p>In log odds the difference is constant (it is a linear relationship):</p>
<pre class="r"><code>example$logodds[example$age == 21] - example$logodds[example$age == 20]</code></pre>
<pre><code>##          2 
## -0.1299931</code></pre>
<pre class="r"><code>example$logodds[example$age == 51] - example$logodds[example$age == 50]</code></pre>
<pre><code>##          4 
## -0.1299931</code></pre></li>
<li><p>Translated back into odds, the difference is not constant:</p>
<pre class="r"><code>example$odds[example$age == 21] - example$odds[example$age == 20]</code></pre>
<pre><code>##         2 
## -11.60945</code></pre>
<pre class="r"><code>example$odds[example$age == 51] - example$odds[example$age == 50]</code></pre>
<pre><code>##         4 
## -0.235046</code></pre>
<p>the multiplication, however, IS constant (this is the odds ratio):</p>
<pre class="r"><code>example$odds[example$age == 21]/example$odds[example$age == 20]</code></pre>
<pre><code>##         2 
## 0.8781015</code></pre>
<pre class="r"><code>example$odds[example$age == 51]/example$odds[example$age == 50]</code></pre>
<pre><code>##         4 
## 0.8781015</code></pre></li>
<li><p>This is the same thing we saw visually in Figure <a href="#fig:plodd">1</a>!</p></li>
</ul>
</div>
<p class="solution-end">
</p>
</div>
<div id="glm-as-a-classifier" class="section level1">
<h1>GLM as a classifier</h1>
<div class="question-begin">
Question B1
</div>
<div class="question-body">
<p>From the model we created in the earlier exercises:</p>
<pre class="r"><code>model1 &lt;- glm(notice ~ age, data = drunkdoor, family=&quot;binomial&quot;)</code></pre>
<ol style="list-style-type: decimal">
<li>Add new column to the drunkdoor dataset which contains the predicted probability of the outcome for each observation.<br />
</li>
<li>Then, using <code>ifelse()</code>, add another column which is these predicted probabilities translated into the predicted binary outcome (0 or 1) based on whether the probability is greater than &gt;.5.<br />
</li>
<li>Create a two-way contingency table of the predicted outcome and the observed outcome.</li>
</ol>
<p><em>Hint:</em> you don’t need the <code>newdata</code> argument for <code>predict()</code> if you want to use the original data the model was fitted on.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-202" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-202&#39;, &#39;sol-start-202&#39;)"></span>
</div>
<div id="sol-body-202" class="solution-body" style="display: none;">
<pre class="r"><code>drunkdoor &lt;-
  drunkdoor %&gt;%
  mutate(
    predprobs = predict(model1, type=&quot;response&quot;),
    predclass = ifelse(predprobs &gt; 0.5, 1, 0)
  )


drunkdoor %&gt;%
  select(notice, predclass) %&gt;%
  table()</code></pre>
<pre><code>##       predclass
## notice  0  1
##      0 42 19
##      1 20 39</code></pre>
</div>
<p class="solution-end">
</p>
A table of predicted outcome vs observed outcome sometimes gets referred to as a <em>confusion matrix</em>, and we can think of the different cells in general terms (Figure <a href="#fig:confmat">5</a>).<br />
Another way to think about how our model is fitted is that it aims to maximise (TP + TN)/n, or, put another way, to minimise (FP+FN)/n.<br />
Which is equivalent to the good old idea of minimising sums of squares (where we minimise the extend to which the predicted values differ from the observed values).<br />

<div class="figure" style="text-align: center"><span id="fig:confmat"></span>
<img src="images/glm/cmat.png" alt="Confusion Matrix" width="60%" />
<p class="caption">
Figure 5: Confusion Matrix
</p>
</div>
<div class="question-begin">
Question B2
</div>
<div class="question-body">
<p>What percentage of the n = 120 observations are correctly classified by our model, when the threshold is set at 0.5?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-203" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-203&#39;, &#39;sol-start-203&#39;)"></span>
</div>
<div id="sol-body-203" class="solution-body" style="display: none;">
<pre class="r"><code>sum(drunkdoor$predclass == drunkdoor$notice) / nrow(drunkdoor)</code></pre>
<pre><code>## [1] 0.675</code></pre>
<p>The model correctly classifies 67.5% of the observations.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="less-guided-exercises" class="section level1">
<h1>Less guided exercises</h1>
<div id="approaching-a-research-question" class="section level2">
<h2>Approaching a research question</h2>
<div class="question-begin">
Question C1
</div>
<div class="question-body">
<p>Recall our research question, which we will now turn to:</p>
<blockquote>
<p><strong>Research Questions</strong>
Is susceptibility to change blindness influenced by level of alcohol intoxication and perceptual load?</p>
</blockquote>
<p>Try and make a mental list of the different relationships between variables that this question invokes, can you identify one variable as the ‘outcome’ or ‘response’ variable? (it often helps to think about the implicit direction of the relationship in the question)</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-204" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-204&#39;, &#39;sol-start-204&#39;)"></span>
</div>
<div id="sol-body-204" class="solution-body" style="display: none;">
<p>The question seems to ask about two relationships:</p>
<ul>
<li>susceptibility to change blindness ← alcohol intoxication<br />
</li>
<li>susceptibility to change blindness ← perceptual load</li>
</ul>
<p>The arrows above are used to show the implied direction of the influence, and in the <code>lm()/glm()</code> syntax, you could imagine each of these mapping to a formula syntax we have seen a few times (e.g., <code>t.test(data$outcome ~ data$group)</code> and <code>lm(outcome ~ predictor)</code>). We can see that the ‘susceptibility to change blindness’ is our outcome variable:</p>
<ul>
<li><code>change blindness ~ alcohol</code></li>
<li><code>change blindness ~ perceptual load</code></li>
</ul>
<p>As a general rule of thumb, it is often worth asking yourself “why run two models when one will do?” Think about what we have learned about moving from simple to multiple regression - some of the explanatory power of <code>x</code> in the relationship <code>y~x</code> might be shared by the relationship <code>y~z</code>.
This will depend on precisely what quantity you want to estimate, i.e., “the overall effect of <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span> <em>independent of <span class="math inline">\(z\)</span></em>” or “the effect of <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span> <em>after partialling out the effect of <span class="math inline">\(z\)</span> on <span class="math inline">\(y\)</span></em>.” The former statement might indicate a simple bivariate relationship, and the latter requires more advanced techniques (e.g., multiple regression).</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question C2
</div>
<div class="question-body">
<p>Think about our outcome variable and how it is measured. What type of data is it? Numeric? Categorical?<br />
What type of distribution does it follow? For instance, do values vary around a central point, or fall into one of various categories, or follow the count of successes in a number of trials?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-205" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-205&#39;, &#39;sol-start-205&#39;)"></span>
</div>
<div id="sol-body-205" class="solution-body" style="display: none;">
<p>Our outcome variable here is <code>drunkdoor$notice</code>, and is stored as a set of 0s and 1s. These are the only two values that an observation can take, and they represent the number of successes in <span class="math inline">\(n = 1\)</span> trials.</p>
<p>So, from this we learn that our method of analysis should be suited to model this binary outcome. So things like <code>lm()</code> and <code>t.test()</code> are not very appropriate.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question C3
</div>
<div class="question-body">
<p>Think about our explanatory variable(s). Is there more than one? What type of variables are they? Do we want to model these together? Might they be correlated?<br />
Are there any other variables (measured or unmeasured) which our prior knowledge or theory suggests might be relevant?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-206" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-206&#39;, &#39;sol-start-206&#39;)"></span>
</div>
<div id="sol-body-206" class="solution-body" style="display: none;">
<p>We know that <code>drunkdoor$bac</code> is simply the observed blood alcohol level (BAC). This is technically measured as a proportion, but for the current purposes we can just treat it as any other numeric scale. However, we might consider scaling the variable so that instead of the coefficient representing the change when moving from 0% to 1% BAC (1% blood alcohol is fatal!), we might want to have the change associated with 0% to 0.01% BAC (i.e, a we want to talk about effects in terms of changing 1/100th of a percentage of BAC).
The <code>drunkdoor$condition</code> variable is an experimental manipulation. That is, the researchers had control over what observations fell into which group. We wouldn’t therefore expect any correlation between this and the <code>bac</code> variable (unless researchers did not allocate participants to conditions randomly).</p>
<p>If we were actually doing research in this area, we might already have the idea based on previous research that change-blindness appears to vary depending upon age. From the earlier exercises here we have some evidence to corroborate this. We may therefore want to include this in our model. If we don’t, any results might simply be due to, e.g. older people tending to be more highly intoxicated (and so we see an effects of alcohol that might actually be simply the effect of age).</p>
<p>We might also think about any other possible variables which might influence our results, even if we didn’t measure them. This sort of thinking becomes important in the discussion section.</p>
<div class="yellow">
<p><strong>John Stuart Mill - Three Criteria for Causality</strong><br />
To varying extents, all of these criteria can be incredibly difficult to satisfy. Criteria 3 especially is one of the things that makes scientific investigation so interesting.</p>
<ol style="list-style-type: decimal">
<li>The cause precedes the effect</li>
<li>The cause is demonstrably related to the effect</li>
<li>There are no plausible alternative explanations</li>
</ol>
<p><em>Mill, J. S. (1869). A System of Logic, Ratiocinative and Inductive: Being a Connected View of the Principles of Evidence and the Methods of Scientific Investigation. Harper and brothers.</em></p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="fitting-the-model" class="section level2">
<h2>Fitting the model</h2>
<div class="question-begin">
Question C4
</div>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>Write a sentence describing the model you will fit. It might help to also describe each variable as you introduce it.</li>
<li>Fit the model.</li>
</ol>
<p><strong>Things to think about:</strong></p>
<ul>
<li>Do you want BAC on the current scale, or could you transform it somehow?</li>
<li>Is condition a factor? What is your reference level? Have you checked <code>contrasts(drunkdoor$condition)</code>? (This will only work if you make it a factor first)</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-207" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-207&#39;, &#39;sol-start-207&#39;)"></span>
</div>
<div id="sol-body-207" class="solution-body" style="display: none;">
<div class="int">
<p>Whether or not participants noticed the swap mid-conversation (binary 0 vs 1) was modelled using logistic regression, with blood alcohol content (measured in 100th of percentages blood content) and perceptual load condition (low load vs high load, with low as the reference level) and age (years).</p>
</div>
<p>In the sentence above, I stated that I want blood alcohol in terms of 100ths of percentages, rather than percentages.</p>
<pre class="r"><code>drunkdoor &lt;- drunkdoor %&gt;% 
  mutate(
    bac100 = bac*100
  )</code></pre>
<p>I also stated that the low-load will be the reference level.<br />
Currently it is the other way around:</p>
<pre class="r"><code># make it a factor
drunkdoor$condition&lt;-factor(drunkdoor$condition)
contrasts(drunkdoor$condition)</code></pre>
<pre><code>##      Low
## High   0
## Low    1</code></pre>
<p>So let’s change it:</p>
<pre class="r"><code># change 0,1 column to 1,0, and rename it so it 
# compares high against low (not low against high)
contrasts(drunkdoor$condition) &lt;- cbind(High=c(1,0))
contrasts(drunkdoor$condition)</code></pre>
<pre><code>##      High
## High    1
## Low     0</code></pre>
<pre class="r"><code>changeblind_model &lt;- glm(notice ~ bac100 + condition + age, data = drunkdoor, family = &quot;binomial&quot;)
summary(changeblind_model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = notice ~ bac100 + condition + age, family = &quot;binomial&quot;, 
##     data = drunkdoor)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.01149  -0.31516  -0.00735   0.26706   2.23101  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   17.01764    3.55483   4.787 1.69e-06 ***
## bac100         0.60763    0.17431   3.486 0.000491 ***
## conditionHigh -5.60871    1.11634  -5.024 5.06e-07 ***
## age           -0.30482    0.06232  -4.891 1.00e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 166.322  on 119  degrees of freedom
## Residual deviance:  66.763  on 116  degrees of freedom
## AIC: 74.763
## 
## Number of Fisher Scoring iterations: 6</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question C5
</div>
<div class="question-body">
<p>Compute 95% confidence intervals for the log-odds coefficients using <code>confint()</code>. Wrap the whole thing in <code>exp()</code> in order to convert all these back into odds and odds-ratios.</p>
<p>Try the <strong>sjPlot</strong> package and using <code>plot_model()</code> on your model, but with <code>type="est"</code>. What do you get?
<strong>Tip:</strong>, for some people this plots seems to miss out plotting the BAC effect, so you might need to add:</p>
<pre class="r"><code>plot_model(model, type=&quot;est&quot;) +
  scale_y_log10(limits = c(1e-05,10))</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-208" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-208&#39;, &#39;sol-start-208&#39;)"></span>
</div>
<div id="sol-body-208" class="solution-body" style="display: none;">
<pre class="r"><code>confint(changeblind_model)</code></pre>
<pre><code>##                    2.5 %     97.5 %
## (Intercept)   11.0145707 25.2161032
## bac100         0.3009620  0.9932602
## conditionHigh -8.1588018 -3.7128209
## age           -0.4487299 -0.1994882</code></pre>
<pre class="r"><code>exp(confint(changeblind_model))</code></pre>
<pre><code>##                      2.5 %       97.5 %
## (Intercept)   6.075294e+04 8.937467e+10
## bac100        1.351158e+00 2.700023e+00
## conditionHigh 2.862051e-04 2.440857e-02
## age           6.384385e-01 8.191499e-01</code></pre>
<pre class="r"><code>sjPlot::plot_model(changeblind_model, type = &quot;est&quot;)+
  geom_hline(yintercept=1)+
  scale_y_log10(limits = c(1e-05,10))</code></pre>
<p><img src="15_binary_logistic_files/figure-html/unnamed-chunk-43-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="looking-beyond" class="section level1">
<h1>Looking beyond</h1>
<p>This week we have looked at one specific type of Generalised Linear Model, in order to fit a <em>binary logistic</em> regression. We can use GLM to fit all sorts of models, depending on what type of data our outcome variable is, and this is all through the <code>family =</code> part of the model syntax.</p>
<p>For instance, if we had data which was binomial but with an <span class="math inline">\(n &gt; 1\)</span>, for instance the number of correct answers in 10 trials:</p>
<div id="lieyjctmwq" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#lieyjctmwq .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lieyjctmwq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lieyjctmwq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lieyjctmwq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lieyjctmwq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lieyjctmwq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lieyjctmwq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lieyjctmwq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lieyjctmwq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lieyjctmwq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lieyjctmwq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lieyjctmwq .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#lieyjctmwq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lieyjctmwq .gt_from_md > :first-child {
  margin-top: 0;
}

#lieyjctmwq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lieyjctmwq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lieyjctmwq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#lieyjctmwq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lieyjctmwq .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#lieyjctmwq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lieyjctmwq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lieyjctmwq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lieyjctmwq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lieyjctmwq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lieyjctmwq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#lieyjctmwq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lieyjctmwq .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#lieyjctmwq .gt_left {
  text-align: left;
}

#lieyjctmwq .gt_center {
  text-align: center;
}

#lieyjctmwq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lieyjctmwq .gt_font_normal {
  font-weight: normal;
}

#lieyjctmwq .gt_font_bold {
  font-weight: bold;
}

#lieyjctmwq .gt_font_italic {
  font-style: italic;
}

#lieyjctmwq .gt_super {
  font-size: 65%;
}

#lieyjctmwq .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">participant</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">trials_correct</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">trials_incorrect</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">x1</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">id1</td>
<td class="gt_row gt_left">1</td>
<td class="gt_row gt_left">9</td>
<td class="gt_row gt_left">114</td></tr>
    <tr><td class="gt_row gt_left">id2</td>
<td class="gt_row gt_left">4</td>
<td class="gt_row gt_left">6</td>
<td class="gt_row gt_left">113</td></tr>
    <tr><td class="gt_row gt_left">id3</td>
<td class="gt_row gt_left">7</td>
<td class="gt_row gt_left">3</td>
<td class="gt_row gt_left">83</td></tr>
    <tr><td class="gt_row gt_left">id4</td>
<td class="gt_row gt_left">8</td>
<td class="gt_row gt_left">2</td>
<td class="gt_row gt_left">141</td></tr>
    <tr><td class="gt_row gt_left">id5</td>
<td class="gt_row gt_left">3</td>
<td class="gt_row gt_left">7</td>
<td class="gt_row gt_left">115</td></tr>
    <tr><td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td></tr>
  </tbody>
  
  
</table>
</div>
<p>We could model this with <code>family = "binomial"</code> using the two columns as the outcome:<br />
<code>glm(cbind(trials_correct, trials_incorrect) ~ x1, data = data, family = "binomial")</code></p>
<p><br>
<br>
Or if we had <em>count</em> data, which can range from 0 to Infinity (theoretically), e.g.:</p>
<div id="mwqgqedjmr" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#mwqgqedjmr .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#mwqgqedjmr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mwqgqedjmr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#mwqgqedjmr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#mwqgqedjmr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mwqgqedjmr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mwqgqedjmr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#mwqgqedjmr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#mwqgqedjmr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#mwqgqedjmr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#mwqgqedjmr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#mwqgqedjmr .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#mwqgqedjmr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#mwqgqedjmr .gt_from_md > :first-child {
  margin-top: 0;
}

#mwqgqedjmr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#mwqgqedjmr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#mwqgqedjmr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#mwqgqedjmr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mwqgqedjmr .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#mwqgqedjmr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mwqgqedjmr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#mwqgqedjmr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#mwqgqedjmr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mwqgqedjmr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mwqgqedjmr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#mwqgqedjmr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mwqgqedjmr .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#mwqgqedjmr .gt_left {
  text-align: left;
}

#mwqgqedjmr .gt_center {
  text-align: center;
}

#mwqgqedjmr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#mwqgqedjmr .gt_font_normal {
  font-weight: normal;
}

#mwqgqedjmr .gt_font_bold {
  font-weight: bold;
}

#mwqgqedjmr .gt_font_italic {
  font-style: italic;
}

#mwqgqedjmr .gt_super {
  font-size: 65%;
}

#mwqgqedjmr .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">person</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">n_fish_caught</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">age</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">id1</td>
<td class="gt_row gt_left">8</td>
<td class="gt_row gt_left">44</td></tr>
    <tr><td class="gt_row gt_left">id2</td>
<td class="gt_row gt_left">7</td>
<td class="gt_row gt_left">46</td></tr>
    <tr><td class="gt_row gt_left">id3</td>
<td class="gt_row gt_left">13</td>
<td class="gt_row gt_left">29</td></tr>
    <tr><td class="gt_row gt_left">id4</td>
<td class="gt_row gt_left">6</td>
<td class="gt_row gt_left">56</td></tr>
    <tr><td class="gt_row gt_left">id5</td>
<td class="gt_row gt_left">14</td>
<td class="gt_row gt_left">37</td></tr>
    <tr><td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td>
<td class="gt_row gt_left">...</td></tr>
  </tbody>
  
  
</table>
</div>
<p>We model this using <code>family = "poisson"</code>:<br />
<code>glm(n_fish_caught ~ age, data = data, family = "poisson")</code></p>
<div style="margin-bottom:100px">

</div>
<p><strong>For real studies demonstrating the effects used in the example here, see:</strong></p>
<ul>
<li><a href="https://www.cse.iitk.ac.in/users/se367/11/papers/simons-ambinder-05_change-blindness.pdf">Simons, D. J., &amp; Levin, D. T. (1997). Change blindness. Trends in cognitive sciences, 1(7), 261-267.</a><br />
</li>
<li><a href="https://www.sciencedirect.com/science/article/pii/S1053810013000032?casa_token=LRZHar5q8eIAAAAA:Rqb8AWhFmJBhLKHbM3RuoB2QaR2XvezrRGx-fJD_EGp_b-iI5OCy36GC_lmWpakoqi_In7T2ZH8">Colflesh, G. J., &amp; Wiley, J. (2013). Drunk, but not blind: The effects of alcohol intoxication on change blindness. Consciousness and cognition, 22(1), 231-236.</a><br />
</li>
<li><a href="https://onlinelibrary.wiley.com/doi/pdf/10.1002/acp.3441?casa_token=J8vaKjaBsmcAAAAA:3_zvcg0TB_6xbed49dGzgJAXYUr2vs_SxkfWsCRF1ebyJwvcyEvLzXOt3jxcOVCMiFc7ie55hFieyWw">Murphy, G., &amp; Murphy, L. (2018). Perceptual load affects change blindness in a real‐world interaction. Applied cognitive psychology, 32(5), 655-660.</a></li>
</ul>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<p>If you want a really nice resource to help you in your future studies, then <a href="https://bookdown.org/roback/bookdown-BeyondMLR/" class="uri">https://bookdown.org/roback/bookdown-BeyondMLR/</a> is an excellent read.</p>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>
A note: This sort of binary thinking can be useful, but it is important to remember that it can in part be simply a result of measurement. To answer some research questions, we need to consider an event as “success” = 1 and all other possibilities as “failure” = 0.
For instance, we might initially consider “has blond hair” to be binary “Yes/No,” but that doesn’t mean that in the real world people <em>either</em> have blond hair <em>or</em> they don’t. We could instead choose to measure hair colour via colorimetric measures of the energy at each spectral wavelength, meaning “blondness” could become a continuum. While binary thinking can be useful, it is not difficult to think of ways in which it can be harmful.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
